### ISSUE TITLE
MCSG Lobby Spawnpoint Rotation Wrong

### ISSUE THREAD

**Issue by iVelocityGaming** [MCGamerNetwork/Issues#109]
**Environment**

This occurs on all MCSG Lobbies on all locations.

**The issue**

When you spawn into the lobby, you are facing a wall instead of out towards the main part of the building.

**Steps to reproduce**

Join an SG server and see the way you face when you spawn.

**Miscellaneous information**

![Screenshot of problem](http://i.imgur.com/g8MjcGZ.jpg)

**Comment by forairan** [comment]
Low priority, but confirmed.

**Comment by forairan** [comment]
Should be fixed shortly.
Thanks for the report!
