### ISSUE TITLE
Items in frames can be obtained

### ISSUE THREAD

**Issue by N0vaKaine** [MCGamerNetwork/Issues#149]
Environment - Survival Games servers

The issue - Players can get items in item frames, which could contain OP items, such as diamonds, potions, etc.

Steps to reproduce - Hitting the Item Frame will cause the item to pop out!

@forairan @subv3rsion

**Comment by subv3rsion** [comment]
Issue's a bit old, but I'm surprised to see this was never fixed over time... this has now been resolved, and will be included in the next plugin push.
