### ISSUE TITLE
Teleport Items are Not Colored

### ISSUE THREAD

**Issue by GotCubes** [MCGamerNetwork/Issues#159]
Simply what the title says. On the preview network, the left click and right click directions were colored purple. On the new network, they are white.

http://imgur.com/kJHta94

**Comment by subv3rsion** [comment]
Another issue that's a bit older... left/right click colors currently do not exist on the dev network, and likely were removed as a result of hard to read colors (obviously) affecting readability. In the future, there may be a better looking instruction panel while hovering items.
