### ISSUE TITLE
/stats Doesn't Update

### ISSUE THREAD

**Issue by Seby011** [MCGamerNetwork/Issues#225]
Today I hopped onto MCSG V2 for the first time. I was really looking forward to the stat reset so I could get some pretty good stats.  I played 5 games and won 4, but when I went to do /stats, I had the exact same stats as I did yesterday.

**Comment by subv3rsion** [comment]
As we have upgraded our leaderboards system, this bug report is no longer relevant. I do believe this was fixed a long time ago, but I cannot confirm that for sure.
Thank you for your report.
