### ISSUE TITLE
Alaskan Village Spawn in Spec

### ISSUE THREAD

**Issue by EctoplasmicNinja** [MCGamerNetwork/Issues#238]
When the map Alaskan Village was chosen we were spawned into the map. However we were all spectators and could fly around. When the countdown to the start of the game finished one person won and the lobby reset.

Not sure if it is just this map but hope this helps.

**Comment by subv3rsion** [comment]
I cannot replicate this in production or testing. If you're able to replicate this in the future, please open a new issue with more information.
