### ISSUE TITLE
Maps not resetting and can't put out the fire  

### ISSUE THREAD

**Issue by bbs22201** [MCGamerNetwork/Issues#248]
I joined a game of icarus and right away I noticed there was fire on the ground so the map didn't reset so later I tried to put out the fire and it wouldn't work.

Bug Video-  https://www.youtube.com/watch?v=03pRAws2GN4&feature=youtu.be

**Comment by subv3rsion** [comment]
This issue appears to have been resolved, but never closed. In addition, being unable to put out fire was resolved.
