### ISSUE TITLE
Joining servers

### ISSUE THREAD

**Issue by BatteryLevelLow** [MCGamerNetwork/Issues#282]
I encountered this issue while trying to join a Survival Games server in the US hub.

When you try and join a game that is full, it takes you directly back to one of the hubs and then you have to go back threw the portal and go back to the signs each time this happens. 

This is a very annoying bug and would be amazing if it was fixed. Thanks!
Brock

**Comment by subv3rsion** [comment]
This appears to have been resolved somewhere over the last several months. You won't be teleported to the landing hub, but you will be teleported back to the minigame hub spawn. Instead of using signs, I would use the game menu (beacon in your item bar).
