### ISSUE TITLE
Survival Bingo GameMaster/Spectator Issue

### ISSUE THREAD

**Issue by Fluxion326** [MCGamerNetwork/Issues#294]
Try to separate your description into four different sections, if possible:

Environment

live network, location (US), server sb/ Survival Bingo 271, 4PM ACST

The issue
When spectating a game of survival bingo you can break and place blocks as well as access Furnaces, chests and crafting tables. You can also attack mobs as well has fly. 

Steps to reproduce
If staff, enter then exit gamemaster to become a spectator when in game or join the game after it has commenced to spectate it

Miscellaneous information
This bug could be used to cheat if the spec flew around collecting items then placed them for a participant in the game. Specs cannot drop items though

**Comment by forairan** [comment]
This will be fixed as of the next plugin push.
Thanks for the report!
