### ISSUE TITLE
/watch 

### ISSUE THREAD

**Issue by JLioner** [MCGamerNetwork/Issues#305]
when I try to spectate a random game, doing /watch sg (for example) I always end up returning to the Hub, as it's always PreGame, PreDeathmatch, or a full game... 
maybe you could limit the random picking of a server to only joinable servers (livegames with max 23 players+specs) :) 
Thank you for your work!

**Comment by sontate72** [comment]
This seems to be a bug. I have tried this, and even though there are probably at least 5 games going on, it tries to connect me to the one in PreGame or the one that is full.

**Comment by subv3rsion** [comment]
This should be resolve as of #603
