### ISSUE TITLE
MCGamer v2 Bug Report: (Staff) BattleGrounds Commands not working

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#331]
-= *Environment* =-

This occurs in the BattleGrounds mini game.

-= *The issue* =-

1) As a Staff member, after switching my gamestate to gamemaster, I am not able to use the /spec <player> or /spectate <player> command in order to teleport to the player and follow them around for evidence. This might seem a minor issue at first glance, but it is really difficult to get sufficient evidence of a player if you do not know where the player is located on the map.

2) This is a less urgent issue, but both Staff and players are not able to run the /kill command during a BattleGrounds game. 

-= *Steps to reproduce* =-

Join a BattleGrounds game - run the /kill command while playing - run the /spectate <player> command while being in Gamemaster.

-= *Miscellaneous information* =-

I have a recording of both issues in 1 video: https://www.youtube.com/watch?v=iOYvUR5LbtM&feature=youtu.be

**Comment by forairan** [comment]
It appears this issue was fixed a while back, and was just never closed.

Thanks for the report!
