### ISSUE TITLE
BG130 + BG157 Spawn Issues - Mobs spawning destroying maps

### ISSUE THREAD

**Issue by OhZola** [MCGamerNetwork/Issues#345]
There is an issue on BG130 that involves spawn issues and map issues:

When warping to Centre: http://prntscr.com/56v44k (Fall out of the world)
When warping to North: http://prntscr.com/56v47b http://prntscr.com/56v49k (Trapped in a pillar/block)
When warping to East: http://prntscr.com/56v4dl (In an enclosed area with 1 hole to exit.)
When warping to South: http://prntscr.com/56v4p1 (Spawn right by a hole in the map)
When warping to West: http://prntscr.com/56v53r (Trapped in a block and dying)

You can get under the map through tons of holes in the floor: http://prntscr.com/56v4ve

**Comment by subv3rsion** [comment]
Map information has been updated, and it appears that this is no longer a problem. If you encounter this further, please let us know.
