### ISSUE TITLE
censoring color bug

### ISSUE THREAD

**Issue by lukasabc123abc** [MCGamerNetwork/Issues#351]
Environment

this ocures in hub and may happen in every other place with the censoring

The issue

i dont know to mutch about this bug but it seems to override the chatcolor perms after a censor. this happend just now and it was in the Eu hub

Steps to reproduce

I dont realy know how you want to fix it and i dont get why it shoud be happening

Miscellaneous information

i got a secreenshot of this happening 
http://gyazo.com/20aea838af72657214ec9026ec594c4c i dont want to report this guy for it dont get me wrong but it woud be good for you fixing it so noone will se it happening and we will see loads of ppl trying to do it and we will have a verry cursed chat

**Comment by subv3rsion** [comment]
Better described in #393
