### ISSUE TITLE
MCGamer v2 Bug Report: /bugreports command broken

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#354]
-= *Environment* =-

This occurred to me in the main hub, but this will most likely be network wide.

-= *The issue* =-

Upon running the /bugreports command in chat, you will receive the following message:

To submit a bug report, please go to <unknown>

-= *Steps to reproduce* =-

Run the /bugreports command in chat.

-= *Miscellaneous information* =-

Screenshot: http://i.imgur.com/L3GbAiM.jpg

**Comment by subv3rsion** [comment]
Appears to have been resolved by statically linking the URL to the issue tracker in the plugin.

Thanks for the report!
