### ISSUE TITLE
Links not clickable in chat

### ISSUE THREAD

**Issue by froggytv** [MCGamerNetwork/Issues#360]
When the mods put a link in chat, such as apply.mcgamer.info, or the github link, it's not able to be clicked. Pretty much as simple as that. Gives no response when attempting to click on it.

**Comment by forairan** [comment]
Confirmed. This appears to be a case of Minecraft just not automatically linking the chat; I'll add in support for clickable links shortly.

**Comment by forairan** [comment]
This will be resolved with the next plugin push.

Thanks for the report!
