### ISSUE TITLE
MCGamer v2 Bug Report: Not registering punishments in-game

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#392]
-= *Environment* =-

This occurred to me while I was on the EU hub, but this will most likely be network wide.

-= *The issue* =-

After muting a player for Mass Demonstration for the 1st time, they came back a few minutes later to demonstrate again. I looked at their Xime page and saw that the first mute did not register on their history. I muted him for the same amount of time again (3 hours), and checked their page right after. Again the mute did not register. So I just muted them for the appropriate amount of time via the panel, which did work.

However, I can guarantee that 95% of the mutes I filed during that time did go through and were registered on the players their history. This only happens once in a while.

Link to that specific person their page: http://manage.mcgamer.net/player/SJCOLE/

-= *Steps to reproduce* =-

Since it did register most of my actions, I do not think it will be easy to reproduce. But I guess that trying it out on different players may be effective.

-= *Miscellaneous information* =-

Screenshot I took to include as evidence for the mute via the panel. It also indicates that the mute message did appear in chat, but it did not actually register. http://i.imgur.com/eNLKpSm.png

**Comment by subv3rsion** [comment]
Is this issue still occurring? This seems to be another issue that simply has faded away with complaints, so I'm not sure if it's still ongoing or if someone's fixed it along the way.

**Comment by vanicle** [comment]
The issue seems to be resolved.

**Comment by subv3rsion** [comment]
Thank you for confirming this. I'm assuming it probably was fixed over time, but it was not marked as closed here.
