### ISSUE TITLE
MCGamer v2 Bug Report: Color Codes Bypassing Filter

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#393]
-= *Environment* =-

Survival Games. This may be possible anywhere on the network.

-= *The issue* =-

Upon using a different color for each letter in a word, you are able to bypass the swear filter.

-= *Steps to reproduce* =-

Type the letters of a word that the swear filter censors in different colors and it should bypass the filter.

-= *Miscellaneous information* =-

Screenshot: http://i.imgur.com/662WZBA.png

**Comment by forairan** [comment]
This should be fixed as of the next deployment cycle.
Thanks for the report!
