### ISSUE TITLE
fishing rod duplicating in your inventory.

### ISSUE THREAD

**Issue by Grayfox888** [MCGamerNetwork/Issues#40]
US Battlegrounds
When I switch my items around my hotbar, sometimes my bow will turn into a fishing rod. 

proof: http://gyazo.com/57d44a960472582a34fa2b91df1aec46

**Comment by subv3rsion** [comment]
I'm also unable to replicate this, using the exact steps shown in the video, even with a large amount of lag (connecting to AU from US, in this case).
