### ISSUE TITLE
Party System Glitch

### ISSUE THREAD

**Issue by Zenocrafter** [MCGamerNetwork/Issues#408]
1. US Hub, continuously whenever attempted.

2. If you create a party, then disconnect from MCGamer, you are unable to rejoin the party. However, the party is not deleted (as it should be if there is no one in it), and you are unable to create another party with the same name.

3. To test this, make a party, leave the server, then try to join and/or recreate the same party.

**Comment by subv3rsion** [comment]
I'm unsure why this was left so long, I think we just overlooked this over time.

This issue has now been resolved, and some improvements have been made to the party system.
These changes will be pushed with tonight's plugin pushes.

Thanks for the report!
