### ISSUE TITLE
Yet Another Pop-up Ad on Website

### ISSUE THREAD

**Issue by cadecranda** [MCGamerNetwork/Issues#409]
Again, I received another pop-up/phish; this time, however, automatically downloaded a .dmg file.  I can upload it to a service if necessary for the ad provider.

Screenshot: http://gyazo.com/447418b2038c866f67d326c6b219cc23
Source-code: http://pastebin.com/3hywfYby
Link (PLEASE DO NOT CLICK IF YOU DO NOT WANT A POSSIBLE VIRUS/TROJAN. YOU HAVE BEEN WARNED): http://officialcomputerdownloads.net/mac/f3/?subid=mbs-f40&transaction_id=131c4478-3d5e-470c-a3b7-fced61566157&rand=5471594933ae2&entry=y&auto=y

**Comment by scott46743** [comment]
I have not once received a pop-up ad on the forums. It is probably a browser add on link PursePoint, etc. You should probably go to your control panel and delete this.

**Comment by subv3rsion** [comment]
For any future complaints regarding ads, email support@mcgamer.net, as this is not a bug.
