### ISSUE TITLE
MCGamer v2 Bug Report: La Brocanterie - OP Chest Room

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#413]
-= *Environment* =-

I found out about this issue on the 22nd of November around 6:49 PM CST. It occurred on server EU 1675 and the Survival Games map was called "La Brocanterie".

-= *The issue* =-

There is a house in the map with approximately 30 tier 1 chests inside of it. Both single and double chests. You need to enter the house by standing on a pressure plate which will open an iron door. Once you have entered the house, you cannot escape it yourself unless a teammate or another player opens the doors for you by using the pressure plates. Even though this could be seen as a trap since you are not able to escape the house on your own, it is still overpowered to have access to 30 tier 1 chests, especially with a teammate.

-= *Steps to reproduce* =-

Join a Survival Games game with the map "La Brocanterie". Then go to the following coordinates: 
x = -284
y = 68
z = -149

-= *Miscellaneous information* =-

Screenshot of the Chest room with the coordinates: http://i.imgur.com/JUhWfaH.png

**Comment by subv3rsion** [comment]
This appears to have been fixed and pushed (considering when this was submitted, I'd hope so).

Thanks for the report!
