### ISSUE TITLE
Hitboxes Shut Off

### ISSUE THREAD

**Issue by 3point14** [MCGamerNetwork/Issues#432]
Recurring issue for me, will be fighting on normal SG on the US servers, and their hitboxes will shut off, making me unable to hit, rod, or shoot them.

This happens to me about once every three games and it always results in my death.

https://www.youtube.com/watch?v=BElS97qcVRQ

Additional info: I'm playing on Optifine 1.7.2 and this does not happen to me on any other server I play on. It's also happened on US battlegrounds.

**Comment by sontate72** [comment]
Please fix, I keep dying to a bug that is unacceptable.

**Comment by subv3rsion** [comment]
We're currently working on an update for NoCheatPlus, and hopefully will have an updated configuration for it to go with the update. I'll be testing this over the next few days, and hopefully will have an update by Tuesday or Wednesday that's been pretty well tested.

**Comment by CAmadeusA** [comment]
As this bug is over 1 year old and has been resolved, this issue has been closed.
