### ISSUE TITLE
Fake person, couldn't win a game

### ISSUE THREAD

**Issue by xDavoCG** [MCGamerNetwork/Issues#437]
https://www.youtube.com/watch?v=aqXVxyUwf9A&list=UUx9sxi68aocy3PqnBiiETmw watch the end, I was the only person left and I didn't win

**Comment by subv3rsion** [comment]
Without the video, as well as additional details outlined in the README.md ([click here](http://github.com/MCGamerNetwork/Issues/README.md)), we cannot proceed.
If this issue is still ongoing after the 1.8 update, please reopen the issue per the README.
