### ISSUE TITLE
Footstep trail bug?

### ISSUE THREAD

**Issue by violetheart17** [MCGamerNetwork/Issues#440]
This happened on EU Hub 1534 at 3:40 AM.

Basically, I was messing with the new trails and such and I activated the footstep trail. I went into F5 mode and jumped, and they disappeared until I landed. Small bug, but it sure did bug me.

Activate footstep trail, go into f5 mode to see it, then jump.

http://youtu.be/ftQEzaLktPI

**Comment by subv3rsion** [comment]
This issue appears to simply be a sort of rendering issue, and it's very trivial; it'd take more time than it's worth to resolve it.

Thank you for the report!
