### ISSUE TITLE
Snowmen freezing everything over.

### ISSUE THREAD

**Issue by LadyOfLove** [MCGamerNetwork/Issues#448]
The snowmen are causing a lot of snow build up as shown here:
http://i.imgur.com/unTS69f.jpg
Is there some way we can have it despawn after a certain amount of time or steps?

**Comment by Gjosiah** [comment]
I can confirm that this is a client-side issue that we cannot prevent. It is not affecting the actual game world, and interacting with the blocks, as well as relogging / switching servers will reset the blocks that your client thought were snow.
