### ISSUE TITLE
Battle Grounds bow changing into fishing rod

### ISSUE THREAD

**Issue by acdc459** [MCGamerNetwork/Issues#457]
Bow changed into fishing rod when pulled back occasionally.

From what I've seen its only on battle grounds au servers.
It duplicates  the fishing rod and replaced the bow with that duplicated fishing rod.

The only way I know of to reproduce the  glitch is to be in a bow fight and it may randomly change the bow into a fishing rod.

**Comment by sontate72** [comment]
Seems to be fixed with the 1.8 update.

**Comment by subv3rsion** [comment]
Glad to hear it. Assuming this may have simply been a 1.7/1.8 dual compatibility issue.
Kind of the reason why it was necessary to swap off of the two -- supporting two versions in one plugin can be unpredictable.

Thanks for the heads up!
