### ISSUE TITLE
Players cannot interact with buttons/chests in the lobby.

### ISSUE THREAD

**Issue by KitMencha** [MCGamerNetwork/Issues#460]
This is network wide in the SG lobby.

In the latest update of the SG Lobby, I have implemented various things for players to do which includes opening chests, pressing buttons, opening doors, etc. None of these can be done currently but it could be done upon the release of MCGamer v2.

Reproduction is just going into an SG lobby and trying to open a chest.

**Comment by subv3rsion** [comment]
Should be fixed as of next plugin push.

Thanks for the report!
