### ISSUE TITLE
Cannot un-hide players (Magic Clock) in populated hubs

### ISSUE THREAD

**Issue by JoelColby** [MCGamerNetwork/Issues#463]
This is an expansion on issue #348. You cannot *un-hide* (make players visible) in hubs that have players in them. However, switching to a hub that has no players in it will allow you to un-hide players.

**Minecraft Client Version:** 1.8 (also occurs on 1.8.1 -- I have not tested 1.7.x versions)
**Environment:** Any hub or game mini-hub
**To Replicate:** 

1. Go to a hub with players in it. 
2. Toggle player visibility with the clock (hiding is not the issue).
3. Attempt to un-hide players. The message indicating the players are visible will never appear; instead you will be told to wait 5 seconds.
4. To "fix" the issue, enter any empty hub and toggle visibility.

I've replicated this bug in a YouTube video below. The beginning portion of the video demonstrates that the client is a 1.8 vanilla client with no modifications (no OptiFine):

https://www.youtube.com/watch?v=tf9UH9Nq8Jc

**Comment by subv3rsion** [comment]
Seems to be resolved. Likely resolved with the 1.8 upgrade (and no one thought to check it).

Slack Devin or me on CH if you notice it breaking again.
