### ISSUE TITLE
The Lost Zoo

### ISSUE THREAD

**Issue by AlphaDanny** [MCGamerNetwork/Issues#467]
On Elavity and I's new map "The Lost Zoo" there is no "Author" or "Map link" in the map info section. We would request to have the authors be: Elavity and AlphaDanny. 
Thank you

P.S. I was advised by a Sr. Mod to report the problem here, so I assume it is a bug.
 -Danny

**Comment by subv3rsion** [comment]
This appears to be resolved. Thank you for your report!
