### ISSUE TITLE
Treacherous Heights v2 Hole In The Dome

### ISSUE THREAD

**Issue by Fluxion326** [MCGamerNetwork/Issues#468]
Environment

This happened on the AU server

The issue

There is a hole in the dome on Treacherous Heights v2 at the coords 163, 77, 98

Steps to reproduce

Join a game with treacherous Heights 

Miscellaneous information

http://imgur.com/RB9vtJO,JWIsmMr

**Comment by subv3rsion** [comment]
Can confirm that this is still an issue.

**Comment by AlpakaWhacker** [comment]
Issue addressed and Fixed
