### ISSUE TITLE
Fly in Hubs Glitch

### ISSUE THREAD

**Issue by ButterScottch** [MCGamerNetwork/Issues#471]
Environment
All hubs and mini-hubs; all regions. 

The issue
People under platinum have access to /fly or flying capabilities. 

Steps to reproduce
1) Use an alt that is under platinum.
2) Try to fly (after using /fly if applicable)

Miscellaneous information
I know the devs are probably aware, but I know you guys like to have it here so I'll put it here :)

**Comment by subv3rsion** [comment]
I haven't seen normal players that weren't disguised flying around the hub for a while. Are you still able to see players flying in the hub as of late?

**Comment by subv3rsion** [comment]
I haven't seen or heard complaints about this ever since the 1.8 upgrade.
If you continue to see this problem, please let us know ASAP.

Thanks!
