### ISSUE TITLE
Survival Kingdom OP Chests

### ISSUE THREAD

**Issue by iVelocityGaming** [MCGamerNetwork/Issues#476]
**Environment**

AU 1126 on the 10th of December 2014 at 3:55AM CET on survival games.

**The issue**

On Survival Kingdom on Survival Games, there is multiple chests full of OP items such as enchant bottles, golden apples and crafting benches which can be placed where ever desired. 

**Miscellaneous information**

Some of the locations of the chests are featured in this video at 4:04, 7:55 and 10:06: https://www.youtube.com/watch?v=DhSHrIDpk3c

**Comment by subv3rsion** [comment]
Without the video, we cannot proceed with verifying this and fixing this. If you still have the video, or at least the locations, someone that handles maps issues can resolve this.
Otherwise, I will go ahead and close this issue.
