### ISSUE TITLE
Upon player joining party, alert all players

### ISSUE THREAD

**Issue by JLioner** [MCGamerNetwork/Issues#480]
>Where: Only tested on EU but probably everywhere

>Issue 1: 
If player A does /party invite B, and the player B joins the party by doing /party join PARTYNAME he joined the party, but partner A can't see a text such as "Player B joined your party". So he gets no information about who joins his party. Doing /party list all 10 seconds is a bit unprofessional. ;)
A short info about who joined would be very helpful.

====
>Issue 2:
Also if you do /party to list all party related comands the way to get the party to join the same sg lobby, /party warp, is not listed. So many players probably don't know how to do that. 

As this might be meant to be there, I posted the Issue report.

Thank you and have a good day all! :)

**Comment by subv3rsion** [comment]
Players will now be notified as of party joins, kicks, and quits.
