### ISSUE TITLE
MCGamer v2 Bug Report: Constant Disguise in BattleGrounds

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#490]
-= *Environment* =-

This issue seems to be occurring network wide. I noticed it on the EU region first, but I recorded the bug on the US network as well. This only happens on the BattleGrounds mini game.

-= *The issue* =-

Upon joining a BattleGrounds server / game, players who are able to use the /disguise command will be instantly disguised. They cannot undisguise while being in the game since it will give them an error that they need to be in spectator mode. As a member of Staff, I am able to undisguise in gamemaster and then go back in game with my real name, but donators are of course not able to get rid of their disguise this way.

-= *Steps to reproduce* =-

Join a BattleGrounds game and type /list to check your disguise name.

-= *Miscellaneous information* =-

I have a recording of the bug: https://www.youtube.com/watch?v=TB4jR0XXs7o&feature=youtu.be

**Comment by subv3rsion** [comment]
I cannot replicate this in the live version of the plugin. The only time I am disguised is when I previously disguised in the hub, as expected, which obviously appears to have not been the case in your video.
Are you still encountering this issue? If so, can you confirm when you last did /d?
If you do /d in a hub, then instantly move to a mini-game hub, then hop into a game, there is a _small_ chance that you might run into this issue.

**Comment by subv3rsion** [comment]
If you are still able to replicate this, please let us know. For now, this issue has been closed.
