### ISSUE TITLE
MCGamer v2 Bug Report: Quarter Quell Deathmatch Lightning

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#492]
-= *Environment* =-

I found out about this issue on the EU network on the 19th of December at 2:40PM CST. I was on server EU1645 on the Quarter Quell mini game when deathmatch was about to occur.

-= *The issue* =-

After the PreDeathmatch countdown has ended, all players will be struck by constant lightning, no matter where they are located on the map.

-= *Steps to reproduce* =-

Join a Quarter Quell game where deathmatch is about to occur.

-= *Miscellaneous information* =-

I have a recording of the issue: https://www.youtube.com/watch?v=wOJZwwoCw3o&feature=youtu.be

**Comment by subv3rsion** [comment]
This will be resolved as of the next plugin push. Thanks for the report!
