### ISSUE TITLE
MCGamer v2 Bug Report: Pets in Survival Games

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#494]
-= *Environment* =-

I noticed this issue on the EU network. In the recording provided below, it happened on server EU2008  in the Survival Games mini game on the 20th of December at 10:36 AM CST, but I have seen it occur multiple times now on any SG server.

-= *The issue* =-

Pets are sometimes being teleported into a Survival Games game together with their owner. They will constantly follow the player around. I have no information whether they can die or not in-game.

-= *Steps to reproduce* =-

Since this happens rarely, I do not know how you could reproduce this issue.

-= *Miscellaneous information* =-

I have a recording: https://www.youtube.com/watch?v=fLvHBZkLDWk

**Comment by Gjosiah** [comment]
I have added something to prevent this from occurring. This should take effect after our next plugin push.
