### ISSUE TITLE
Map Bug: Hole in Hubs

### ISSUE THREAD

**Issue by scott46743** [MCGamerNetwork/Issues#495]
_Environment_
All regions; all main hubs.

_The issue_
There is a random hole at these coordinates: 
x- 229
y- 15
z- 277

_Steps to reproduce_
1) Teleport to the coordinates above.

_Miscellaneous information_
http://i.imgur.com/JQFErog.jpg

**Comment by Gjosiah** [comment]
This issue has since been resolved.
