### ISSUE TITLE
/Friend bug

### ISSUE THREAD

**Issue by DarkNiightz** [MCGamerNetwork/Issues#497]
Environment

All regions, all times, all servers.

The issue

If you already have 4 friends added, you can't add anymore. I have tried both sending a friend request and accepting one, but nothing works.

Steps to reproduce

Add four people as a friend and try and add a fifth. 

Miscellaneous information :cactus: 

http://youtu.be/cOBgPXaFjs8 

I want to be popular :c

**Comment by subv3rsion** [comment]
It appears that the friend system is currently functioning properly. Can you guys confirm this?

**Comment by DarkNiightz** [comment]
Nope, you can still only have a limited amount of friends.

**Comment by forairan** [comment]
You're actually supposed to use `/friend accept <name>` to accept a friend request, but I can very easily see how this would be confusing. I'm reworking the friends system a bit to be a bit clearer, and this should be fixed the next time we push out updates.

**Comment by DarkNiightz** [comment]
I don't know if you watched the video or not but I tried "/friend accept <name>" and it doesn't do anything. 

to be fair at first I was doing it wrong but at the end of the video I was typing in the correct command and it wasn't doing anything at all..

**Comment by forairan** [comment]
Ah. Yeah, I watched most of the video, except for the end bit. Regardless, that just means it was encountering an error internally - unfortunately, it was never printing out the error. Hopefully, over the next few days (if not sooner), we'll have an updated friends system released that is a bit easier to use and more stable as well.

**Comment by DarkNiightz** [comment]
It would be great if you could add more features to the /friend command such as; Server Messaging and/or Teleportation to friends. 

There's not really any use for a /friend command when the only thing you can do with it is see who is online, it doesn't say what server they're in or anything... They could be on a completely different region to you and you wouldn't know it.

If you could message your friend or teleport to them that would be great!

**Comment by forairan** [comment]
Some of the things you suggested are actually part of the plan for the update to the system.
