### ISSUE TITLE
Pets visible in SG Games

### ISSUE THREAD

**Issue by Tawklo** [MCGamerNetwork/Issues#498]
It was during a Survival Games match on the US servers.

There was a player that still had their pets while the SG match was still going.

Not 100% sure

https://www.youtube.com/watch?v=Wf19cbp6JmY&feature=youtu.be
At around 10:17 is when you can see the pet!

**Comment by JLioner** [comment]
Same happened to me (2 times yesterday):
http://i.imgur.com/1TmKudm.jpg

**Comment by Gjosiah** [comment]
The most recent update has fixed this issue.
