### ISSUE TITLE
Mutes/Bans Bug

### ISSUE THREAD

**Issue by ButterScottch** [MCGamerNetwork/Issues#499]
_Environment_
All regions, all hubs, all servers

_The issue_
If a user is muted using XKMB, but the user has left, it shows that the user was muted in-game but does not show up on xime. 
For example:
User 1: *Breaks rule* 
*User 1 goes to an SG game* 
Moderator: /mute user1 <#> h Avoiding the Swear Filter
*Message confirms that the user has been muted, but it doesn't show up on Xime*

Also, if someone is rulebreaking, and the moderator mutes them from a different hub/minihub, it doesn't go through. This is incredibly annoying as we have to /goto them or mute them from the panel each time.

_Steps to reproduce_
1) Go into a hub
2) Wait for someone to spam.
3) Wait for them to leave.
4) Mute them using the M button on XKMB. 

_Miscellaneous information_

**Comment by subv3rsion** [comment]
This should be resolved in the next plugin push, assuming that the change doesn't cause a high load on our internal services. Thanks for the report!
