### ISSUE TITLE
Keeping your stuff after Winning a Game

### ISSUE THREAD

**Issue by JoshRocks159** [MCGamerNetwork/Issues#501]
What happens is. The winner of the game will not be kicked if the lobby is full. Which means they will keep their stuff and they will stay in the lobby they have won in. The spectators will just be invisible. My video proof is here : https://www.youtube.com/watch?v=tRHvsG4QyZc&feature=youtu.be

Also, the good part is that you don't spawn in with the stuff when the game starts.
Thank you.

**Comment by subv3rsion** [comment]
It looks like the video is no longer available. I do recall this issue, but I cannot say that I've seen it or heard about it as of late.
Are you still able to replicate this problem?

**Comment by JoshRocks159** [comment]
Your a few months late. So um sad to say, I kinda quit MCSG a while ago.....
