### ISSUE TITLE
Punishments Duplicating

### ISSUE THREAD

**Issue by ButterScottch** [MCGamerNetwork/Issues#502]
*Environment*
Punishments done in-game, specifically US but possibly EU, CA, & AU. 

*The issue*
When punishments are issued in-game, they sometimes duplicate up to 15 times. 

*Steps to reproduce*
It doesn't happen often, so you will probably have to sit in a hub and mute people (who break rules of course) until it happens. 

*Miscellaneous information*
From Xime: http://gyazo.com/75a374df235f813b2bedcca480264d54. You can also check the recent punishment section.  Names omitted from screenshot intentionally.

**Comment by subv3rsion** [comment]
Have you seen this as of recent? I haven't heard any complaints regarding this, and haven't seen it happen personally.
If I remember correctly, an update was pushed to resolve this several months back, but this issue may not have been updated.

**Comment by subv3rsion** [comment]
Since we haven't received further information from you, I'm going to go ahead and close this issue.
From my understanding, this issue was resolved several months ago, and I haven't heard any recent complaints about this -- I'm sure we'd hear plenty of complaints if this were still the case.
