### ISSUE TITLE
/ban not going onto xime panel

### ISSUE THREAD

**Issue by vladthegreat100** [MCGamerNetwork/Issues#504]
So I was in the US hub (For Survival Games) and a player was being abusive.
I did /ban [Player name] 3 days Abuse and when I clicked enter it told me that I had to confirm the ban, I confirmed the ban and it said that the ban was submitted correctly (and it is the right person I sent it to) but it does not show on the panel.

If you need a bit of help understanding the problem contact me over slack and I can send you guys the picture, thanks :)

**Comment by subv3rsion** [comment]
Duplicate of #499
