### ISSUE TITLE
MCGamer v2 Bug Report: Breakable Blocks in Winter Spleef 

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#505]
-= *Environment* =-

This occurs in the seasonal Winter Spleef mini game on the EU network. It might be network wide, but I haven't confirmed that theory yet.

-= *The issue* =-

As a spectator, players can break block in the map.

-= *Steps to reproduce* =-

Join the Winter Spleef mini game, die and try breaking one of the blocks on the map.

-= *Miscellaneous information* =-

I have a recording of the issue: https://www.youtube.com/watch?v=Hb2Q_g2oajI&feature=youtu.be

**Comment by forairan** [comment]
No longer applicable, but thanks for the report.
