### ISSUE TITLE
MCSG, finding /d players Glitch

### ISSUE THREAD

**Issue by pokibeys217** [MCGamerNetwork/Issues#506]
Well if you think a /d player is in your game, eg: huahwi and he's /d, if you type /stats huahwi it will say cthis player can not be found.. si that means he or she is in your game, and if you /stats huahwi's /d it will show his stats, sort of complecated but it actually works

**Comment by subv3rsion** [comment]
This has been fixed a couple weeks ago. Thank you for the report!
