### ISSUE TITLE
Platinums Cannot Kick Lower Ranks

### ISSUE THREAD

**Issue by Scraptonix** [MCGamerNetwork/Issues#507]
Platinum donors cannot kick other donors such as Diamond, Gold and Iron; they can only kick normal members.
This appeared on Huahwi's livestream when Platinums could not get into his game because it was full of donators they could not kick.

**Comment by subv3rsion** [comment]
This has been fixed as of about a month ago, at the very latest. If you're still encountering this, please let us know as soon as possible.

Thanks!
