### ISSUE TITLE
User's are able to get crafting tables and place them

### ISSUE THREAD

**Issue by mfunGamer** [MCGamerNetwork/Issues#510]
Environment:
    EU, SG, 1.1.2015, 16:26 (GMT)

    The issue:
    I found a user placing crafting tables in an SG Server.

   I do not know how to reproduce the issue since i joined shortly before.
   http://i.imgur.com/O97Yd0h.jpg

**Comment by subv3rsion** [comment]
Unfortunately, without additional details and steps on how to reproduce this, we cannot resolve this.
It's likely that there are crafting tables in a stray chest somewhere, which someone placed after finding them.
