### ISSUE TITLE
Wrong Rank when you /stats a /d Player.

### ISSUE THREAD

**Issue by GetRidaHim** [MCGamerNetwork/Issues#512]
Issue: When you /stats a /d player, it shows them as their disguise, although the rank may still appear as their regular rank, also with Moderators, /drank doesn't change their /stats to the appropriate rank.

How to replicate: /stats a /d player.

**Comment by GetRidaHim** [comment]
Issue: When you /stats a /d player, it shows them as their disguise, although the rank may still appear as their regular rank, also with Moderators, /drank doesn't change their /stats to the appropriate rank.

How to replicate: /stats a /d player.

**Comment by subv3rsion** [comment]
This has been resolved roughly 21-22 days ago.
