### ISSUE TITLE
Users cannot leave ./party 

### ISSUE THREAD

**Issue by ohjayx** [MCGamerNetwork/Issues#513]
Its been brought to my attention several times that if users join a party, whether its intentional or not, they cannot leave it after words.

After you do ./party leave [in and out of the same server where host is] it portrays the follow message
"You must be in a party to use this command" 

I recommended users to log off the servers for 5 minutes and return to see if it possibly automatically disbanded them from the party, but that failed as well.

**Comment by forairan** [comment]
I'm unable to reproduce this issue. Is the issue still occurring?

**Comment by subv3rsion** [comment]
We've determined this happens after a player disconnects without leaving. We're now investigating.

**Comment by subv3rsion** [comment]
This has been resolved, and will be pushed out tonight.

Thanks for the report!
