### ISSUE TITLE
MCTF2 Pyro Class

### ISSUE THREAD

**Issue by ButterScottch** [MCGamerNetwork/Issues#518]
*Environment*
All regions, MCTF2.

*The Issue*
The ammo in the pyro class is infinite, and it is a instant death. 

*Steps to Reproduce* 
1) Go into MCTF2.
2) Select the Pyro class.
3) Use it.

*Miscellaneous Information*
N/A

**Comment by arsenalfcgunners** [comment]
This is a game breaking glitch and needs to be resolved ASAP.
