### ISSUE TITLE
GameMaster In BG

### ISSUE THREAD

**Issue by ButterScottch** [MCGamerNetwork/Issues#520]
*Environment*
All regions, all battlegrounds

*The Issue* 
GameMaster is not working properly. When in GameMaster, you can be seen by everyone in the game.

*Steps to Reproduce*
1) Go into BG. 
2) Go into Gamemaster. 
3) Go into the game. 
4) Watch people hit you or call you a fly hacker.

*Miscellaneous Information*
N/A

**Comment by Gjosiah** [comment]
This issue was resolved when updating to 1.8.
