### ISSUE TITLE
Platinums Cannot Kick Certain Users

### ISSUE THREAD

**Issue by ButterScottch** [MCGamerNetwork/Issues#521]
*Environment* 
All regions, all servers.

*The Issue*
Platinums cannot kick gold or iron donors.

*Steps to Reproduce*
1) Get a platinum alt in-game.
2) Try to join a game filled with no normal members, and at least 1 iron/gold donors.

*Miscellaneous Information*
N/A

**Comment by subv3rsion** [comment]
Duplicate of #507
