### ISSUE TITLE
Survival Games Classic

### ISSUE THREAD

**Issue by Muix** [MCGamerNetwork/Issues#522]
Title: Survival Games Classic... Boring??

Description: In SGC or Survival Games Classic there use to be 4 maps, SG1, SG2, SG3 (ew xD not a fave bit laggy.) and SG4. Currently there is now only one map after the migration to the Antvenom network you could say. >.>. SG2 is broken, laggy, and boring after playing 50 games on the same map and starving to death. It would be helpful if the other 3 maps are brought back. Sg1, Sg3, and Sg4.

Example: MCSG, SGC, US. All servers.

The issue: Only one map, very laggy, broken, and boring after playing tons of times.

Steps to reproduce: You could re-add the other 3 maps like the old SGC, and take a quick look at SGC for yourself please. c:

Miscellaneous information: SG2 is missing pink house items, chest items on some lobbies, leaves are broken, spawn is destroyed in the center.

Please take these into consideration due to the SGC community would be likely appreciated if this issue is resolved. <3

**Comment by TheGametTag123** [comment]
Yes i also think they should fix it,
its much more popular now, i think more people would play it if they fixed it up and added back the maps, and payed more attention to classics

**Comment by Muix** [comment]
Thanks atleast someone understands. It has grown quite popular, but the ranks will go down due to 1 broken map that gets boring if you play it to much. Meaning they'd lose players from that game mode. :c

**Comment by KitMencha** [comment]
This is not a bug. Please use our forums for suggestions as this is out bug tracker.
