### ISSUE TITLE
MCGamer v2 Bug Report: mobs in Survival Games 3

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#525]
-= *Environment* =-

This issue occurred on the EU Network on the 11th of January, 2014 at 10:27 AM CST on EU2748.

-= *The issue* =-

Mobs were able to spawn in the following map: Survival Games 3. During the game, they were also able to kill the players.

-= *Steps to reproduce* =-

Maybe try joining a game where SG3 was chosen, but it might have been coincidence as well.

-= *Miscellaneous information* =-

Screenshot: http://i.imgur.com/7YSCNBP.png

**Comment by subv3rsion** [comment]
This appears to no longer be an issue. I'd chalk this up to an issue with the version of Spigot we were running at the time not respecting mobs being disabled.

Thanks for the report!
