### ISSUE TITLE
MCGamer v2 Bug Report: Disguised players joining Survival Bingo

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#528]
-= *Environment* =-

Confirmed that this issue occurs on all regions, so network wide.

-= *The issue* =-

Whenever a disguised player joins the Survival Bingo mini-game, it will display their real name in chat instead of the disguise name. Their name would appear in the old AntVenom chat system (the blue chat instead of the regular MCGamer joining / leaving message).

This was tested on the other AntVenom game types and it appears to be fixed there. The AntVenom chat system was removed over there as well, so that might have been the solution.

-= *Steps to reproduce* =-

Let player A join the Survival Bingo lobby. Then let player B join the lobby as well while being in /disguise. Player A will see Player B their real name in the blue "AntVenom" chat, rather than the disguise name.

-= *Miscellaneous information* =-

Screenshots: http://i.imgur.com/ZKmPqXK.jpg & http://i.imgur.com/CrS4QcB.png

Note: Since I'm a Senior Mod, I could see the 2 moderators joining the lobby, even though they were disguised. However, in the first screenshot, it can be proven that players with a lower rank can see a higher ranked player their real name instead of the disguise. (mfungamer, who is a mod, could see me join through the AntVenom chat)

**Comment by subv3rsion** [comment]
You're appear to be correct, the message appears to have simply been removed (checked DD for comparison).
This will be included in the next update.
