### ISSUE TITLE
MCGamer v2 Bug Report: /echopet (tab) revealing disguises

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#529]
-= *Environment* =-

Applies on all regions, network wide.

-= *The issue* =-

Upon typing /echopet then follow by the TAB button in the hub or lobby and maybe even in-game, players will be able to find out the real name of a disguised player. The real name would appear after the echopet command. I have video material below.

-= *Steps to reproduce* =-

Go into a lobby or hub with a disguised player, run the /echopet + TAB command and you'll be able to see the real name of that disguised player.

-= *Miscellaneous information* =-

Recording of the issue: https://www.youtube.com/watch?v=I3Zhlw-Iu1w&feature=youtu.be

**Comment by Gjosiah** [comment]
The most recent update will have fixed this issue.
