### ISSUE TITLE
MCGamer v2 Bug Report: Links not appearing in chat.

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#531]
-= *Environment* =-

Network wide, applies to all regions.

-= *The issue* =-

Upon putting a link in chat, whether it be http://report.mcgamer.info or support@mcgamer.net for example, neither of those will appear which makes it really difficult to moderate the network. They do appear for the person who put them in chat originally. However, anyone else who is in the hub at that time won't see the link.

-= *Steps to reproduce* =-

Put a link in chat. Then ask someone else in the hub if they saw it appear. They will say it did not.

-= *Miscellaneous information* =-

N/A.

**Comment by KitMencha** [comment]
We are aware of the issue as it is a bug with the filter which prevents IPs/Links being shown. The Developers are already looking into the issue. Thank you!

**Comment by Gjosiah** [comment]
A fix for this issue has been pushed to the network, and should now be live.
