### ISSUE TITLE
0 points - glitch

### ISSUE THREAD

**Issue by JLioner** [MCGamerNetwork/Issues#532]
-= Environment =-

Tested on EU and US (confirmed)

-= The issue =-

The amount of points infront of the players name is 0. -> /stating the players shows their real amount of points. If you experience that glitch you are not able to sponsor others (not enough points) and also lose 0 points for dying. (last Screenshot)
Does not happen to all players.

-= Steps to reproduce =-

Go into a lobby and see players having 0 points - /stating the players shows their real amount of points.

-= Miscellaneous information =-

Screenshots: 
http://imgur.com/a/0YcQv#0 
http://i.imgur.com/RRGONU0.jpg
http://i.imgur.com/nLvlyRq.jpg
http://i.imgur.com/w1jYfOL.jpg (US)
http://imgur.com/611rJY4

**Comment by subv3rsion** [comment]
Does this happen at any certain time of the day more often than others? Or does this simply happen all the time?

**Comment by JLioner** [comment]
oh mhm, I can't tell :/ Sorry

**Comment by subv3rsion** [comment]
Have you seen this issue as of late? I haven't taken a look at this in a while, but haven't heard any complaints regarding this, or seen it for myself.
