### ISSUE TITLE
Deadly Descent Lobby Issue

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#533]
In the lobby players can take fall damage, and when they die they are spawned in a normal MC world.

Reproducing this is pretty self explanatory.

Note: There use to be a glitch where you would not take fall damage in a game of DD.  I don't know if this glitch has been fixed because I have not been able to get into a game with enough players.  Seems to me like the fall damage is toggled the opposite of what it should be.

**Comment by subv3rsion** [comment]
This should be fixed in the next plugin update.

Thanks for the report!
