### ISSUE TITLE
"Null" Sign Glitch

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#534]
Environment: US hub after recent update.

Issue:
Instead of saying "Server starting shortly" or whatever it should say the signs just say "Null" on only a few gamemodes.  So far I can confirm that SGC and Color Zone have this issue.  Normal SG does not.  Haven't had a chance to check other gamemodes yet.

Reproduce:  Go to US hub and see for yourself.

**Comment by subv3rsion** [comment]
I'm unable to replicate this today, and I do not see any updates to resolve any "null" hub messages in the past couple of weeks.
Have you seen this problem recently?

**Comment by arsenalfcgunners** [comment]
I believe the issue is gone.

**Comment by subv3rsion** [comment]
In that case, I'll go ahead and close this report. Let us know if you see this recur!

Thanks for the report!
