### ISSUE TITLE
Auto Eat Glitch

### ISSUE THREAD

**Issue by ServerOfTheAltar** [MCGamerNetwork/Issues#536]
Japanese players have the ability to open and close a chest to make them eat while running similar to the fence post glitch.

**Comment by Gjosiah** [comment]
Is this glitch exclusive to Japanese players? If so, what makes it exclusive to them?

**Comment by sontate72** [comment]
I heard from a friend that this worked. We are both US players.

**Comment by ServerOfTheAltar** [comment]
It's unclear as to why they are the only ones able to do it. Most people claim it to be ping but that may be mere speculation.

**Comment by subv3rsion** [comment]
Can either of you provide steps on how to reproduce this, or do you have a video of someone doing this?

**Comment by subv3rsion** [comment]
I'm unable to replicate any issues similar to this on the EU or AU networks and having >100 - 200ms ping.
If you can provide us with instructions, we can most definitely look into this further, but until then I will close this report.
