### ISSUE TITLE
Survival Games - Tier 2's don't fill

### ISSUE THREAD

**Issue by GustyyHD** [MCGamerNetwork/Issues#541]
Environment:
On the EU live network. Since the 1.8 update (3/02/2015)

The issue:
Every tier 2 does not fill. They are empty. At corn and across the map. Tier 1's get filled. But tier 2's not.

Steps to reproduce::
Join a EU server. You will notice that every tier 2 spawn chest is empty, across the map every tier 2 will be empty too.

**Comment by PMMoLoToV** [comment]
I'd like to add to this that doesn't happen on every server. I've played a few games which all the tier 2's worked perfectly fine.

**Comment by forairan** [comment]
What maps seem to have this issue?

**Comment by PMMoLoToV** [comment]
SG4, I personally haven't seen it happen on different maps.

**Comment by forairan** [comment]
So any other map you've played doesn't seem to have this issue, correct?

**Comment by PMMoLoToV** [comment]
Ehhh... I don't trust my memories enough to confirm that, I only remember playing SG4 without having any tier 2's

**Comment by LygerByte** [comment]
I'd like to add that par 72, and SG Adrenaline also have this issue, I'll try to find more maps that have this problem.

**Comment by forairan** [comment]
Resolved in the latest plugin push.
