### ISSUE TITLE
Invisible players

### ISSUE THREAD

**Issue by PMMoLoToV** [MCGamerNetwork/Issues#542]
Players become invisible to certain other players since the 1.8 update.
For example, I wasn't able to see my opponoment in Deathmatch, and he was able to kill me, so I asume I was visible to him. Although, in the same game I was invisible for a friend of mine aswell.
This happened on EU1801 at 11:45 but I can confirm it happens on other server aswell.

**Comment by forairan** [comment]
Resolved in the latest plugin push.
