### ISSUE TITLE
Missing chest on SG4

### ISSUE THREAD

**Issue by PMMoLoToV** [MCGamerNetwork/Issues#545]
This should be a double chest
http://i.imgur.com/Wxe7Tpt.png
( Forgot to get the co-ord, but show this to any mod and they should know where it is )

**Comment by forairan** [comment]
Likely related to #541.

**Comment by subv3rsion** [comment]
This appears to have been fixed based on #541. If this issue is still ongoing, please do let us know.

Thanks for the report!
