### ISSUE TITLE
Invis glitch still happening in Battlegrounds

### ISSUE THREAD

**Issue by froggytv** [MCGamerNetwork/Issues#550]
Experienced multiple people invisible whilst disguised, as well as me. I /d'ed and asked people if they could see me. They couldn't.

**Comment by JLioner** [comment]
^

Also I feel like it need to be added that, as donors are automatically disguised and unable to undisguise, that is a pretty big issue.

**Comment by sontate72** [comment]
This has been noticed by mods in the cleansweep, so it should be fixed eventually.

**Comment by arsenalfcgunners** [comment]
I have experienced this glitch twice in SG as well.  One of the times was recent.

**Comment by subv3rsion** [comment]
Are you still able to replicate this? Several changes were introduced over the past couple of months that should've resolve this.

**Comment by subv3rsion** [comment]
Confirmed that others can see me while disguised in BG. This issue is now closed.

Thanks for the report!
