### ISSUE TITLE
Changed name and lost everything

### ISSUE THREAD

**Issue by bcfcAnt** [MCGamerNetwork/Issues#551]
I changed my name from "bcfcant" to "bcfcAnt" a few minutes ago and I have now lost:

a) Donor,
b) Leaderboard position (#16),
c) Stats.

I went to play and my stats are completely reset ;-;

**Comment by bcfcAnt** [comment]
I changed my alt too, that has kept its stats ;-;

**Comment by bcfcAnt** [comment]
It's updated I assume it took a while however I do not have Platinum anymore.

**Comment by Rustywolf** [comment]
Your platinum should return shortly. Sorry for the inconvinience.
