### ISSUE TITLE
Messages Duplicating in hub

### ISSUE THREAD

**Issue by Mnormansell** [MCGamerNetwork/Issues#552]
Not sure the hub number, but in US messages seem to randomly be duplicating.

http://i.imgur.com/4PdqqHt.jpg
http://i.imgur.com/qRuwB3K.jpg

**Comment by subv3rsion** [comment]
Have you seen this as of recent? This issue should have been resolved several months ago, but if this is still a problem, we will do some digging.

**Comment by subv3rsion** [comment]
If you continue to see this happen, let us know and please provide the same screenshots you have, as well as times and dates of when this occurred.
