### ISSUE TITLE
MCGamer v2 Bug Report: Alaskan Village Crashing

### ISSUE THREAD

**Issue by MattGlowstone** [MCGamerNetwork/Issues#553]
Environment

This has been occurring on the EU Network; might be network wide. Any SG server that will load the Alaskan Village map.

The issue

Server crashes upon loading the Alaskan Village map.

Steps to reproduce

Join a server with said map.

Miscellaneous information

N/A.

**Comment by subv3rsion** [comment]
Unable to replicate. It's likely that the server you were on either ran out of memory, or the map had some issues at the time. With that being said, the map loads fine at this time.
