### ISSUE TITLE
Pet invisibility (Horse)

### ISSUE THREAD

**Issue by JLioner** [MCGamerNetwork/Issues#554]
=======================
Environment
=======================

Hubs - All Regions

=======================
The issue
=======================

The horse is sometimes invisible. Donkey and Mule work perfectly fine but when changing to a horse, it sometimes appears to be invisible (sometimes not).

This section should provide a detailed explanation of the issue.

=======================
Steps to reproduce
=======================

See Video (down below)

=======================
Miscellaneous information
=======================

http://youtu.be/wFrZFNE2lM0

**Comment by subv3rsion** [comment]
It appears that somewhere along the lines of the past several months that this issue was fixed. I'm unable to replicate horses becoming invisible in any hub.
If you encounter this issue again, feel free to give us a shout!
