### ISSUE TITLE
Zone 85 Ladder Glitch

### ISSUE THREAD

**Issue by KILLERTITANS25** [MCGamerNetwork/Issues#556]
In the lighthouse on Zone 85 I noticed this while playing.
Where: Au Servers. ID:Au 1255, Survival Games.
When: 7:27pm Cst, 6th of February 2015

Basically the ladders in the lighthouse either did not spawn or just broke and spawned in on the floor. You can see the 8 ladders in my inventory. This however is the first time I have seen this because I do not normally visit the lighthouse

Evidence: http://imgur.com/4C3FDcd

**Comment by DarkNiightz** [comment]
That's a bug that was already patched and somehow broke again, someone has set a fire in front or behind the ladder which made them break.

**Comment by subv3rsion** [comment]
This will be resolved in the next plugin push. Thanks for the report!
