### ISSUE TITLE
Gamemaster

### ISSUE THREAD

**Issue by ButterScottch** [MCGamerNetwork/Issues#557]
*Environment*
All regions, all servers.

*The issue*
When you are in GameMaster, you cannot fly down by double tapping the space bar. Additionally, /togglep removes the body from a player, but not the name above them. Basically, GameMaster is like f1 except you can see names above heads and you can see chat.

*Steps to reproduce*
Go into GM, and look.

*Miscellaneous information*
http://i.imgur.com/5qmStMZ.jpg

**Comment by Muix** [comment]
Omg it's so annoying not being able to see your task bar thing unless you press the numbers. And being invisible flying through walls is annoying also. Fix that. o; ^

**Comment by subv3rsion** [comment]
This is part of the new "Spectator" mode in Minecraft 1.8.
The intention of the item bar is for you to select what player you're spectating, which is what GameMaster is intended for -- spectating players.
As for being able to stop flying (double tapping space) -- you cannot stop flying. This is another part of the new Spectator mode.

For more information regarding spectator mode, see: http://minecraft.gamepedia.com/Spectator
