### ISSUE TITLE
Crash in the hub

### ISSUE THREAD

**Issue by ThatsTurbo** [MCGamerNetwork/Issues#558]
When i join the hub i crash and a message says: "size of 20 is below server threshold of 256" or "incorrect data/header check". I don't know what to do D:
http://gyazo.com/47ef44f22d061d8d29dee2ba8640a74e
http://gyazo.com/ec19ec9d0ceb5f60f1132d313e4869d5

**Comment by Gjosiah** [comment]
Could you provide us with some more details like the client version you are using, or any output that you see in the client log (on the second tab of the Minecraft launcher)?

**Comment by ThatsTurbo** [comment]
I use 1.8.1 and optifine_hd_u_c7

**Comment by Gjosiah** [comment]
There does appear to be an issue, I have attempted to mimic your environment and have experienced trouble joining all minecraft networks using optifine C7. We're looking into this to see if there is something we can do to resolve this on our end.

**Comment by Gjosiah** [comment]
Could you provide us with a screenshot of the "size of 20 is below server threshold of 256" or "incorrect data/header check" error you were speaking of?

**Comment by ThatsTurbo** [comment]
http://gyazo.com/47ef44f22d061d8d29dee2ba8640a74e
http://gyazo.com/ec19ec9d0ceb5f60f1132d313e4869d5

**Comment by subv3rsion** [comment]
Can you provide us with a traceroute? https://support.cloudflare.com/hc/en-us/articles/200169336-How-do-I-run-a-traceroute-
Instead of "yourdomain.com", just use "us.mcgamer.net" (or which ever server you're connecting to).

**Comment by subv3rsion** [comment]
Closing due to lack of information. It sounds like a client-side problem, which you'll either want to open a thread on the forums, or contact Mojang for assistance.
