### ISSUE TITLE
[Battlegrounds] Doing /join bg random doesn't work

### ISSUE THREAD

**Issue by sontate72** [MCGamerNetwork/Issues#559]
When you type /join bg random, it says 
"[Xime] Unable to locate any servers for the game BG!"
You must do /watch bg random to join a game.

Proof: http://imgur.com/Xrv6GPm
Proof: http://imgur.com/Bj3jE7Q

**Comment by subv3rsion** [comment]
This will be resolved in the next plugin push. Thanks for the report!
