### ISSUE TITLE
Server GUI: clicking empty squares connects to other gamemodes

### ISSUE THREAD

**Issue by sontate72** [MCGamerNetwork/Issues#560]
When I open the Battlegrounds beacon GUI and click a square without a block, it teleports me into a different gamemode.
I came across three results:
A) Getting into a QQ lobby.
B) Starting to spectate an SG.
C) Going into the SG hub.

Proof: http://imgur.com/j7D3VTl
Proof: http://imgur.com/DyYB2J4

**Comment by subv3rsion** [comment]
Modified the title appropriately. This happens on any gametype.

**Comment by subv3rsion** [comment]
This appears to occur _after_ another server has occupied the slot in the server menu. It doesn't matter what gametype it actually is afterwards, it will forward you to that server that _used to be_ SG (or whatever hub you're in at the time).

This is a minor issue when it comes to full hubs and actively played games, but obviously can present a problem for smaller gametypes.

**Comment by forairan** [comment]
This _should_ be fixed in the next deployment cycle, although I can't say whether or not the fix will work (there's not enough player flow in our test environment to test this scenario).
Thanks for the report!
