### ISSUE TITLE
Premium Members not able to join full games

### ISSUE THREAD

**Issue by JLioner** [MCGamerNetwork/Issues#562]
============
Environment
============

At least EU

============
The issue
============

Many platinum and diamand donors have recently complained about not being able to join full games, and having wasted money for joining Full servers, but now not being able to.

============
Steps to reproduce
============

Probably be donor and try to join a full server.

**Comment by forairan** [comment]
This is an odd issue that seems to keep popping up, but we can't reproduce it at all (testing as diamond/platinum). Do you happen to know who was in the server at the time that you failed to join, i.e. was the server completely full of gold donors, full of diamond, or a mix-and-match of some ranks?

**Comment by bcfcAnt** [comment]
I've noticed it happen to servers which are above 24/24 for example: 25/24, I can never join them games.

**Comment by JLioner** [comment]
I can't reproduce it either, as I'm not a Plat/ dia donor, nor can I give more information atm..
Just heard people complaining about it and felt like letting you know. :)

**Comment by ButterScottch** [comment]
Nice formatting btw ;)

**Comment by GetRidaHim** [comment]
I believe this happens when players */party warp* their premium friends into the game, and it causes the number to go above 24 and nobody can join.

**Comment by subv3rsion** [comment]
This appears to have been fixed a little over a month ago. Let us know if you notice any further problems with join priorities!
