### ISSUE TITLE
Hub crashes (whole Minecraft)

### ISSUE THREAD

**Issue by JLioner** [MCGamerNetwork/Issues#563]
========
Environment
========

Hubs - (at least EU)

========
The issue
========

Seems like the hub randomly closes/crashes. This happends to all player in that hub (Tested multiple times via teamspeak). 
It says: "Downloading Terrain" (and that won't change). Basically the only thing you can do, is to close minecraft and start it again. - see video

========
Steps to reproduce
========

Be in a Hub and wait for it to crash (randomly?).

========
Miscellaneous information
========

Video evidence: http://youtu.be/fo0N6JnoO6o

**Comment by kpwn243** [comment]
What timezone was the computer clock in. I would like to check the logs of that server.

**Comment by JLioner** [comment]
Germany, GMT + 1 
But it happens pretty often

**Comment by JLioner** [comment]
just crashed again when I was online:
~ 18:34 GMT+1

**Comment by kpwn243** [comment]
Make sure you are posting the xid of the server that crashed as server numbers change

**Comment by JLioner** [comment]
how do I find out what the server's "xid" is? :o

**Comment by kpwn243** [comment]
its the number on your experience bar

**Comment by JLioner** [comment]
oh right, I'll keep an eye out next time :)

**Comment by JLioner** [comment]
happened again:

when: 23:18 GMT+1, 11th Feb.
where: Eu SG HUB 1477

**Comment by kpwn243** [comment]
Thanks for those. We have identified the issue that crashes the hubs and are looking into fixing said issue.  No more server crash details are required. Thanks for the help.

**Comment by JLioner** [comment]
Great, glad to be able to help :) Thank you very much! :)

**Comment by subv3rsion** [comment]
This appears to have been fixed a month or two ago, this was simply an issue with one of our monitoring systems ensuring that there were enough hubs for a specific gametype.
If you notice this again, please do let us know.

Thanks!
