### ISSUE TITLE
Vanish bug in BattleGrounds

### ISSUE THREAD

**Issue by Atrain111** [MCGamerNetwork/Issues#566]
I have been playing in BattleGrounds on AU and when I PvP I get told I am invisible. It seems that some people can see me but not everyone. I really want this fixed because people call me a hacker, get mad at me when I am just trying to play. I cannot undisguise so maybe it has something to do with the disguise plugin??

Thank you.

**Comment by Atrain111** [comment]
By the way my username in-game is BajanAustraliano

**Comment by subv3rsion** [comment]
Better described in #576
