### ISSUE TITLE
Different time-zones' affect on the scoreboard 

### ISSUE THREAD

**Issue by TheMinecraftPharaoh** [MCGamerNetwork/Issues#567]
So it has occurred to me, that all the servers run with the Central Standard Time which regards to the United States rather than any other region, which makes it confusing for people in other parts of the world, especially the European and Australian times which are affected by this because the time-zones are very much different and due to that the time is different in each region. I would suggest that we would get every region its own designated time depending on where the server is hosted, like for the Australian side, it would be the Australian Eastern Daylight Time, and for the European side it would be the Greenwich Mean Time Zone. I think that with this change people can easily recognize their actual time rather than having to convert the time written on the scoreboard to their own time.

**Comment by forairan** [comment]
This isn't a bug, though it's something we plan to implement in the future.

Quoting the readme:
```
Do not:
[...]
Submit suggestions; the issue tracker is only for bugs with current features
```
