### ISSUE TITLE
MCGamer v2 Bug Report: Pets following in SG / BG

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#570]
-= *Environment* =-

I have been noticing this issue a lot on the EU Network recently, but this is most likely network wide. SG  and BG game type.

-= *The issue* =-

Pets from the hub will often teleport with the player into a lobby and even in-game where they constantly follow the player around. Pets will be invincible, they will teleport to the player like they do in the hub and they will de-spawn upon their owner's death.

-= *Steps to reproduce* =-

Have a pet activated in the hub and try joining several lobbies in a row. Eventually, they will teleport into a lobby with you. Happens around 1 in 5 games.

-= *Miscellaneous information* =-

You also receive a message by EchoPet saying that your pet is following close behind you: http://imgur.com/IySGBob,sf7EPjE

https://www.youtube.com/watch?v=fLvHBZkLDWk

**Comment by Gjosiah** [comment]
The recent update will have fixed this issue.
