### ISSUE TITLE
MCGamer v2 Bug Report: Sea Temple on Fortunate Island (SG)

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#571]
-= *Environment* =-

Noticed this on the EU network for the first time, but will most likely occur network wide. Server details can be seen in the video provided below.

-= *The issue* =-

A sea temple spawned on the map "Fortunate Island", wherefore part of the map disappeared to make room for the temple and wherefore certain rooms / areas were blocked.

-= *Steps to reproduce* =-

Join a game that has the map Fortunate Island loaded and go to the coordinates provided below to see if their is another temple. This occurred on the SG game type.

-= *Miscellaneous information* =-

Video: https://www.youtube.com/watch?v=M7PoRfF_Rx8
Screenshot: http://i.imgur.com/NZqrwdm.jpg

**Comment by Gjosiah** [comment]
This issue has been resolved in the latest update, and should take effect the next time we update the live servers.

**Comment by Nephilim04** [comment]
Occurs on Demons Breeze as well, http://imgur.com/yA4PUNW,2BDkYe5#0
