### ISSUE TITLE
MCGamer v2 Bug Report: Arcade Hub

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#572]
-= *Environment* =-

This occurred to me on the EU network, but again, will most likely occur network wide. Main area is the Hub.

-= *The issue* =-

Sometimes you will spawn in the old arcade hub after connecting to the servers or after being reconnected to the hub after a mini game like SG has ended. Players are able to teleport back to the main hub however. The Arcade hub should have been removed from the servers as the game types were added to the main hub through portals.

-= *Steps to reproduce* =-

As this happens randomly, I am not sure how you are able to reproduce this issue. I would say try to connect to the servers multiple times and see if you are being redirected to the arcade hub.

-= *Miscellaneous information* =-

Recording of the issue: https://www.youtube.com/watch?v=ktb4J30Tj00

**Comment by Gjosiah** [comment]
I have fixed an issue with one of our EU servers, and the arcade hub should no longer be present.
