### ISSUE TITLE
MCGamer v2 Bug Report: Invisible Players (Hub)

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#573]
-= *Environment* =-

This occurred on the EU network, will most likely occur network wide. Main area is the Hub.

-= *The issue* =-

Players will sometimes be invisible in the hub. The way we found out is through particle effects of some players who were standing AFK in the hub, while being invisible.

-= *Steps to reproduce* =-

Look around in the hub for random flying particles or for random particles standing in the hub.

-=* Miscellaneous information* =-

Recording of the issue with the fire particles: https://www.youtube.com/watch?v=ktb4J30Tj00

**Comment by JLioner** [comment]
Omg I found the reason for that issue!!

There are no invisible players, the particles will just stay after a player leaves/change Hubs!

Here a video evidence: http://youtu.be/mIYWmGg6PXM

**Comment by subv3rsion** [comment]
Are you still able to replicate this? I believe @Rustywolf made several changes that should fix invisibility problems, beyond those AFK and hidden, which I believe you should not see the particles.

**Comment by subv3rsion** [comment]
Tested this, and it no longer appears to be an issue, likely fixed either in the 1.8 upgrade, or with changes made earlier on.
Let us know if you encounter this again.

Thanks!
