### ISSUE TITLE
MCGamer v2 Bug Report: Glitched Spectator Mode (BG)

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#574]
-= *Environment* =-

This occurred on the EU network, will most likely occur network wide. Main area is the game type BattleGrounds.

-= *The issue* =-

As a staff member, when going in game master, you will be put into the new 1.8 spectator mode, but instead of being completely invisible, your character will still wear their battle gear and weapons and therefore you are also unable to fly through blocks.

-= *Steps to reproduce* =-

Join a game of BattleGrounds and go into the game master mode. Then either enter your inventory or toggle f5 to view the issue.

-= *Miscellaneous information* =-

Recording of the issue: https://www.youtube.com/watch?v=yaVj4Tpz3sg

**Comment by ButterScottch** [comment]
Also, we cannot /spec.

**Comment by subv3rsion** [comment]
Both issues appear to have been resolved, as they're working on the live network.

Thanks for the report!
