### ISSUE TITLE
MCGamer v2 Bug Report: Invisible Disguised Players (BG)

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#576]
-= *Environment* =-

Network wide on the BattleGrounds game type.

-= *The issue* =-

Due to the instant disguise glitch on the BattleGrounds game type, some players who have access to the disguise command can experience the invisibility glitch again. So far, from what I have noticed myself, anyone who has access to the command and who joins the game after you did, will be invisible to you.

-= *Steps to reproduce* =-

Let player A join BattleGrounds. Next, let player B who has access to the /disguise command join after player A and player A will notice that Player B is invisible to them.

-= *Miscellaneous information* =-

3 Recordings of the Issue. Axanite joined first, then myself (Nephilim), then lastly JLioner.

Axanite's perspective: https://www.youtube.com/watch?v=CRBogeOiQdU&feature=youtu.be
Nephilim's perspective: https://www.youtube.com/watch?v=ckdyrHOxI0I
JLioner's perspective: https://www.youtube.com/watch?v=9JrKgeaP6mg&feature=youtu.be

**Comment by Rustywolf** [comment]
Fixed as of the disguise fix patch
