### ISSUE TITLE
MCGamer v2 Bug Report: Chest Glitch in SG Lobby

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#577]
-= *Environment* =-

Network wide, the SG lobby at the top of the library.

-= *The issue* =-

Upon spam right clicking the chest that is located on top of the library right before the game starts, players might be able to take two items out of it (an enderpearl and an enchanted diamond axe) and glitch them into the game.

-= *Steps to reproduce* =-

Follow the steps provided in the video below.

-= *Miscellaneous information* =-

Recording of the issue: https://www.youtube.com/watch?v=94N4K3WF1cc&feature=youtu.be

**Comment by subv3rsion** [comment]
This is not a technical possibility due to the simple fact that items can't be taken from a chest in another dimension/map. Even if it were a possibility, your items are cleared when the game hits the "pregame" phase.
