### ISSUE TITLE
Solar Frost - Spawn Glitch

### ISSUE THREAD

**Issue by GetRidaHim** [MCGamerNetwork/Issues#578]
http://www.minecraftsurvivalgames.com/threads/weird-glitch-i-found-on-solar-frost.168784/#post-1804877

User reported the glitch and provided a screenshots. No other information was given.

**Comment by subv3rsion** [comment]
Unfortunately, without further information, we can't do much about this. I don't see any errors for the logs of that date/time, so we would need a detailed explanation of what happened, not just the end result.

I've got a feeling that it was likely that the player was spawned into the block that they're supposed to spawn on top of, and thus he fell through the ground to the DM arena. If that's the case, then we can fix that, we just need to know if this is actually the case.

We have no other reports about this, so I will close this under the assumption it was a one-time issue. Let us know if you see any further complaints.
