### ISSUE TITLE
Regeneration Hacks

### ISSUE THREAD

**Issue by AlpakaWhacker** [MCGamerNetwork/Issues#580]
This appears to be regeneration hacks.

https://www.youtube.com/watch?v=D5x6HR_NfQg

Location: US (may affect all regens)

This player should have been dead after 4 - 5 hits with a stone sword however managed to live after 9 hits in a row, soon followed by a further 7 hits in a row before being killed by the player using the regeneration hacks.

May wish to look into it as this has been seen in a few youtube videos since the update to only 1.8, one of which was reported to Gideon 5 days ago however since then, that video has been deleted.

**Comment by GetRidaHim** [comment]
Looking at the fast deterioration of the Stone Swords status, it looks like the player who has the sword never actually had it, but two player seemed to have grabbed it at the same time, and one had better connection than the other. 

This happens much more common than you think.

**Comment by arsenalfcgunners** [comment]
Yeah, it is just a glitch.  I have experienced it a few times myself.

**Comment by Rustywolf** [comment]
Ghost item, player was actually using his fists.
