### ISSUE TITLE
/friend commands not working

### ISSUE THREAD

**Issue by Buchenherz** [MCGamerNetwork/Issues#581]
As the title says, /friend <command> is not working for me. IGN: Buchenherz

**Comment by subv3rsion** [comment]
Unfortunately, "it is not working" is not a valid bug report, and does not provide us with any useful information in regards to resolving any problem(s) that may exist.
Please follow the [README.md](https://github.com/MCGamerNetwork/Issues/blob/master/README.md) and recreate your Github issue.
