### ISSUE TITLE
MCSG Weird Hits on Holiday Resort 

### ISSUE THREAD

**Issue by xMinecraftNerd** [MCGamerNetwork/Issues#583]
Environment:
Live Network, US, Server sg 538, 1:11 a.m. CST

The issue:
So me and my friend Huraii were playing on Holiday resort where we figured out this issue. My friend was changing his texture pack and at first I realized that I could not hit him with my fishing rod, so I started to hit him just to scare him when I noticed I could extremely far hits that also would make him go really high in the air. Not only were the hits getting him really high in the air but I could hit him multiple time while he was in the air.

Steps to reproduce:
None

Miscellaneous information:
This is footage of the issue.

http://www.youtube.com/watch?v=RBeR4PCxcNc&feature=youtu.be

**Comment by xPugPvPx** [comment]
I have found the same bug. It has happened to me and my friend, Alex a lot today. We were on lobyb games in deathmatch, and when we did a 1v1, Alex (with one hit) knocked me flying through the air and had incredible knockback. When I did it again, the same happened. Hope this gets fixed

**Comment by subv3rsion** [comment]
This issue has been resolved. The cause was simply a very bad Spigot update, which was resolved promptly once our team was available to update the servers.
