### ISSUE TITLE
#1 priorty kick glitch

### ISSUE THREAD

**Issue by 1X1Mike1X1** [MCGamerNetwork/Issues#591]
I get kicked 1st in every game I join, I have friends that join the game after me (THEY DONT HAVE DONOR) and I get kicked first almost instantly even though i join a no player game

**Comment by sontate72** [comment]
This might be due to your internet. Lagging out can happen frequently with a bad connection. Are you being kicked into the lobby or kicked out of the server?

**Comment by 1X1Mike1X1** [comment]
Get kicked to the lobby

**Comment by KitMencha** [comment]
This has been fixed in the latest patch. More information can be found here: http://www.minecraftsurvivalgames.com/threads/the-patch-notes-3-16-2015.172519/

Closed.
