### ISSUE TITLE
Disguised Glitch: /d undisguises in game

### ISSUE THREAD

**Issue by JLioner** [MCGamerNetwork/Issues#593]
======================
Description:
======================

======================
Environment
======================
All regions

======================
The issue
======================
If you are disguised in game (with the new disguise system) and you do /d ingame you will *un*disguise. 
/ud doesn't work.

======================
Steps to reproduce
======================
Join a Lobby, disguise, do /d in the middle of a game and get undisguised.

**Comment by Rustywolf** [comment]
This has been fixed, thank you for the report.
