### ISSUE TITLE
New Disguise Feature Glitch

### ISSUE THREAD

**Issue by FaithIndie** [MCGamerNetwork/Issues#594]
1. Environment: I was on SG US529 (Game ID: #14059090) at 2:25am EST. 

2. Issue: I was disguised (Drank gold) and I was playing Valleyside University and It was around 10-20 seconds until deathmatch and I realized my regular skin was back (The entire game it was an alex skin) and so I did /list and it said I was not disguised. I guess somehow it undisguised me in game.

3. Steps to reproduce: Not sure

4. Misc information: I was drank gold so maybe that had something to do with it? I have no idea

**Comment by subv3rsion** [comment]
I'm unable to find any logs for March 12, 2015 at 2:25AM EST. Can you confirm if you've encountered this issue since, or if it were a one-time occurrence?
When did you disguise, before you entered the MCSG server (in the hub), or after?
When did you /drank?

**Comment by subv3rsion** [comment]
If you are able to provide any further information, please open a new issue and we'll be happy to look into it further.
