### ISSUE TITLE
Party Time Issues 

### ISSUE THREAD

**Issue by SpectralSlayer** [MCGamerNetwork/Issues#595]
1st: If a game ends, the server crashes, so you play 1 game over and over 
http://i.imgur.com/6SBY80D.jpg

2nd: Spectators can get targeted (not hit) by mobs, so they can force them to hop down from the "TnT"-Buildings into the arena http://youtu.be/g02poJEd0MQ

**Comment by KitMencha** [comment]
Similar to #587
