### ISSUE TITLE
Creative Glitch

### ISSUE THREAD

**Issue by GetRidaHim** [MCGamerNetwork/Issues#597]
There's not much to explain, the command /creative join works. It spawns you in an empty world in which you fall endlessly.

**Comment by subv3rsion** [comment]
/creative join prompts me saying that 'join' is not a gamemode, and /join creative says that there are no game types for "CREATIVE".
Can you clarify what command you're using, and provide the additional information per the README?

**Comment by GetRidaHim** [comment]
Me and Razz talked it over a while ago, it was fixed. :) sorry for the typo!

**Comment by subv3rsion** [comment]
No worries, just wanted to make sure this wasn't an issue any longer (and that no rogue commands randomly appeared -- that'd be a fun bug...)
