### ISSUE TITLE
QuarterQuell not going to map problem.

### ISSUE THREAD

**Issue by xblaster112** [MCGamerNetwork/Issues#599]
Um, when i played QuarterQuell and the game started, it did not teleport us to the map and it was played in the lobby.

**Comment by subv3rsion** [comment]
As per the [README](https://github.com/MCGamerNetwork/Issues/blob/master/README.md), you will need to provide us with additional information, such as the map you were going into, the server ID and location, time and date, etc.
Without this information, we cannot act on this, as it could very well be a map specific issue.

**Comment by subv3rsion** [comment]
As we have not received further information from you, I'm closing this issue. If you can provide the additional information, please open a new issue using the format of the README linked above.
