### ISSUE TITLE
Some SG chests are broken again.

### ISSUE THREAD

**Issue by sontate72** [MCGamerNetwork/Issues#600]
I was playing a game on SG2, and the old glitch came back around.
So the chest tiering is messed up. You get golden apples, crafting tables, saddles, and spawn eggs, along with weapons and rods.

**Comment by subv3rsion** [comment]
Can you provide us with exact locations? I can't feasibly go through every single chest in the map in order to find which chest(s) you're talking about.

**Comment by subv3rsion** [comment]
Without further information, we cannot proceed with figuring out what's going on with the chests. If you can provide more information, feel free to open a new issue following the README format.
