### ISSUE TITLE
/watch needs adjustments for player balancing

### ISSUE THREAD

**Issue by sontate72** [MCGamerNetwork/Issues#602]
Doing /join sg will always send you to a full game or a game in Pregame, so it is completely broken.

**Comment by arsenalfcgunners** [comment]
it works if you have priority join.  It's just that if you don't, you get kicked very quickly.  Occasionally it will send you to a game that has just started, or is now full.  It works decently though.

**Comment by subv3rsion** [comment]
This should mostly only affect players that are not donors, as normal players won't be able to join full games.
This will be resolved soon™, which will involve players being placed on not completely full servers, allowing normal players a chance to use `/join sg` without a problem.

**Comment by sontate72** [comment]
Currently /watch has the issue, although /join seems to work.

**Comment by sontate72** [comment]
The join is currently broken again.

**Comment by forairan** [comment]
I've worked on a system that appears to work pretty decently when tested as a regular player - essentially, it tries to join you to servers that are around 50% full if you're a regular player, or resorts to the current sorting algorithm if you're a donor. Although this can't be fully solved, it should be much better as of the next deployment cycle.
