### ISSUE TITLE
Battleground leaderboards and player health not appearing anymore.

### ISSUE THREAD

**Issue by maddymoosers** [MCGamerNetwork/Issues#604]
They always used to appear but now there is just nothing. Other people can see the leaderboards and health though.

**Comment by sontate72** [comment]
Sometimes it works, sometimes it doesn't. I can confirm this bug.

**Comment by forairan** [comment]
Next time this happens, could you `/bugreport` and give us the state ID that's provided to you? We'd like to try and see if we can isolate this issue to any specific causes, and the debug data that command gives us would help greatly.

**Comment by arsenalfcgunners** [comment]
Devin I got a state ID for one that was broken. #4555

**Comment by Rustywolf** [comment]
This issue has been fixed and will be pushed to live upon the release of the new BG update.
