### ISSUE TITLE
Not all wins are registering

### ISSUE THREAD

**Issue by PDPM** [MCGamerNetwork/Issues#606]
After the stats reset I tried to pump out some wins. So I tried to aim for 16 wins but 3 of the wins didn't register. All the games played were on the EU servers.

To reproduce this, you have to win a game in Demons breeze and Alaskan village I think.

Ign: NotJJ

**Comment by arsenalfcgunners** [comment]
I have heard others stating that it's Demons Breeze and Alaskan Village as well.

**Comment by subv3rsion** [comment]
Can you provide me with times and dates of when this occurred, and your Minecraft username?

**Comment by subv3rsion** [comment]
This appears to be a resolved issue, and the game would not have counted for or against you. Unfortunately, we cannot retroactively replace wins, we can only fix the issues that caused the information to not properly be updated on your profile.

Thank you for the report, and please do let us know if you notice any further troubles.
