### ISSUE TITLE
Wins that didn't register: Have proof; both on Demons Breeze.

### ISSUE THREAD

**Issue by NickSharpx** [MCGamerNetwork/Issues#607]
Environment: The map Demons' Breeze on the server EU1759 (1 April 2015) 5:51 PM CDT: I won the game but it didn't count at all in the new statistics. Although, if I do /debug in game, I can see it counted (Doing some math between old and new statistics, you can have some leftovers, which are the games and wins that didn't register).
It also happened a second time, Demons' Breeze aswell; server EU 2877 (2 April 2015) 05:02 PM CDT, won that game too, 
I have two screenshots to prove my wins, here they are:
First win: http://prntscr.com/6otjur
Second win: http://prntscr.com/6otk23
The issue: As explained earlier aswell, the issue itself is the fact that all of the games and wins occurred on Demons' Breeze and Alaskan Village WILL NOT DISPLAY in terms of numbers on the player's new statistics, although, they will if you subtract your old statistics to the ones shown by /debug and then again substracting the statistics shown via /stats or the MCGamer website.
Steps to reproduce: Simply play on one of those maps and do the maths I've explained, quite simple as annoying, since I'd really like those two wins to display now.
Miscellaneous information: None

**Comment by subv3rsion** [comment]
Could you look through these games and see which one(s) may be related to the two games you listed above? These are all your games that were "lost" (gamewon = 0). The lower the ID at the end, the earlier the game:
http://www.mcgamer.net/round/mcsg/?round=355602
http://www.mcgamer.net/round/mcsg/?round=355406
http://www.mcgamer.net/round/mcsg/?round=355342
http://www.mcgamer.net/round/mcsg/?round=355119
http://www.mcgamer.net/round/mcsg/?round=347249
http://www.mcgamer.net/round/mcsg/?round=346609
http://www.mcgamer.net/round/mcsg/?round=318369
http://www.mcgamer.net/round/mcsg/?round=262855
http://www.mcgamer.net/round/mcsg/?round=242030
http://www.mcgamer.net/round/mcsg/?round=232139
http://www.mcgamer.net/round/mcsg/?round=169134
http://www.mcgamer.net/round/mcsg/?round=168815
http://www.mcgamer.net/round/mcsg/?round=168719
http://www.mcgamer.net/round/mcsg/?round=168008
http://www.mcgamer.net/round/mcsg/?round=142041
http://www.mcgamer.net/round/mcsg/?round=141447
http://www.mcgamer.net/round/mcsg/?round=40592
http://www.mcgamer.net/round/mcsg/?round=40507
http://www.mcgamer.net/round/mcsg/?round=40179
http://www.mcgamer.net/round/mcsg/?round=39765
http://www.mcgamer.net/round/mcsg/?round=28691
http://www.mcgamer.net/round/mcsg/?round=28509
http://www.mcgamer.net/round/mcsg/?round=27505
http://www.mcgamer.net/round/mcsg/?round=13742
http://www.mcgamer.net/round/mcsg/?round=10012
http://www.mcgamer.net/round/mcsg/?round=9979

These are the games listed as won:
http://www.mcgamer.net/round/mcsg/?round=354883
http://www.mcgamer.net/round/mcsg/?round=354691
http://www.mcgamer.net/round/mcsg/?round=346882
http://www.mcgamer.net/round/mcsg/?round=318078
http://www.mcgamer.net/round/mcsg/?round=241828
http://www.mcgamer.net/round/mcsg/?round=231621
http://www.mcgamer.net/round/mcsg/?round=217219
http://www.mcgamer.net/round/mcsg/?round=217039
http://www.mcgamer.net/round/mcsg/?round=216751
http://www.mcgamer.net/round/mcsg/?round=216527
http://www.mcgamer.net/round/mcsg/?round=168976
http://www.mcgamer.net/round/mcsg/?round=168506
http://www.mcgamer.net/round/mcsg/?round=168103
http://www.mcgamer.net/round/mcsg/?round=141825
http://www.mcgamer.net/round/mcsg/?round=141383
http://www.mcgamer.net/round/mcsg/?round=39067
http://www.mcgamer.net/round/mcsg/?round=29395
http://www.mcgamer.net/round/mcsg/?round=28075
http://www.mcgamer.net/round/mcsg/?round=14021
http://www.mcgamer.net/round/mcsg/?round=13826
http://www.mcgamer.net/round/mcsg/?round=13210

**Comment by NickSharpx** [comment]
#231621 and #231621; I'm sure about it, in fact, I had done /debug right
after those and seen how they technically counted on there, but would not
show in my stats, which was disappointing. Thanks for your attention, hope
they'll get counted as I found that quite annoying...

2015-04-18 11:00 GMT+02:00 Bill Ewing <notifications@github.com>:

**Comment by subv3rsion** [comment]
#231621 appears to have been one of the games that were counted as a win, and based on that information, it is showing on your stats. Can you provide me with the ID for the Alaskan Village win, or the other Demon's Breeze win?

You currently have 21 games won, and your overall SG stats say the exact same:
```
+----------+-------+--------+----------+---------+------------+----------+
| playerid | kills | chests | lifespan | gamewon | gameplayed | dmplayed |
+----------+-------+--------+----------+---------+------------+----------+
|   923465 |    86 |    627 |    23322 |      21 |         47 |       20 |
+----------+-------+--------+----------+---------+------------+----------+
```

**Comment by subv3rsion** [comment]
This appears to be a resolved issue, and the game would not have counted for or against you. Unfortunately, we cannot retroactively replace wins, we can only fix the issues that caused the information to not properly be updated on your profile.

Thank you for the report, and please do let us know if you notice any further troubles.

**Comment by NickSharpx** [comment]
Okay. Yesterday I was curious about the combined leaderboards and checked
them, however, when I found my stats there (approx #580) I noticed how I
had 1083 wins while the sum of my previous and current wins is 1087, I
couldn't understand why, so I'm telling you.. I think it's the same for the
games played. (IGN is, of course, NickSharpx)
Have a nice day
Il 20/apr/2015 01:55 "Bill Ewing" <notifications@github.com> ha scritto:
