### ISSUE TITLE
Buzzlightyear9 hacking

### ISSUE THREAD

**Issue by ColossalTitanFTW** [MCGamerNetwork/Issues#608]
The Hacker Buzzlightyear9 was hacking in the au mcsg from 2-6 am this morning 3/04/15

this is a link to my youtube channel to where i have uploaded a video and if this is not enough proof and have multiple other recorded vids of him hacking so if need more evidence please reply.

https://www.youtube.com/watch?v=YDLwRSUWZ8U&list=UUJhIgmRWbsGordWJVYIw6fA

**Comment by ColossalTitanFTW** [comment]
i also have another 12 hackers recorded now this will take me more then 24 hours to upload so if i could get in contact with a moderator it would help me alot

**Comment by ColossalTitanFTW** [comment]
i also have multiple other videos of people hacking so if i can get in contact with a moderator if would so helpful

**Comment by arsenalfcgunners** [comment]
This is the wrong place to report them.  Please report them here: http://www.mcgamer.net/forums/Report/  using this template: http://www.mcgamer.net/threads/report-abuse-templates.6742/
