### ISSUE TITLE
62deniig Hacking

### ISSUE THREAD

**Issue by ColossalTitanFTW** [MCGamerNetwork/Issues#609]
62deniig was hacking throughout mcsg in the early morning around 4-6.  03/04/15
He has been abusing what i think people call kill aura / aimbot, not bow aimbot

here is the video of this acurring which will be posted to my youtube 
https://www.youtube.com/watch?v=_M8nT-_Ejcw

**Comment by arsenalfcgunners** [comment]
This is the wrong place to report them. The issue tracker is for bugs. Please report them here: http://www.mcgamer.net/forums/Report/ using this template: http://www.mcgamer.net/threads/report-abuse-templates.6742/
