### ISSUE TITLE
almdroda and LegendGamerInMC

### ISSUE THREAD

**Issue by ColossalTitanFTW** [MCGamerNetwork/Issues#610]
these 2 vs'd each other in deathmatch in mcsg again around the time of 3-6 in the morning
and now again if need more proof please reply i have multiple videos of LegendGamerInMc but none of almdroda :'(

again here will be a video uploaded to my youtube: 
https://www.youtube.com/watch?v=j0KcHdHaMqk&feature=youtu.be

We need Moderators at this time from au or us it is really important that we get moderators at this time it's just hacker after hackers after hackers at that time of morning where i usually play so i think it would stop atleast some hackers and and the rest moderators can catch

**Comment by arsenalfcgunners** [comment]
This is the wrong place to report them. The issue tracker is for bugs. Please report them here: http://www.mcgamer.net/forums/Report/ using this template: http://www.mcgamer.net/threads/report-abuse-templates.6742/
