### ISSUE TITLE
Tahsin hacking

### ISSUE THREAD

**Issue by ColossalTitanFTW** [MCGamerNetwork/Issues#611]
Tahsin was hacking from the time of 4-6, killaura, aimbot, and bow aimbot is what i thought he had through out the process of watching all my videos.

here will be a video of him hacking on my youtube chanell: 
https://www.youtube.com/watch?v=rGZ8k4nnqYc&feature=youtu.be

p.s Do you think i should become a moderator? just a quick idea and in the video there's a guy who has clownfish on sorry about that

**Comment by arsenalfcgunners** [comment]
This is the wrong place to report them. The issue tracker is for bugs. Please report them here: http://www.mcgamer.net/forums/Report/ using this template: http://www.mcgamer.net/threads/report-abuse-templates.6742/
