### ISSUE TITLE
Z_stroup and Buzzlightyear9 hacking

### ISSUE THREAD

**Issue by ColossalTitanFTW** [MCGamerNetwork/Issues#612]
Z_stroup and buzzlightyear9 were using there hacks all morning from the time of 2-6 am on the 3/4/15 it made impossible for anyone to win so i want to make sure these 2 people face there consequence and hopefully it'll end in a perm ban. but then again it's the your job/moderators job to handle that.

here is the video and them hacking in a deathmatch  in minecraft survival games:
https://www.youtube.com/watch?v=mm5HRq30Tfo&feature=youtu.be

please this is really important that you ban these people it would make mcsg a much more happier environment

**Comment by arsenalfcgunners** [comment]
This is the wrong place to report them. The issue tracker is for bugs. Please report them here: http://www.mcgamer.net/forums/Report/ using this template: http://www.mcgamer.net/threads/report-abuse-templates.6742/

**Comment by ColossalTitanFTW** [comment]
the webpage is not available
