### ISSUE TITLE
/upgrade items with long name/lore

### ISSUE THREAD

**Issue by rf2minecraft** [MCGamerNetwork/Issues#613]
Environment
Hubs

The issue
When doing /upgrade in the hub, after clicking on the Bow to redeem a Stats Reset for Survival Games, all the items have a long lore/title and it's quite confusing which may be an issue....

Steps to reproduce
Be in a Hub and do /upgrades then click on the Bow and look at the item names/lores.

Miscellaneous information
Image: http://imgur.com/vuslAjW

**Comment by subv3rsion** [comment]
This appears to have been fixed just before this issue was opened, just not fixed on the live servers yet. Thanks for the report!
