### ISSUE TITLE
Survival bingo bug

### ISSUE THREAD

**Issue by lqdlqdlqd** [MCGamerNetwork/Issues#614]
When I play survival bingo and I die some of my chests, blocks, even houses (small) disappear. I have a video of it if you would like it.

**Comment by subv3rsion** [comment]
If you could provide the video, that'd be greatly appreciated, as logically, there should be no way for chests/blocks/small structures to disappear unless someone took them down, with the exception of the chest since it's protected.

**Comment by subv3rsion** [comment]
Without further information (the video), we cannot troubleshoot this further. This issue has been closed.
