### ISSUE TITLE
Rainbow-Names still active in Hungry Games Hub (AU)

### ISSUE THREAD

**Issue by JLioner** [MCGamerNetwork/Issues#616]
>>Environment:  Hungry Games Hub - AU only

>>The issue:  Rainbowed Names are still a thing there

>>Steps to reproduce:  Join AU Hungry Games Hub and type something in the chat.

Screenshots: http://i.imgur.com/JZiaWcL.jpg

**Comment by BigFella98** [comment]
This has been an issue in the main hub and survival games hub of AU also.

**Comment by subv3rsion** [comment]
This should be resolved as of the most recent restart of the AU network, if it hadn't been resolved already. Let us know if you see this again.
