### ISSUE TITLE
/goto command getting broadcasted in public deadly descent chat!

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#619]
Environment: Deadly Descent

How to reproduce: Type /goto playername in chat and it will be broadcasted to the whole chat.  It will not perform the command.  Example:

http://i.imgur.com/Ky8HIhs.png
http://i.imgur.com/epxh4a1.png

Edit: I should also note that I tested this in a few other gamemodes, and this did not happen.

**Comment by subv3rsion** [comment]
This does not occur while using an unmodified Minecraft client. One of your mods are affecting chat and sending the text of "/goto ..." rather than sending a command.
As this is not something we _should_ solve on our side, I'm closing this issue.
