### ISSUE TITLE
Bugs in survival games

### ISSUE THREAD

**Issue by coolsonic** [MCGamerNetwork/Issues#621]
I found a few bugs in survival games. One is before the games begin, it lets me move.
Another is that there is this little house in the lobby that if you open it will close. But after a while of closing and opening, it stays open. If you want I can give you a screenshot.

**Comment by subv3rsion** [comment]
While we appreciate you taking the time to report bugs, please do so in the proper manner as outlined in the [README](https://github.com/MCGamerNetwork/Issues/blob/master/README.md).
Issues not following the guidelines posted above will simply be closed.
