### ISSUE TITLE
PvPing in Battlegrounds Lobby

### ISSUE THREAD

**Issue by HolidaysInTheSun** [MCGamerNetwork/Issues#622]
Description: Players are able to PVP in the Battlegrounds lobby whereas they should only be allowed to PVP in the map. 
A) Environment: Battlegrounds Server 550. I'm pretty sure it's in all regions, and I think the bug has been there ever since they implemented this specific map http://i.gyazo.com/9385dd377c8ada2e5b4abd7fefe50ab6.png  
Honestly, I'm a noob and I have no clue what a "Live Network" and "Preview Network" is so I can't really answer that question.
B) The issue is that players are able to PVP where they normally wouldn't be able to as demonstrated by my good friend and me.
https://youtu.be/XD1xccNq9gs

Comments: I would've reported this issue sooner but I thought maybe a lot of players would address the issue and developers (or whoever sees this) would be flooded with Bug Reports about the same issue. I'm sorry if all of this is a little bit hard to understand but this is my first time reporting a bug. I do apologize for that.

**Comment by subv3rsion** [comment]
This should be resolved as of the next plugin and map push.

Thanks for the report!
