### ISSUE TITLE
Hungry Games game doesn't end.

### ISSUE THREAD

**Issue by ashleyindigital** [MCGamerNetwork/Issues#623]
Basically, I was the last tribute and it said that it would go to deathmatch?...
http://gyazo.com/a1a5542fe0fd3260d7b427de6a5eaed8

**Comment by forairan** [comment]
Are you sure you were the last remaining player? In this screenshot, it appears to show that 4 players were alive.

**Comment by ashleyindigital** [comment]
I don't have any sufficient evidence to show this, but the player that I killed before it said that deathmatch was starting was the last player in the game besides myself.

**Comment by forairan** [comment]
If this happens again, please `/bugreport` in-game when it happens, create a new issue, and include the ID number that command gave you. The command gives us a bit of debug data that can help us diagnose this issue.
