### ISSUE TITLE
UHC Worlds - No Teleport, voting, deathmatch and more

### ISSUE THREAD

**Issue by GustyyHD** [MCGamerNetwork/Issues#624]
Environment

On the EU beta of UHC worlds.

The issue

There are a few issues I noticed in my first game.
1. After the world is generated we never teleport to the world. We stay in the lobby. In deathmatch we teleport to a skyland arena where a 30 seconds countdown is before we can fall down.

2. Rather a small issue. The voting percentages seem to have really long decimals.

3. In the lobby it says you can fly but we are not able to.

4. The "Players remaining" seems to be stuck in deathmatch.

Steps to reproduce

When you join a UHC and play you will see all the bugs.

Miscellaneous information
I don't know if this happens on every server, this is just the experience of my first game.

I really hope this helped you devs out a little. I'll do my best to report all the bugs I encounter!

**Comment by forairan** [comment]
Most of these bugs should be fixed by now. Can you report back and let us know which, if any, of these bugs remain?

Thanks!

**Comment by subv3rsion** [comment]
From my understanding, most of these issues have been resolved, with the exception of the signs saying "You can fly in this lobby!" -- I'll leave that up to the team that handles the maps.

Let us know if you run into any further issues.

**Comment by CAmadeusA** [comment]
As this bug is over 1 year old and has been resolved, this issue has been closed.
