### ISSUE TITLE
Cannot submit media on the website 

### ISSUE THREAD

**Issue by MrNoisyKidd** [MCGamerNetwork/Issues#625]
Location: On the MCGamer website
Detail: everytime I try and submit a video clip on the media section it says "Media URL did not match any supported services." 

http://imgur.com/wS5R0Ga,FRNuSGW#1

**Comment by forairan** [comment]
I've made a change which should fix this issue; it appears as though the media system would not accept https links, only http links. Could you go ahead and try adding in the exact same link again (including the https://)?

**Comment by MrNoisyKidd** [comment]
It still doesn't work

**Comment by kpwn243** [comment]
After an arduous and long battle with our forums software I was able to fix the issue
