### ISSUE TITLE
UHC Worlds Games Merge

### ISSUE THREAD

**Issue by NerdyNoodles** [MCGamerNetwork/Issues#630]
Envioronment 
On the EU Beta of UHC Worlds

The Issue
When the deathmatch timer runs out, not only does it count as a loss for everyone, but the next game in the server is 'connected' to the previous one. It's hard to put the issue into words, but this is what I mean:
http://www.mcgamer.net/round/uhc/?round=436
Although acr9mas and I both survived until the end of Deathmatch and the server closed, another game seems to have 'continued the round'.

Steps to Reproduce
1.Play a UHC Worlds Game on the EU servers
2.Have multiple players survive until the end of deathmatch
3.Play another game on the same server as before
4.Check the round that you just played on the website, and you should see that the games have merged

Miscellaneous information 
The previous link that shows the evidence:
http://www.mcgamer.net/round/uhc/?round=436

I hope this issue is resolved soon, and I'll do my best to report any more bugs that I find :)

**Comment by subv3rsion** [comment]
@Gjosiah Could you look into this? It sounds like there's something not resetting stored player data at the end of games, which I'm not sure if this is possible or not. This should only happen with servers that run through a second (or more) round(s) of UHC.

**Comment by Gjosiah** [comment]
This issue has been addressed and should be fixed as of our next plugin update.
