### ISSUE TITLE
UHC Worlds Pregame Loss

### ISSUE THREAD

**Issue by NerdyNoodles** [MCGamerNetwork/Issues#631]
Environment
On the EU Beta of UHC Worlds

The Issue
If you leave in pregame it counts as a loss.

Steps to Reproduce
1.Leave a game after voting has ended and world generation has began, but before the player scatter

Miscellaneous information 
Screenshot of this: http://gyazo.com/5c63cb0c49016ebf379d68cdd7d35977

Once again, I hope this helps you out with tracking bugs :)

**Comment by forairan** [comment]
This isn't a bug, but rather intended behavior; SG behaves the same way.

Thanks for the report regardless!
