### ISSUE TITLE
UHC Worlds - Deathmatch/Timer is Glitched

### ISSUE THREAD

**Issue by Ceroria** [MCGamerNetwork/Issues#633]
US Beta of UHC Worlds

I've only played one round of UHC Worlds, so I may not have the most accurate description, but about 15 minutes into the 45 minute game, it'll start the Deathmatch timer and teleport us into a bordered off chunk of water. 

Nobody in the game seemed to have found iron.

**Comment by forairan** [comment]
Did you /reportbug and get a state dump ID number when this issue happened? If not, don't do it now, as the information is only helpful during the game having issues,  but it'd be helpful for us to have this information in the future.

**Comment by arsenalfcgunners** [comment]
It's working correctly.  It starts when a 4 players are left, or when the timer runs out.  It is not entirely based on the timer.

**Comment by Ceroria** [comment]
Okay, my bad.  Was in a rush to complete the report as I had to go somewhere and forget to get the stamp.
