### ISSUE TITLE
SG/UHC Worlds Spectator Glitch [May occur in other gamemodes]

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#634]
If you do /watch uhc to spectate a game of uhc you will join in survival mode.  You have to do /spec to get into the 1.8 spectate mode.

**Comment by forairan** [comment]
Did you /reportbug and get a state dump ID number when this issue happened? If not, don't do it now, as the information is only helpful during the game having issues, but it'd be helpful for us to have this information in the future.

**Comment by arsenalfcgunners** [comment]
This is happening in SG. Sorry I did /reportbug but I wasn't sure what to do with the number.  In the game of SG where this was occurring the id was 217.  As a spec I could see several players who were specs running around the game as if they were players.  I don't think the ingame players could see them though.  In /list they were considered specs.

**Comment by forairan** [comment]
For future reference, just put the number in the body of your report, i.e. "/reportbug number: #122323", as the instructions say to do.

You mentioned in your last comment that this was occurring on a game of SG - I assume you mean UHC?

**Comment by arsenalfcgunners** [comment]
It happens on both.  Just realized that.

**Comment by arsenalfcgunners** [comment]
UPDATE: In seems this occurs after you die in UHC Worlds and SG, or like I said when you join with /watch.  Typing /spec fixes this issues.  Not sure if it occurs in other gamemodes.

**Comment by subv3rsion** [comment]
I can confirm (per #636) there appears to be some wonkiness with gamemasters, where I _believe_ before a recent update, you would be able to fly around and be a regular "spectator" (1.8 spectator mode) while in the lobby.
In addition, spectators after joining with /watch appear to be visible, but only when joining with /watch. I'm still looking into this, and hopefully someone will have a fix for this soon.

**Comment by Gjosiah** [comment]
This issue has been resolved, and the changes should be live within a few hours.
