### ISSUE TITLE
Color Zone: Spectators do not have fly

### ISSUE THREAD

**Issue by sontate72** [MCGamerNetwork/Issues#637]
-Environment-
Color Zone, 3:15 EST 5/2/15, US
-Issue-
Watching a Color Zone game connects you to the server as a spectator. You spawn in mid-air, but you cannot fly. You then fall to the arena. The plugin stops you from landing on the ground to prevent spec-blocking, but since you cannot fly, you are stuck in place, constantly being teleported half a block up.
The game warns you to stop, and then you are kicked. "Flying is not enabled on this server."
-Steps to Reproduce-
1. Spectate a CZ game.
2. Observe.
-Misc.-
Here's a video demonstrating the problem. I am doing anything I can to fly or move.
https://youtu.be/fsCFBa_ERzc

**Comment by forairan** [comment]
Did you `/reportbug` and get a state dump ID number when this issue happened? If not, don't do it now, as the information is only helpful during the game having issues, but it'd be helpful for us to have this information in the future.

**Comment by arsenalfcgunners** [comment]
Probably is related to #634.
