### ISSUE TITLE
Glitching Armor into a new Sg round.

### ISSUE THREAD

**Issue by Mauro2424** [MCGamerNetwork/Issues#641]
A person won on a sg map wearing full iron armor.
Joined another lobby to play a new sg game - With Full Iron.
Pregame - He still had the full iron armor.

Armor was usable and it dropped when the person died.
Only armor was glitched.

Image: http://i.imgur.com/B0LM7fM.png
Video: https://www.youtube.com/watch?v=WpwWufWEhSk

**Comment by forairan** [comment]
Should be fixed when the plugin is next deployed. Thanks for the report!
