### ISSUE TITLE
The commands /achievement and /achievements don't work

### ISSUE THREAD

**Issue by xHigh** [MCGamerNetwork/Issues#643]
1. Environment
This section should provide all information regarding the environment where the issue occured, location (US/EU/CA/AU), server ID, gametype, time of when the issue happened, etc.
 All servers (Everywhere)

2. The issue
The commands /achievement and /achievements don't work

3. Steps to reproduce
Type /achievement  or /achievements in chat

4. Miscellaneous information
http://gyazo.com/4a421e46248566f9467dbc02474aa4c9

 
---------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 973).

**Comment by forairan** [comment]
Intended behavior - those commands are developer commands right now, as we haven't implemented our new achievement system yet.
