### ISSUE TITLE
UHC Worlds Lobby Fly Glitch

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#644]
Issue #: 1352

Donors get kicked in lobby when they try to fly with /fly.  It says they were kicked for flying.

**Comment by forairan** [comment]
I'm unable to replicate this. Does it only affect donors, or does it affect staff (i.e. mods) as well?

**Comment by arsenalfcgunners** [comment]
Devin it has to happen while the world is being generated I believe.  Just did some more experimenting.  It seems it occurs when a player has done /fly before the generation starts and are flying when it changes from normal lobby to generating the world.

**Comment by YourAverageTiger** [comment]
I tried all that was mention @arsenalfcgunners and it failed to duplicate. @forairan please close?

**Comment by arsenalfcgunners** [comment]
Closing this issue, as I have tested it and can no longer reproduce it.
