### ISSUE TITLE
Tab-complete does not react to player name filters

### ISSUE THREAD

**Issue by sontate72** [MCGamerNetwork/Issues#645]
Typing a name in chat and pressing tab will not complete the name, but rather cycle through every player in the game/hub/lobby as if nothing had been typed.

   If I wanted to say:
hi X_x_Candyland_x_X
   Then I would type:
hi X_x
  Then press TAB. However, this goes to the first name in the lobby, so my message would say:
hi Astronautical
   So I have to type out the whole name without using TAB to auto-complete the name.

**Comment by arsenalfcgunners** [comment]
I have noticed this too.

**Comment by forairan** [comment]
This doesn't seem to be an issue anymore.
