### ISSUE TITLE
Pre-Game crashes

### ISSUE THREAD

**Issue by sontate72** [MCGamerNetwork/Issues#649]
Although I don't have a video for this, it is the same glitch as the old one on Alaskan Village. Here is a list of maps that I have seen glitch out, stopping at 29 or 30 seconds and allowing players to run around and break blocks:
-Alaskan Village
-La Bronchaterie
-48-man games with more than 24 players
-120 man games

**Comment by forairan** [comment]
Should no longer be an issue. If this is still an issue, please open another issue with updated information.
Thanks for the report!
