### ISSUE TITLE
XKMB not equally spaced?

### ISSUE THREAD

**Issue by ChildishG** [MCGamerNetwork/Issues#651]
Try to separate your issue report into four different sections, if possible:
1. Environment
This was found to be a bug that worked on one server, but not on the other. (The XKMB are not equally spaced on EU)

2. The issue
Recently, on the US servers, the XKMB were spaced out, as to make moderation easier(seen here http://imgur.com/wUzu05B), but on EU, they are currently not. Though this is not too much of an issue, it can still be corrected and make moderation easier.

3. Steps to reproduce
Log onto US and EU and type in chat. 

4. Miscellaneous information
![wuzu05b](https://cloud.githubusercontent.com/assets/12483830/7670681/87649614-fc7c-11e4-860d-9f58b55bbbfb.png)
![sreorea](https://cloud.githubusercontent.com/assets/12483830/7670684/95622470-fc7c-11e4-8453-407e6cfc51d1.png)

.
----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 2558).

**Comment by Rustywolf** [comment]
This change was not intentional and has been fixed. The fix will be rolled out upon the next update.
