### ISSUE TITLE
No 24 Player SG Servers

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#655]
1. Environment
US SG Mini Hub

2. The issue
No 24 player servers.
http://i.imgur.com/Ge6cyv8.png
http://i.imgur.com/JmpcH6u.png  

3. Steps to reproduce
Not any real way to make it happen, but this is usually a problem during off-peak hours.

A state dump was generated and submitted successfully (ID number 3174).

**Comment by subv3rsion** [comment]
This will be resolved in the next plugin push. Thanks for the report!
