### ISSUE TITLE
[Hub] /friend has a friend limit of 0

### ISSUE THREAD

**Issue by sontate72** [MCGamerNetwork/Issues#656]
Environment
US, hub. Works in any game hub as well.

The issue
It appears that members have a max limit of 0 for friends. This stops you from sending any requests and therefore adding any friends to your list. I'm not sure if upgrading to a higher rank changes this.

Steps to reproduce
1. Type /friend add [player] Press enter.

Miscellaneous information
http://youtu.be/7VreZn-Iq1c

Dump ID: #4404
(Please note that I closed Minecraft before I rendered the video, then I reopened it to get the dump ID. I'm not sure if this matters.)

**Comment by subv3rsion** [comment]
Thanks for the report! This should be resolved as of tonight's plugin push.
