### ISSUE TITLE
Users can see their own Disguise Skin

### ISSUE THREAD

**Issue by TheDiamondzGaming** [MCGamerNetwork/Issues#658]
1.Environment

This issue has occurred in all regions, by many users, in the Survival Games gametype. It mainly occurs in the map itself, and not the lobby.

2.The issue

Users cannot see their own skin, but instead, see their disguised skin.

3.Steps to reproduce

Don't exactly know if this will work, but disable the function for players to see their disguised skin?

4.Miscellaneous information
Screenshots are provided below:

http://i.imgur.com/2kufEmn.png - When disguised in the lobby, I am able to see my own skin.

http://i.imgur.com/jSeoF6m.png - When ingame, I am not able to see my own skin, and instead, the disguised skin.

**Comment by forairan** [comment]
Intended behavior - this is a feature, not a bug.
