### ISSUE TITLE
Stats Reset Bug

### ISSUE THREAD

**Issue by SkillsAtPvP** [MCGamerNetwork/Issues#661]
I have an issue with the stats reset. I used a daily stats reset that only resets the daily stats, but instead it reset my overall stats. I was told by a mod that this wasn't suppose to happen and now I'm here to see if I can get my stats back. I worked hard to get those stats and I really don't want to lose it over a bug. Can you please help me with my situation? My IGN is SkillsAtPvP.

**Comment by forairan** [comment]
You'll need to contact support@mcgamer.net for help getting your stats restored.
