### ISSUE TITLE
/friend list doesn't work.

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#663]
I reported this earlier and my report was closed.  Still doesn't work.  Maybe the fix wasn't pushed?  Just wanted to make sure it is cause it's been a few weeks.

**Comment by forairan** [comment]
Is there any specific error you get when doing this command, or does it just not produce any output?

**Comment by arsenalfcgunners** [comment]
no output. /friends /friend list 1 /friend list all don't work

**Comment by forairan** [comment]
See #695.
