### ISSUE TITLE
Tab list - White disguised names on undisguised players

### ISSUE THREAD

**Issue by JoelColby** [MCGamerNetwork/Issues#665]
When disguising in any hub lobby (it can be for any game hub or a main hub) you are given a disguised name and skin as intended. However, the disguised username will appear white on the tab list.

When undisguising your name will remain the white disguised name, though your skin will return to normal.

To replicate this:
1. Enter any hub lobby.
2. Disguise and then immediately undiguise.
3. Check the tab list. Your name will be a white disguised name -- this is how it appears to all other users.

NOTE: Your name will appear normally when performing the /list command.

**Comment by JoelColby** [comment]
Fixed in the latest Community Update.

**Comment by subv3rsion** [comment]
Joel y u lie
