### ISSUE TITLE
Zed Chase Required Players Issue

### ISSUE THREAD

**Issue by iVelocityGaming** [MCGamerNetwork/Issues#666]
1. Environment
Zed Chase, US.

2. The issue
On the /v message, it states that 7 players are required for the game to commence, though the required number is actually 10 players for the game to start according to the plugin.

3. Steps to reproduce
Not necessary. 

4. Miscellaneous information
http://i.imgur.com/6oa9eoV.jpg

**Comment by arsenalfcgunners** [comment]
For what it's worth the exact same thing is a problem in UHC Worlds.

**Comment by forairan** [comment]
This will be fixed as of the next deployment cycle. Thanks for the report!
