### ISSUE TITLE
Disguising doesn't change skin client side

### ISSUE THREAD

**Issue by Crafter409** [MCGamerNetwork/Issues#669]
On Survival Games (US), if a player disguises, then their skin will change server side, but will not do so for the client side. To the client their original skin remains the same. This occurs in both 1.7 and 1.8.

**Comment by forairan** [comment]
I'm almost positive this is a Minecraft thing, as it seems to work sometimes, but not others. We'll look into it, but I can't guarantee a fix.

**Comment by YourAverageTiger** [comment]
From what I do know/noticed, happens to 1.7 only.

**Comment by CAmadeusA** [comment]
As this bug is over 6 Months old and has been resolved, this issue has been closed.
