### ISSUE TITLE
Server Lag on MCGamer

### ISSUE THREAD

**Issue by MikelFilko** [MCGamerNetwork/Issues#671]
Location: US MCGamer (whole server)
Time:  21/6/15 9-11pm (+8GMT)

Details: Whenever I join MCGamer, my ping will fluctuate between a 1 bar to a 4 bar and I cannot seem to get a stable connection to MCGamer (my average ping should be 180). I have tried joining other servers and they all work perfectly fine, it's only MCGamer which gives me the inconsistent ping. This has therefore caused me to die multiple times in MCSG when playing in a game. 
I did check the amount of packets I received and sent, on MCGamer, I receive about 70-400 packets and sent out about 70 on average. However on other servers, I usually receive about 70-100 which is considered stable unlike MCGamer. I haven't had this experience before and I am thinking it has something to do with the new Community/Summer Update.

Thank you for reading,
Mikel

**Comment by forairan** [comment]
This may have been routing issues between your ISP (internet service provider) and our datacenter. The Internet operates on a network of routes; routes go down all the time for various reasons, and this may cause your connection to our server to take a less desirable route across the world. There's not much we can do in that case, unfortunately.
