### ISSUE TITLE
Issue with anti cheat!

### ISSUE THREAD

**Issue by Crotexx** [MCGamerNetwork/Issues#674]
So,when i log in in mcgamer i have a problem that it keeps banning me from server...mods that i use are Better sprinting mod and Optifine...but i don t think that that is the problem because my friend has same mods that i do but he doesn t get banned any time...can you pls fix that...my IGN:Crotexx

**Comment by Chadthedj** [comment]
You are being temp banned due to you using the BSM mod. Please uninstall it before playing on our servers. Thanks!
