### ISSUE TITLE
Deadly Descent, Multiple Users in 1st, 2nd, and 3rd Place

### ISSUE THREAD

**Issue by ButterScottch** [MCGamerNetwork/Issues#675]
*Environment*
Deadly Descent, All Regions (Particularly US), All Games. 
State Dump ID: 8851

*The issue*
There is always one person that has 1st, 2nd, and 3rd place at the end of the game. The true winner is on the list.

*Steps to reproduce*
Play a game of Deadly Descent.

Images:
http://imgur.com/a/m7Ta7
http://i.imgur.com/cJeu8ue.jpg

**Comment by arsenalfcgunners** [comment]
@forairan I think this is fixed? http://www.mcgamer.net/threads/game-build-356-22-november-2015.233001/#post-2301654
