### ISSUE TITLE
SG Spectator Glitch.

### ISSUE THREAD

**Issue by ChildishG** [MCGamerNetwork/Issues#676]
Environment

US, SG game.

The issue: Spectators can interact with the environment eg: can put out fires, open doors.

Steps to reproduce

Go to zone 85 into the helicopter, run in front of the doors as a spectator.

Miscellaneous information

https://www.youtube.com/watch?v=b0ldpFHsyE8&feature=youtu.be

**Comment by forairan** [comment]
This should be fixed in the next deployment cycle.
Thanks for the report!
