### ISSUE TITLE
Mobs spawning on maps?

### ISSUE THREAD

**Issue by KaosInspired** [MCGamerNetwork/Issues#677]
This happened on US @ around 1:20 PM on Monday the 22nd of June, Ill post a screenshot of what happened.

Basically mobs are spawning on the map Survival Games 3 and I died to 4 creepers ;-;
http://gyazo.com/ca90f58cad080ed1bee4f29fe1603023

^ Above is the before mentioned issue hopefully this will be fixed thanks <3

**Comment by arsenalfcgunners** [comment]
Almost 100% sure this has been fixed. @forairan please close.

**Comment by AlpakaWhacker** [comment]
Has been fixed. Closed.
