### ISSUE TITLE
1.7.10 Unlimited Enchantments in SG

### ISSUE THREAD

**Issue by Hxdrah** [MCGamerNetwork/Issues#678]
Environment
In SG on all regions (on 1.7.10) at any time attempted.

The Issue
When you enchant in SG on 1.7.10, it does not take your XP levels away. You can continuously enchant to get all your weapons and armor enchanted with one level.

Steps to reproduce
To reproduce, simply play SG on 1.7.10, get one or more bar(s) of XP and then enchant.

Miscellaneous information
This has been brought to my attention by a forum user that has attempted to announce the bug to the community. The thread can be viewed here: http://www.mcgamer.net/threads/want-to-become-full-enchanted-in-game.192713/

**Comment by Gjosiah** [comment]
This issue has been fixed, and the fix should take effect within 24 hours, as of the next plugin push.
