### ISSUE TITLE
I can't do /friends.

### ISSUE THREAD

**Issue by Inspiired** [MCGamerNetwork/Issues#679]
Hello, when I log onto MCGamer, US,AU Or EU. I do /friends and nothing comes up. I also try to do /friend accept and nothing actually happens. It works fine for everyone else... I could do it before and now I can't. help me?

**Comment by sontate72** [comment]
Does /friend work?

**Comment by Inspiired** [comment]
Yes it does.

**Comment by forairan** [comment]
See #695.
