### ISSUE TITLE
hit glitch

### ISSUE THREAD

**Issue by fukwitme** [MCGamerNetwork/Issues#683]
if you blockhit your sword will often get stuck in block (it appears normal to you but this way to other players) and you will not be able to hit anyone until you right click your sword

**Comment by forairan** [comment]
We'll need some more information to properly investigate this issue.

Is the issue occurring on 1.7 or 1.8? What region was this occurring on, and in what gametype?

**Comment by forairan** [comment]
Looks like a duplicate of #432.
