### ISSUE TITLE
Infinite Enchanting Bug

### ISSUE THREAD

**Issue by Xeride** [MCGamerNetwork/Issues#685]
Title:
Infinite enchanting, can enchant items without levels being used up.

Example:
Picture Attached

Description:

SG: Adrenaline, MCSG, EU, EU1957, 11:03 AM CDT

The issue:

Was sponsored some enchant bottles. Used them and got one level. I enchanted my sword (no lapis needed because 1.7) and I got sharpness 1, but my level wasn't used. So I tried it with my bow and it happened again. No timing or anything, just enchanting as you would do normally, but the level wasn't used up.

Steps to reproduce:

Get a level, and enchant multiple items. 

Miscellaneous information:
Bug might be caused because of the server being 1.7 and 1.8, just a guess.

![screenshot_1](https://cloud.githubusercontent.com/assets/13085548/8395969/3c8a758c-1d88-11e5-8610-efdb383126e7.png)

**Comment by Gjosiah** [comment]
This issue has been fixed, and the fix should take effect within 24 hours, as of the next plugin push.
