### ISSUE TITLE
MCSG hubs

### ISSUE THREAD

**Issue by ArcticForce** [MCGamerNetwork/Issues#686]
BEFORE: 
![2015-06-28_15 24 46](https://cloud.githubusercontent.com/assets/13089844/8397929/a782cdb8-1daa-11e5-87e1-fba53bd3fe27.png)

After
![2015-06-28_15 24 50](https://cloud.githubusercontent.com/assets/13089844/8397930/b11136bc-1daa-11e5-8f28-11e2a9687c28.png)

**Comment by ArcticForce** [comment]
This was after i clicked the ender pearl

**Comment by JLioner** [comment]
^^^^^^^^^^
I experience the same issue.
Here is a recording of it:
Video: https://www.youtube.com/watch?v=yrGeokUvohA

**Comment by forairan** [comment]
Should be fixed. Thanks for the report!
