### ISSUE TITLE
ZedChase King of the Hill [team]

### ISSUE THREAD

**Issue by vanicle** [MCGamerNetwork/Issues#687]
Gametype: ZedChase

The Issue: When playing King of the Hill [team] on ZedChase, the game does not end until one player remains. Therefore, when an entire team wins, you have to wait the length of the game or the rest of the teammates have to commit suicide for the game to end. http://i.imgur.com/V2wqd2k.jpg

Steps to reproduce: Play a game of Zed Chase, King of the Hill [team]

Misc: none

**Comment by forairan** [comment]
Judging based on the sidebar, it looks like KOTH Solo was selected in this case. What you're seeing is the bug where team colors would be assigned in a solo game, which will be fixed as of the next deployment. I'll also add some clarification on which game type was chosen.

Thanks for the report!
