### ISSUE TITLE
ZedChase Lobby

### ISSUE THREAD

**Issue by vanicle** [MCGamerNetwork/Issues#688]
Gametype: ZedChase

The issue: Game information says it requires 10 people to play, however, when you vote for the lobby it states you need 7 players to play. http://i.imgur.com/Xx5N4KQ.png

Steps to reproduce: Go to a ZedChase lobby and do /v

Misc: None

**Comment by forairan** [comment]
This issue will be fixed in the next deployment cycle. Thanks for the report!
