### ISSUE TITLE
BattleGrounds: Wither visible as Spectator (Staff)

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#690]
-= *Environment* =-

BattleGrounds on the EU region, but most likely across all regions.

-= *The issue* =-

The wither that is causing the Battlegrounds health bar at the top is visible in-game as a spectator. When a staff member is spectating in Gamemaster.

-= *Steps to reproduce* =-

Go in GM and spectate a player around to see the wither appear.

-= *Miscellaneous information* =-

Advised by CAmadeusA to report this as a bug.

Video: https://www.youtube.com/watch?v=flg6jgWXVhI

**Comment by forairan** [comment]
Nothing we can do about this; as far as I'm aware, it's a 1.8 limitation.
Thanks for the report regardless!
