### ISSUE TITLE
EU Survival Games server 'hacked'?

### ISSUE THREAD

**Issue by rf2minecraft** [MCGamerNetwork/Issues#691]
This issue is on the EU network on the server SG 2929. This has been seen a couple of times before but has been noticed again on the 29th of June 2015 at 18:45PM GMT+1.

The issue is when joining Survival Games through methods such as /join sg, I have come across this one server which holds 120 players and where it says the region on the scoreboard at the side and also in the chat when you join, it doesn't say EU but rather it says HAX. This has been noticed a few times before but I never really took any notice of it, thinking it was just a glitch which would be fixed with a server restart, but this is apparently not so.

To reproduce the issue I am facing, you will have to connect to the EU network & join the survival games (seems to be survival games all the time...) server 2929 and look at the message you get once you connect where it says "Connecting you to <region> - <number> (gametype)" and also the 'region' shown on the scoreboard. 

If needed, here is a screenshot of what I am seeing: http://imgur.com/wt4TNzI

Bug Report Dump Code: #10366

**Comment by forairan** [comment]
Fixed. Thanks for the report!
