### ISSUE TITLE
Friends list/requests

### ISSUE THREAD

**Issue by AGFire2013** [MCGamerNetwork/Issues#695]
/friends list not working for certain people
Adding friends also not working for some

**Comment by JLioner** [comment]
^^^^^^^^^^^^^^
Only happens to some people.
The commands simply don't perform any action (see video).
Video: https://www.youtube.com/watch?v=zVzM9cXUX1s

**Comment by arsenalfcgunners** [comment]
Still not working for me as well.

**Comment by forairan** [comment]
Requests fixed, list is still being looked into.

**Comment by forairan** [comment]
Should be fixed as of [Proxy build 24](http://www.mcgamer.net/threads/proxy-build-24-5-august-2015.210164/). Thanks for the report!
