### ISSUE TITLE
Compatibility 1.7/1.8

### ISSUE THREAD

**Issue by GoldenWave98** [MCGamerNetwork/Issues#696]
Environment: SG, maps that use 1.8 blocks.

The issue: Players using 1.7 can't se 1.8 blocks, and the server acts like they're not there. For example today i was playing with one of my friends, him using 1.7 and me using 1.8: The map was holiday resort 2. I was standing on a 1.8 block, which he couldn't see, nor interact with, and i got kicked for flying, while i was just standing on a block that the 1.7 "part" of the server didn't recognize. 

Steps to reproduce: Just enter the server on both clients on a map that takes advantage of 1.8 blocks and you'll immediately recognize the issue

**Comment by forairan** [comment]
Unfortunately, this is a limitation introduced when 1.7 support returned: servers running a 1.7 core internally (hub, SG, BG) don't recognize that 1.8 blocks exist, and so 1.8 clients have erratic behavior when interacting with 1.8 blocks, and 1.7 clients don't see the blocks at all. There's nothing we can do about this, aside from updating affected maps to remove 1.8 blocks.
