### ISSUE TITLE
Hub-Player-Invisibility-Glitch 

### ISSUE THREAD

**Issue by ghost** [MCGamerNetwork/Issues#697]
===========================
The issue & Steps to reproduce
===========================
1. Be in a Hub and make players invisible, using the clock.
--> Names disappear from the tab-list and ingame (so far so good.)
2. Make them visible again, using the clock.
--> Names in the tab list are white (without the rank-color) and the players are not visible ingame.
--> All players that join the hub after this action will be visible and their rank will appear in the tab list.

Video: https://www.youtube.com/watch?v=NzGsTflc6-I

**Comment by arsenalfcgunners** [comment]
Devin this seems to be working correctly when I just tested it on hub.  Maybe it doesn't always occur.

**Comment by CAmadeusA** [comment]
As this issue is over 6 months old and has been resolved previously, this issue is now closed.
