### ISSUE TITLE
Spectating in BattleGrounds?!

### ISSUE THREAD

**Issue by iPowerHD** [MCGamerNetwork/Issues#700]
- Location: US
- Server ID: 256
- GameType: BattleGrounds
- Time: 5:00 PM EST

 ~

Rare bug were when you join a random BG server, you have a spectator glitch where your a spectator and cant hit people but fly. (Found by typing /debug)

~

None

~

Video:

https://www.youtube.com/watch?v=Whnk5HVHOdo&feature=youtu.be
----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 12519).

**Comment by forairan** [comment]
I can't reproduce this issue, and unfortunately the video has been taken down at this point.
If this is still a bug, feel free to open another report.
