### ISSUE TITLE
OptiFine Zoom Issues (Community-reported issue)

### ISSUE THREAD

**Issue by Hxdrah** [MCGamerNetwork/Issues#703]
Environment:
MCGamer as a server, happened today.

The issue:
A group of community members told me that their zoom isn't working for OptiFine on MCGamer, but it works on every other server.

Steps to reproduce:
Attempting to zoom on MCGamer with OptiFine.

Miscellaneous information:
I don't believe it is happening for everyone, but there were a few people that did bring it up to me.

**Comment by forairan** [comment]
We don't provide support for issues with client modifications, sorry.
