### ISSUE TITLE
Unlimited Enchantment Glitch

### ISSUE THREAD

**Issue by vanicle** [MCGamerNetwork/Issues#705]
Gametype: MCSG, tested on dev network

Issue: If you have one level on 1.7, you are able to enchant all your gear without losing levels. If you have two levels on 1.8, you are able to enchant all your gear without losing levels.

Steps to reproduce: play MCSG, gain one level, enchant.

Misc: This is verifying that this bug report, as of 07/16/2015, is still an issue https://github.com/MCGamerNetwork/Issues/issues/685

**Comment by CAmadeusA** [comment]
This issue has been resolved in a recent update, closed.
