### ISSUE TITLE
BattleGrounds: Fire Damage after Dying

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#706]
-= *Environment* =-

Network wide. On the BattleGrounds game type. 

-= *The issue* =-

If players die while being on fire, they will remain taking fire damage upon respawning and going into the next fight.

-= *Steps to reproduce* =-

Die while being on fire, and go back into the arena.

-= *Miscellaneous information* =-

Video evidence: https://www.youtube.com/watch?v=7EgxpJaH-_o

**Comment by forairan** [comment]
Will be fixed the next time the plugin is deployed. Thanks for the report!
