### ISSUE TITLE
Turkish Swear Filter Bug

### ISSUE THREAD

**Issue by Alkan1** [MCGamerNetwork/Issues#709]
-I saw you made a good swear filter for turkish. But there is a big bug with it.

-This Bug will happen all the hubs that have turkish swear filter.

- Here is the issue with the turkish swear filter: As you know you blocked words like "anan", or "amına" etc. But...You forgot that: We use these letters in lots of different words like "Bayramın" etc. and your swear filter blocks those too. I mean, We cant write some turkish words in chat which isnt swear. and it is quite annoying as you can imagine. Lots of Turkish players are suffering from this. And I wanted you to know this bug.

-What you can do for fixing it?: Maybe you can set the filter for using "anan" etc. alone. I don't know....

-I will send you screenshots here so you can understand clearly what I'm trying to explain.

![screenshot_8](https://cloud.githubusercontent.com/assets/13395874/8762717/f4a92972-2d89-11e5-8f89-4c009fae49e8.png)
 
/\ Here I tried to write "sanan" which isnt a swear...But I cannot write it.

![screenshot_7](https://cloud.githubusercontent.com/assets/13395874/8762750/8ce7579a-2d8a-11e5-8dd1-b1aec8e62f6e.png)

/\ Here I tried to write "Bayramın" which isnt a swear..But I cannot write it.

As you can imagine, Turkish people (me too) are really annoyed of this bug. If you can fix this we can communicate clearly. Thanks for reading this <3

Love,
KaanGurbuz

**Comment by forairan** [comment]
This will be fixed when we deploy the plugin next.
Thanks for the report!
