### ISSUE TITLE
Connection lost bug

### ISSUE THREAD

**Issue by Sedrazo** [MCGamerNetwork/Issues#711]
GameType: In the hubs.

Issue: A connection lost issue.

Steps: Whenever you are in the hub, you use the netherstar to go to a different hub, it disconnects you from the server and it gives you a connection lost error. Here is what it gives me: http://gyazo.com/b76e045680f8cccce3223bb3c3c5206a

That's basically the issue I was having.

**Comment by forairan** [comment]
This issue should be fixed. If you are still experiencing issues, please re-open another issue report.
