### ISSUE TITLE
[Staff] /locate command broken

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#714]
-= *Environment* =-

Network wide, on any game type and in the hub.

-= *The issue* =-

Upon running the /locate <player> command, nothing shows up in chat.

-= *Steps to reproduce* =-

Run the /locate <player> command anywhere on the Network.

-= *Miscellaneous information* =-

N/A.

**Comment by forairan** [comment]
Should be fixed next time the plugin is deployed.
Thanks for the report!
