### ISSUE TITLE
Battlegrounds Bug - Reloading Inventory

### ISSUE THREAD

**Issue by JDusk** [MCGamerNetwork/Issues#716]
Battlegrounds (Where Bug Happened) All of them

Ugh, so I can't get a video of the battlegrounds glitch because my processing is taking forever right now, but basically how the glitch works is that you have to break a block while standing on it. When breaking the block, anything in your inventory such as the durability of your bow, rod, sword, armor and arrows, even the porkchops gets refilled to the original inventory you obtain when spawning in a battlegrounds game. If you have gapples in your inventory that you haven't ate and you break the block whiling standing on it, your gapples will be removed.

To recreate this; just go in a BG game and shoot some arrows or break some of your armor, etc. then stand on any block and just break it (except grass,leaves, etc.)

**Comment by Nephilim04** [comment]
Was reported to me as well, managed to replicate the bug myself. Can confirm that this doesn't work on leave, wooden blocks are the easiest way to do this.

https://www.youtube.com/watch?v=NgoA7syaKJQ

https://www.youtube.com/watch?v=ETsyp3Ul078

**Comment by forairan** [comment]
Will be fixed next time the plugin is deployed. Thanks for the report!
