### ISSUE TITLE
 Thorndon Valley - Bug Report - Deathmatch Lightning

### ISSUE THREAD

**Issue by NagolGames** [MCGamerNetwork/Issues#717]
Whilst playing a game of SG, Skill and I went to Deathmatch and this began happening:

Evidence: http://youtu.be/8mf3FDPmQiM
Game Information: http://www.mcgamer.net/round/mcsg/?round=3054093

NagolGames

**Comment by AlpakaWhacker** [comment]
Issue addressed and Fixed
