### ISSUE TITLE
Forums Sign-up Error

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#718]
**Environment**

MCGamer Website.

**The issue**

Recently I have received multiple reports from users that they are unable to sign-up their account as they receive the following error: http://prntscr.com/7vec5p. I needed to add their accounts manually through the admin panel.

**Steps to reproduce**

Not sure what exactly is causing this issue, but it has been occurring more frequently. Perhaps try to signj-up a few accounts and see if you encounter the issue.

**Miscellaneous information**

Screenshot provided above. I added 3 accounts manually so far due to this error/bug.

**Comment by forairan** [comment]
If the user tries to sign up multiple times, does it eventually work? Or do they get this error every time they try to sign up?

**Comment by Nephilim04** [comment]
￼<18:21:54> "Saski": My friend says hes tried again and again and it still comes up with an error
￼<18:22:28> "Neph": How many times did he approximately try?
￼<18:23:56> "Saski": He said he tried twice and couldnt type in his info again after

@forairan

**Comment by forairan** [comment]
This issue appears to be resolved. If there are further issues, please open a new issue report.
