### ISSUE TITLE
Friends plugin, requests command not working

### ISSUE THREAD

**Issue by LiveInInfamy** [MCGamerNetwork/Issues#719]
Try to separate your issue report into four different sections, if possible:
1. Environment: All servers in all regions. 

2. The issue: When /friends requests is typed in chat, nothing happens. I currently have 3 pending requests, and I can't access them. 

3. Steps to reproduce: Type /friend requests in any server. 
----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 14648).

**Comment by forairan** [comment]
Requests have been fixed - see #695 for more information.
