### ISSUE TITLE
Sponsoring Is Glitched

### ISSUE THREAD

**Issue by levimcgrew** [MCGamerNetwork/Issues#723]
US 520
Sponsoring is glitched. When you do /sponsor (name) it pops up the menu, and it disappears normally when you click on an item. It gives no recognition of the item being sent and it doesn't take any points, and lastly they don't receive the item.
I don't have any screenshots, sorry. Someone was just complaining about it and I tried for myself multiple times and the exact problems they described happened to me.
----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 15124).

**Comment by Jodemoted** [comment]
Environment:
This glitch happens Network Wide

The issue:
When sponsoring a user, the menu appears, however the actual request and item does not seem to go through, meaning the user does not actually receive the item.

**Comment by Rustywolf** [comment]
Fix is now live, thank you for the report.
