### ISSUE TITLE
Battlegrounds Leaderboard bug

### ISSUE THREAD

**Issue by ghost** [MCGamerNetwork/Issues#724]
The Battlegrounds leaderboards do not show the amount of kills in some cases, or they show a “§” instead.
Screenshots: http://i.imgur.com/An6BCtF.png,  http://i.imgur.com/juF6zAt.png, http://i.imgur.com/tsR9eOR.png

**Comment by forairan** [comment]
More information is required to diagnose this issue.
Were you on 1.7.x or 1.8.x when this issue occurred?

**Comment by CAmadeusA** [comment]
As this issue is over 6 months old and has been resolved previously, this issue is now closed.
