### ISSUE TITLE
Not able to eat raw potatoes

### ISSUE THREAD

**Issue by vladthegreat100** [MCGamerNetwork/Issues#726]
Environment: US, SG
Issue: I found a raw potato, tried eating it but the eating cycle restarted making me not able to eat it.
Steps: Find a raw potato on the ground or in a chest, take it out and put it in your inventory, attempt to eat it.

**Comment by CAmadeusA** [comment]
As this issue is over 6 months old and has been resolved previously, this issue is now closed.
