### ISSUE TITLE
Item Frame Glitch

### ISSUE THREAD

**Issue by Cqthy** [MCGamerNetwork/Issues#728]
1) Environment 
Occurred Location: US    ID #: #16105, Time: 3:26pm Date: 7/31/15 Issue:

2. The issue
I was just walking into a house and I saw  Item France All Over The Floor and I was picking them up 
3. Steps to reproduce
If applicable, this section should provide a detailed list of steps needed to reproduce the issue.

4. Miscellaneous information http://gyazo.com/31c45c2c0dd8d3cce89d75979c9cb725

Please remove the above text before submitting your issue report, but DO NOT REMOVE ANYTHING BELOW THIS LINE! The information below this line will help us find the issue faster.
----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 16099).

**Comment by arsenalfcgunners** [comment]
This happens on a lot of maps.

**Comment by YourAverageTiger** [comment]
This happened with the 1.7 - 1.8 update.

**Comment by CAmadeusA** [comment]
As this issue is over 6 months old and has been resolved previously, this issue is now closed.
