### ISSUE TITLE
Tab-list doesn't work correctly.

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#735]
https://github.com/MCGamerNetwork/Issues/issues/645 this is still an issue.  If you are in a game of sg for example and you do /stats and type the first few letters of their name and then press tab it will go to the first name in the tab list instead of to the name you want.  If that makes sense.

**Comment by forairan** [comment]
Are you on 1.7 or 1.8 when this issue happens?

**Comment by arsenalfcgunners** [comment]
Confirmed this with both.
