### ISSUE TITLE
/party list won't work

### ISSUE THREAD

**Issue by YourAverageTiger** [MCGamerNetwork/Issues#736]
Environment:
All regions
The issue:
/party list doesn't work and does not show who is in the party [the command doesn't return anything]
Steps to reproduce:
Join any region.
Join a party.
Run /party list
Miscellaneous Info:
N/A

**Comment by arsenalfcgunners** [comment]
NOTE: This does work if you are the only member in the party.

**Comment by forairan** [comment]
This will be fixed as of the next deployment cycle.
Thanks for the report!
