### ISSUE TITLE
Birch wood fence SG Bug

### ISSUE THREAD

**Issue by Mauro2424** [MCGamerNetwork/Issues#738]
When you right click on the birch wood fence in sruvival games they disappear and you can go trought them. Other can see you walking trought them.

Video: https://www.youtube.com/watch?v=qwjChb6jumg

**Comment by FusionDeck** [comment]
This is caused by the 1.7 - 1.8 protocol hack, as it shows the 1.8 blocks to players running that version, when the server thinks it's not there, until the block is 'updated' by the player breaking it, right clicking it or placing a block next to it.

**Comment by forairan** [comment]
See #765.
