### ISSUE TITLE
Snow Golem places snow on the ground when walking

### ISSUE THREAD

**Issue by YourAverageTiger** [MCGamerNetwork/Issues#739]
Environment

US - The hub. It can work on other regions too.

The issue

When you use a snow golem from seasonal items, you can ride it and place snow on the floor.

Steps to reproduce

Be in the hub.
Use the Gold Bar.
Click Seasonal items.
Click the snow golem.
Ride it by right clicking.
Move around.
A video of me moving around can be found here: https://youtu.be/-wc2TGTS2Jg

Miscellaneous information

https://youtu.be/-wc2TGTS2Jg

**Comment by arsenalfcgunners** [comment]
On the seasonal items note, the current seasonal items are way outdated.

**Comment by forairan** [comment]
This is a 1.7 client bug, and unfortunately it's not something we can fix. The snow is only visible to other 1.7 users - 1.8 users do not see it.
