### ISSUE TITLE
Survival Bingo Joining Gaming in Progress Glitch

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#740]
1. Environment
Survival Bingo when joining a game already in progress.

2. The issue
I cannot right click the Diamond in order to join the game.

3. Steps to reproduce
Join a Survival Bingo game that is already in progress and try to join by clicking the diamond.

4. Miscellaneous information
None

A state dump was generated and submitted successfully (ID number 17684).

**Comment by forairan** [comment]
Unable to reproduce - I tried this and was able to join the game just fine.
Are you able to reproduce this on a video?

**Comment by arsenalfcgunners** [comment]
Ok, so if you try to join a game in progress already the diamond does work if you click it against a block.   However, if you are not looking down or at a block the diamond will click properly if that makes sense.  Also, once it puts you in the game, if you do /list it says you are watching.  You can interact with the game though it seems, not sure if this causes any problems.

**Comment by forairan** [comment]
Ah, I see what you mean; I've gone ahead and fixed this, and it'll be resolved as of the next deployment cycle.
Thanks for the report!
