### ISSUE TITLE
"Ice-Bow" crashes 1.7.10 Clients

### ISSUE THREAD

**Issue by S1kBruZZ** [MCGamerNetwork/Issues#741]
**Environment**: Hub

**The Issue**: From what is happening, 
the Ice-Bow particles seem to have been added in 1.8.x so when the server tries to spawn them in, it crashes all 1.7.10 clients because they never had support for such particle.

**To Reproduce**: Shoot the Ice-Bow, preferably from a 1.8 client, near a 1.7.10, close enough so the particles render.

**Comment by forairan** [comment]
This will be fixed (_actually_ fixed) during the next deployment cycle.
Thanks for the report!
