### ISSUE TITLE
[Bug Report] Vanilla world in EU SG 1960.

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#744]
1. Environment
EU Network, SG server 1960.

2. The issue
Instead of a Survival Games map, a Vanilla world spawned.

3. Steps to reproduce
Connect to the SG 1960 server to have a look. Other than that I'm not sure how this can be reproduced.

4. Miscellaneous information
http://i.imgur.com/KhYAtsy.png
----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 18483).

**Comment by FusionDeck** [comment]
As well as EU 2011.

The SG plugin seems to not be loading, as there is no /vote or debug info.

**Comment by forairan** [comment]
The issue behind this should be fixed in the next deployment cycle.
Thanks for the report!
