### ISSUE TITLE
/upgrade system bug

### ISSUE THREAD

**Issue by iBarnyHD** [MCGamerNetwork/Issues#746]
The /upgrade sysem it very bad because i just typed /upgrade adn my survival games stats has been reseted!

**Comment by forairan** [comment]
This isn't exactly possible with how our code works.
Are you sure you didn't type `/upgrade 1`? This may have caused your stats to reset if you had a pending stat reset.

**Comment by iBarnyHD** [comment]
yes im sure..,..i just typed /upgrade and my stats has been reseted :/

**Comment by iBarnyHD** [comment]
How many % can i get back it?
....can you remove my all stats reset tokan i don't need it

**Comment by iBarnyHD** [comment]
Please, can i get it back? I had 180wins

**Comment by forairan** [comment]
I see that you triggered a stats reset:
![](http://i.forairan.com/Pkjs/5rDPYh8r+)

If you'd like to undo your stats reset, please contact support@mcgamer.net for assistance, as we can not directly assist in this matter.

**Comment by iBarnyHD** [comment]
Sorry im not a fan of the english language....can i get my stats back?

**Comment by forairan** [comment]
As I said, you will need to email support@mcgamer.net for assistance. We can not directly assist in this matter.

**Comment by iBarnyHD** [comment]
Ok i sended a Email: i want to undo my stats reset!
