### ISSUE TITLE
/party list doesn't work.

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#751]
Note: IT DOES WORK if you are the only person in the party.  But when I am in a party with friends and I do /party list it returns nothing.  Reported by a lot of people other than myself.

**Comment by arsenalfcgunners** [comment]
WUP duplicate.

**Comment by arsenalfcgunners** [comment]
#736 was closed, but it is still broken.  Not sure if the update was pushed or not, but I know that there has been a few development cycles since then.  If the fix wasn't included yet then close this.  But if it was, it is still broken.

**Comment by forairan** [comment]
Proxy hasn't been deployed yet, so that's why it's still broken. On the next Proxy update, it'll be resolved.
