### ISSUE TITLE
Can't remove pending friend requests

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#753]
When I try to remove a friend who is pending it won't let me.  This technically maybe isn't a glitch because it wasn't designed that way, but seems like that pending requests should at least be put in a separate list or made removable.  Or else you friend list looks like this: http://i.imgur.com/zrfBLLW.jpg

Btw, Devin and Rusty you are both in trouble.  That has been pending for months!

**Comment by forairan** [comment]
You need to use `/friend deny` to deny a pending friend request. However, I can see why this behavior would be a bit misleading; we'll look into modifying it.

**Comment by arsenalfcgunners** [comment]
No, that doesn't work.  These are people that I added.  It says request does not exist if I try to do that.

**Comment by forairan** [comment]
Ah, okay. Yeah, there's currently no feature for cancelling your own request, but we can implement that easily.

**Comment by arsenalfcgunners** [comment]
Yes please do!

**Comment by forairan** [comment]
You should now be able to use `/friend remove` to remove pending friend requests.
