### ISSUE TITLE
Disguise bug when being moved to a lower rank.

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#756]
![screen shot 2015-08-21 at 9 22 34 pm](https://cloud.githubusercontent.com/assets/9291541/9422525/f6d4ae98-484a-11e5-9831-38f263a1ca8f.png)
If that is true then it I would assume that this would also be an issue if a player has monthly Platinum and they have used /scramble or are disguised when it expires.  No confirmation that this is a bug though other than the report.  May want to look into it though.

**Comment by forairan** [comment]
This will be fixed in the next release. Thanks for the report!
