### ISSUE TITLE
Seasonal Items are very outdated.

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#757]
Pretty self explanatory...
![2015-08-21_21 30 32](https://cloud.githubusercontent.com/assets/9291541/9422544/04b49d74-484c-11e5-839f-cbac0e983752.png)

**Comment by Chadthedj** [comment]
That is because you are Mod, you will see all seasonal items rather than public players. Any public players who purchased the item will always have it in their inventory.
