### ISSUE TITLE
Minor /lookup issue

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#758]
Some players with a lot of Xime punishments produce a VERY long when doing /lookup.  This means that if we are using /lookup after an offense in chat it sometimes gets pushed out of our chat history to make room for the very long Xime History.  Yes, we could take screenshots before we check /lookup, but you don't want to take a screenshot every time if you don't need one since it just floods all your MC Screenshots with pointless ones. No evidence needed if you are warning. xD

Maybe make it so if the history is very long it tells you that and gives you the link to look it up on Xime instead? Very small issue but if this could be improved it would be nice.

**Comment by forairan** [comment]
As of the next release, the `/lookup` command will be modified in the following ways:
* Punishments of 60 seconds or less (i.e. automatic BSM/DIM bans) won't be displayed in the results
* If a user has over 10 punishments on their record, the output will indicate this and state that only the most recent 10 punishments are displayed
