### ISSUE TITLE
ZedChase server crash

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#762]
The ZedChase server will become "unavailable" about 75-80% into generating the world under this circumstance based on my testing:

A previous game of ZedChase ends and all users are redirected to the ZedChase lobby and another game starts.  The game will crash upon generating the world for the next game.

**Comment by arsenalfcgunners** [comment]
The following video shows this issue and the #759 issue: http://youtu.be/xeJ4Y-bvRtE

**Comment by forairan** [comment]
This tends to occur when servers have switched around several times (i.e. 7 times or so) before becoming a ZC server. I've applied something that might help with the issue, slated to be deployed in the next release. If you still see this issue past then, please do reopen this report.
