### ISSUE TITLE
Left Click Spam in Spec Issue

### ISSUE THREAD

**Issue by Chadthedj** [MCGamerNetwork/Issues#764]
When you spam left click to spec a new player, it will lock the character in a void area of the map and can't move. Only way to get out of it is to leave the server completely. There should be a cooldown on this command or something needs to be looked into to resolve this.

**Comment by forairan** [comment]
This doesn't seem to happen only on spam clicking, nor is it directly related to Xime's spectator mechanism; probably a bug in XimeBukkit 1.7/1.8's spectator support.
