### ISSUE TITLE
Survival Bingo Joining Game in Progress Glitch

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#768]
You cannot take damage when you join a game that is already in progress.  You can however interact with the environment and the Bingo creating a very abusable glitch.  I believe you are suppose to be able to join a Bingo game mid-game and play though.  So maybe damage just needs to be enabled idk.

**Comment by forairan** [comment]
Unable to reproduce.
Please use `/bugreport` next time, as it sends vital information that could help us. A video would also be helpful, if possible.
