### ISSUE TITLE
Flint and Steel SoloSG Unbreakable Bug ?!

### ISSUE THREAD

**Issue by R3chii** [MCGamerNetwork/Issues#769]
Today,at 25 August 2015 04:04 PM CEST on EU SG1897 I found this bug or something like that.
All game I was playing with this FnS and at end of the game,as I won,durability was -568/64.
I think this Is a not big bug,but If I can get some reward from finding this bug,like Iron Donor rank.Thanks ! My IGN is R3chii_

![16hlwjr](https://cloud.githubusercontent.com/assets/13976227/9486734/5a6bcb20-4bcb-11e5-9c52-1733a98dd4ef.jpg)

**Comment by forairan** [comment]
I was unable to reproduce this, but I've applied an experimental fix regardless that may fix the issue.
Thanks for the report!
