### ISSUE TITLE
Diamond Armor Bug/Glitch ?!

### ISSUE THREAD

**Issue by R3chii** [MCGamerNetwork/Issues#770]
Okey,SoloSG is full of bugs and glitches!
Before 1 hours I posted another bug report with Flint and Steal,but now I got a bigger problem.
Today at 26 August 2015 at 08:53 AM CEST EU SOLOSG SG1735 I found out new bug -.-"
I was playing with "full diamond armor" on my inventory hotbar without even seeing it -.-".
After deathmatch as I won,I accidentally opened my inventory and I saw this on photo down below.I had full diamond armor on me.
If you can see on picture I was holding FnS same as holding in my game(you can see under inventory hotbar that I had Full IRON armor with FnS,btw,there is AGEIN bugged FnS which I played all game long with it.)
Okay,now I made a compare about Iron helmet,Iron chestplate,Iron leggings and Iron boots.You can see down below where is "that little armor thing" that I had 7 and half "iron things=that thing,ya now what I am talking about".After that I went to SinglePlayer and put exacty same armor as ingame.Now I had 8 "iron things".SoloSG is full of bugs and glitches !
This is my SECOND bug repport,I want at least some reward man,maybe Iron or Gold Donor.Thanks !
Btw,I want reward !!
My IGN is R3chii_

![2015-08-26_08](https://cloud.githubusercontent.com/assets/13976227/9487745/e74c2194-4bd4-11e5-909c-5e3d6911043e.jpg)

![2015-08-26_09 101](https://cloud.githubusercontent.com/assets/13976227/9487750/eca92bfa-4bd4-11e5-9418-3e3b715c1f55.png)

**Comment by arsenalfcgunners** [comment]
I don't think this is a glitch on MCG's end if I understand it correctly.  If you only had 7.5 armor bars you did not actually have full diamond, it is just simply impossible.  You had full iron.  It is possible that there was an issue with your texture pack, that made the iron texture appear as diamond.  I am not a dev though so I could be wrong, but don't believe that this is an MCG glitch.

**Comment by forairan** [comment]
Indeed, I'd say this is a client-side glitch, as there's nothing server-side that would do this.
