### ISSUE TITLE
Deadly Descent Fly Glitch

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#771]
Watch the video for full details.  Basically you can use /fly after joining a DD game that is already in progress, and use it to easily make sure that you don't miss any jumps between blocks.  You still take fall damage, but you can literally fly to any block that you want as long as it is not too far of a drop.  Also, not sure if it had to do with this map, or the fact that I joined the game after it started, but I was not able to win the game when I reached the bottom.  I had done /fly earlier in the game to demonstrate the glitch, which I am not sure if that would have had an affect on this.  But after I stopped recording, I killed myself because I did not want to abuse the /fly glitch.  And then tried to win legit.  (This is on the exact same game on the same map) I reached the bottom and it didn't give me the win.  A player in the same game also said in chat that they reached the bottom and it wasn't working.  Not sure if they started playing from the start, of if this is a glitch when you join after it starts.  If I can confirm that that is a glitch with the map, and was not a glitch related to flying or joining the game in progress I will create another report with another state dump so you can get the details.  Probably should have done a state dump when it wouldn't give me the win as well, wups.

A state dump was generated and submitted successfully (ID number 20537).

http://youtu.be/o5OBRofYpM4

**Comment by forairan** [comment]
You joined a game of DD that was in progress, and you can't play if the game is already in progress; that explains both why you could still fly, and why you didn't win upon reaching the bottom. I suppose the game should made that a little clearer, though...

**Comment by arsenalfcgunners** [comment]
@forairan then isn't taking damage a glitch? You also can't fly if you don't have donor I don't think.  Also, when I did /list it said that everyone in the game was watching.
