### ISSUE TITLE
Ice bow crashes 1.7 clients.

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#772]
If you shoot the ice bow at a 1.7 client it will crash there Minecraft.
http://youtu.be/YTNsNUmaBtE

Shoutout to the testers who let me crash their MC!

Edit: This crash report was given to me from one of the testers: http://pastebin.com/sfFdD8Un

**Comment by forairan** [comment]
This has already been fixed; the fix just hasn't been deployed yet.
