### ISSUE TITLE
Tiering problem on Breeze Island

### ISSUE THREAD

**Issue by N0vaKaine** [MCGamerNetwork/Issues#779]
Environment:
Any Survival Games server, apparent on the AU region.

The issue:
Some of the chests on Breeze Island have a tiering problem, where sometimes they're tier 2, and other times they're tier 1's

Steps to reproduce:

Open specific chests on Breeze Island on different servers.

![2015-08-30_12 18 26](https://cloud.githubusercontent.com/assets/9727189/9565454/87464878-4f13-11e5-80fe-39b0a1c1783c.png)
![2015-08-30_12 19 57](https://cloud.githubusercontent.com/assets/9727189/9565455/8a963cf4-4f13-11e5-891e-04e930f67566.png)

Miscellaneous Information:
I believe this bug is also on SG3

**Comment by arsenalfcgunners** [comment]
OMG I THOUGHT I WAS CRAZY AND ALWAYS IMAGINING THINGS! Yes, I have 100% seen this occur on Breeze Island.

**Comment by N0vaKaine** [comment]
![2015-09-05_20 55 07](https://cloud.githubusercontent.com/assets/9727189/9702065/a8e49868-5490-11e5-8c98-532a09fdb5c4.png)
Ok, I got an image of one of the chests being a tier 2, when it was a tier 1 in the other picture above
