### ISSUE TITLE
Outdated hub (AU)

### ISSUE THREAD

**Issue by FusionDeck** [MCGamerNetwork/Issues#781]
Environment

AU Hub (1105)

The issue

The hub is using outdated code, including the old sidebar, compass GUI and a book. The hub itself is still the same, but on daytime. Including the old [XKMB] rather than [XKMBG]

Steps to reproduce

Join AU 1105 (Hub)

Miscellaneous information

http://i.imgur.com/gNJ9I2Y.png

**Comment by arsenalfcgunners** [comment]
I did a state dump.

A state dump was generated and submitted successfully (ID number 21061).

**Comment by forairan** [comment]
This issue has been resolved.
Thanks for the report!
