### ISSUE TITLE
/party list still broken

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#782]
First image: Says my name correctly.  But only says part of Upward's ign.
http://imgur.com/Sc2nCRj,EtbzAAo
Second image: No spaces between names.  Still an issue with the last name, should say "Upward"
http://i.imgur.com/EtbzAAo.jpg

**Comment by forairan** [comment]
This issue will be fixed as of the next deployment cycle.
Thanks for the report!
