### ISSUE TITLE
Possible way to escape the map on Survival Games 2. http://imgur.com/a/aFX6F

### ISSUE THREAD

**Issue by xpotatoe** [MCGamerNetwork/Issues#783]
if you sponsor an ender pearl, or maybe another way, you can get outside the map on SG 2 from up here. Getting up here is intended obviously due to the chest. http://imgur.com/a/aFX6F
A state dump was generated and submitted successfully (ID number 21083).

**Comment by AlpakaWhacker** [comment]
Issue Resolved
