### ISSUE TITLE
UHC Worlds Must Needed Additions

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#789]
Players have been requesting this so much I am going to add this as a needed enhancement.  

1. Ability to track the health of others using a command or tab bar.
2. Ability to use the head they get from killing someone into a golden head that they can eat to regen some health.  

Also, from a moderators perspective I can see the spectating becoming an issue.  The 1.8 spectating allows people to fly through blocks so they can literally fly down into caves very easily and who players where the diamonds are.  Kind of like an third person x-ray mod.

**Comment by forairan** [comment]
As suggested in the bug report instructions, please split this issue into multiple reports, one for each issue. This will allow us to keep better track of issues/enhancements and their resolution timeframes.
