### ISSUE TITLE
EU HUB 2793 - Cannot Disguise

### ISSUE THREAD

**Issue by Alkan1** [MCGamerNetwork/Issues#793]
In the EU hub 2793, players cannot disguise. It stucks in the generating random username part.
Here is a screenshot: http://imgur.com/sODVj0n

In the screenshot you can see when I do /l it shows my name regular, but in TAB it shows me undisguised.

Also here is a video: https://youtu.be/6TCbnLZN350

Also when I do /lookup in that HUB it says "Database error", here is a screenshot:

![](http://i.imgur.com/sFyvyRx.jpg)

But in other HUBs it works.

**Comment by Alkan1** [comment]
I think it is fixed right now ^^

**Comment by arsenalfcgunners** [comment]
Do a state dump by doing /reportbug.  I think this might be useful for the devs in this scenario.  Not 100% sure though.

**Comment by forairan** [comment]
This is actually part of a much larger internal issue; however, regardless, said issue should be fixed as of the next production deployment.
Thanks for the report!
