### ISSUE TITLE
People dealing more damage with a weaker weapon

### ISSUE THREAD

**Issue by y0loftw69** [MCGamerNetwork/Issues#794]
So in the past week people in SG where killing me with stone swords or wooden swords ( we both were full iron ) and I had diamond sword ??? Why do they do more damage and I'm sure they didn't crit me I crit them sometimes because I get launched in to the air 1 block because I have weird knockback cuz my internet sucks. Last game I played 10 mins ago I was full iron with a diamond sword and I met a guy that was full iron with a stone sword we both shot a fully pull back arrow and hit then he set me on fire and we started trading hits. Amazinglly I took 3 hits and died !!!! How ???

**Comment by forairan** [comment]
I don't know what to say about this, but it's definitely not a bug.
