### ISSUE TITLE
SoloSG - Not Disguising?

### ISSUE THREAD

**Issue by DarkNiightz** [MCGamerNetwork/Issues#797]
Player not disguised in SoloSg

Environment

EU1813 13.09 12:19ZS 2015

The issue

I went into a server and found a guy not disguised. (SoloSG)

Steps to reproduce

I don't know if there is any, I went into a server and found him like that.

Miscellaneous information

http://i.imgur.com/0bqFmWB.jpg
#23086 - State Dump

**Comment by arsenalfcgunners** [comment]
He may have joined at the last second. Kind of like how an SG game can have more than 24 players if you join right as the lobby ends.  Just a guess idk.
