### ISSUE TITLE
Spectators can break/interact with boats

### ISSUE THREAD

**Issue by ep1cn00bt00b** [MCGamerNetwork/Issues#80]
Environment:

AU survival games- spectating.

The issue:

Whist spectating a game, and flying around, I teleported to someone who was on a boat, and as soon as this happened, their boat broke. I thought this was strange, so I tried to replicate this if I didn't just teleport to someone, and the same thing happened- if I was hovering, as a spectator, and someone that was driving a boat collided with me, their boat would break as if I was a tribute.

Steps to reproduce:

1) Be a spectator
2) Hover in the path of a tribute that is driving a boat. Note: the boat only broke on one occasion that I teleported to them.

Miscellaneous information:

Sorry- no screenshots... but I tried this many times and each time the boat broke.

-ep1cn00bt00b

**Comment by subv3rsion** [comment]
This appears to no longer be possible with the new spectator mode, cannot replicate. I do remember this being a problem before the spectator mode was introduced though.

Thank you for the report!
