### ISSUE TITLE
Last Charge on the FnS is broken

### ISSUE THREAD

**Issue by UnFuggettable** [MCGamerNetwork/Issues#800]
1. As far as I know this is a server wide issue that occurs in every game, and occurs on all areas of the servers.
2. The flint and steel is supposed to have three working charges, however, as of now the first two charges work and the last charge does not. By this I mean the fire will not place and then the Flint and Steel will break.
3. To reproduce this issue, all you need is a Flint and Steel and attempt to place all three charges.
4. N/A

**Comment by Divining** [comment]
A game build was pushed today, and for me all 3 charges still aren't working.

**Comment by forairan** [comment]
This (hopefully) should be resolved in the next release.
Thanks for the report!
