### ISSUE TITLE
Frozen on Alaskan Village

### ISSUE THREAD

**Issue by UnFuggettable** [MCGamerNetwork/Issues#801]
1. As I only play on the US servers, I only know about this issue on these servers. It occurs in every game of Alaskan Village as well.
2. The issue is certain parts on the outer areas of Alaskan Village will cause me to freeze completely. I will be frozen as if I am ghosting, however, my internet will be 100% perfect. I notice this issue in multiple games of Alaskan Village and it has come to my attention that other players also experience this same issue. 
3. To reproduce this issue, you will just have to walk along the outsides of the map. I notice a main reoccurring area is towards the antenna on the snow hill of the map.
4. N/A

**Comment by Divining** [comment]
Broken chunk. This is probably a map glitch for AlpakaWhacker, although could be a plugin error with this map in specific.

**Comment by AlpakaWhacker** [comment]
Issue Resolved.
