### ISSUE TITLE
Endless lobby time

### ISSUE THREAD

**Issue by themangotiger** [MCGamerNetwork/Issues#803]
1. EU Solosg 2113

![](http://i.imgur.com/TNnHI8i.png)

2. The lobby time says -79 minutes. The time will get closer to 0 by 2 minutes and then take away 3 minutes, in an endless loop.

**Comment by Divining** [comment]
I was able to have this issue reproduced in 2/5 lobbies on US.

**Comment by GustyyHD** [comment]
![2015-10-03_15 02 35](https://cloud.githubusercontent.com/assets/10827582/10263148/e16ef9fa-69e2-11e5-832c-5e77837ac896.png)

Also happened here

**Comment by forairan** [comment]
Should be fixed as of the last release.
