### ISSUE TITLE
SoloSG Chat Disabled 

### ISSUE THREAD

**Issue by Divining** [MCGamerNetwork/Issues#804]
I'm aware this is intentional, however at the end of the game you're unable to say GG, or other related comments. As the game is over, you should be able to chat. I was told this was a bug by another Mod and to report it here. 

My idea is to check the game state, if it's over, allow said message(s).

**Comment by Gjosiah** [comment]
This appears to have been an oversight; Solo SG has now been changed to allow chat after the game ends. This change will be live by the weekend.
