### ISSUE TITLE
Xac list issue

### ISSUE THREAD

**Issue by Sedrazo** [MCGamerNetwork/Issues#805]
Okay, so this is an issue I have seen on the EU servers, and on the US servers. I am not sure if it's on the AU servers. This is the issue.

Issue: Whenever I am going through the /xac list reports ingame. All of the players that have been reported seem to be Offline. I have been trying to find hackers through that command. Yet, it appears that it doesn't seem to pick up, they are all Offline whenever I try to do a /xac list report ingame.

**Comment by Ceroria** [comment]
Can confirm ^

Players appear to be offline no matter what when trying to Go-To them through XAC List command.

This could be tied into the fact that the /report command is broken, meaning the list does not update and the current list of players on /xac list are outdated.
