### ISSUE TITLE
Scoreboard Timer Messed Up

### ISSUE THREAD

**Issue by blismatic** [MCGamerNetwork/Issues#807]
1. US region, server ID280, gametype: solosg, time it happened: around 3:20pm PST

2. The scoreboard timer was counting negatively, so it just keeps going up and wont stop.
    http://prntscr.com/8ng3bs

3. not sure how this happened, so i don't know how or if it can be reproduced. i was only poked about it on teamspeak so i joined and saw.

4. none.

**Comment by forairan** [comment]
Should be fixed as of the last release.
