### ISSUE TITLE
Construct Has pink name in voting list

### ISSUE THREAD

**Issue by Goldsminer** [MCGamerNetwork/Issues#808]
Description
Try to separate your description into four different sections, if possible:

1.Environment

Survival Games on AU

2.The issue

When doing /v 'Construct' is pink like map-maker.

3.Steps to reproduce

Find 'construct' as a voting option and it will be pink.

4.Miscellaneous information

http://imgur.com/K7sAGdb

**Comment by KitMencha** [comment]
http://www.mcgamer.net/threads/survival-games-map-updates-3rd-october-2015.224617/
Check the bottom of the thread. It's meant to be there. Featured map.

**Comment by Gjosiah** [comment]
As mentioned, this is a new feature we have added to "feature" a map so it will always be available for voting.

We will however take this into consideration to make it more apparent that this behavior is intended.
