### ISSUE TITLE
Battlegrounds - Ice Map | Warp "West" Bug 

### ISSUE THREAD

**Issue by Divining** [MCGamerNetwork/Issues#815]
1. This has been happening for a while, and occurs in every Battleground server.

2. You do not spawn with any gear, and you spawn facing down - this ONLY happens on the Ice map, on WEST warp ONLY.

3. Go on the ice map, click on the west warp sign, and boom - it's reproduced.

4. VIDEO showing this bug: https://www.youtube.com/watch?v=ome17eIzi1Q&feature=youtu.be

**Comment by forairan** [comment]
This has been fixed and should be live shortly.
Thanks for the report!
