### ISSUE TITLE
Colored name in tab and above their head.

### ISSUE THREAD

**Issue by DarkNiightz** [MCGamerNetwork/Issues#818]
Tips to remember while submitting an issue (please read this carefully before submitting your issue report):
- Search the issue tracker to ensure that your issue is not a duplicate.
- Be clear and concise in your description.
- Submit one issue per report. Putting multiple issues into one report makes it difficult for us to separate and identify the issues within our code. If you submit multiple issues in one bug report, your report will be closed and you will be asked to separate them.

Try to separate your issue report into four different sections, if possible:
1. Environment
This section should provide all information regarding the environment where the issue occured, location (US/EU/CA/AU), server ID, gametype, time of when the issue happened, etc.

US493 15.10 00:53Z 2015

2. The issue
This section should provide a detailed explanation of the issue.

The users name is colored in the tab and also above their head. 

3. Steps to reproduce
If applicable, this section should provide a detailed list of steps needed to reproduce the issue.

I have no idea, it just randomly happened.

4. Miscellaneous information
Information that doesn't necessarily fit into any other sections, such as screenshots.

http://i.imgur.com/uO7hLES.jpg

Please remove the above text before submitting your issue report, but DO NOT REMOVE ANYTHING BELOW THIS LINE! The information below this line will help us find the issue faster.
----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 26659).

**Comment by InstanceOfDev** [comment]
Isn't this meant to happen?

**Comment by DarkNiightz** [comment]
In the hub, yes. In-game, no or everyone would have a colored name and it would still be a bug because only 1 person has it. c:

**Comment by InstanceOfDev** [comment]
Oh! I thought you meant the hub.
