### ISSUE TITLE
MCGamerMonitors becoming visible.

### ISSUE THREAD

**Issue by DarkNiightz** [MCGamerNetwork/Issues#820]
Tips to remember while submitting an issue (please read this carefully before submitting your issue report):
- Search the issue tracker to ensure that your issue is not a duplicate.
- Be clear and concise in your description.
- Submit one issue per report. Putting multiple issues into one report makes it difficult for us to separate and identify the issues within our code. If you submit multiple issues in one bug report, your report will be closed and you will be asked to separate them.

Try to separate your issue report into four different sections, if possible:
1. Environment
This section should provide all information regarding the environment where the issue occured, location (US/EU/CA/AU), server ID, gametype, time of when the issue happened, etc.

HUB 15/10 14:35Z 2015 / EU2793

2. The issue
This section should provide a detailed explanation of the issue.

Hundreds of "MCGamerMonitor##"s becoming visible and making the hub laggy for some users.

3. Steps to reproduce
If applicable, this section should provide a detailed list of steps needed to reproduce the issue.

Wait in a hub until they turn visible for you, other than that I've got nothing.

4. Miscellaneous information
Information that doesn't necessarily fit into any other sections, such as screenshots.

http://i.imgur.com/zY0Vvpg.jpg

Please remove the above text before submitting your issue report, but DO NOT REMOVE ANYTHING BELOW THIS LINE! The information below this line will help us find the issue faster.
----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 26712).

**Comment by forairan** [comment]
This might be something client-side; temporary workaround is to leave the server (i.e. switch hubs), then come back.

**Comment by forairan** [comment]
This issue should (hopefully) be resolved as of the next release. In the meantime, you can use the workaround stated above.
Thanks for the report!
