### ISSUE TITLE
Flint and steel has been fixed a lot, but still experience some problems

### ISSUE THREAD

**Issue by WilliamFTW** [MCGamerNetwork/Issues#821]
Environment:
EU Servers. Server ID: 1699. Survival Games Solo. It happened 18th of October 2015 01:53AM

The issue:
Great work on fixing the FNS, it's a lot better now than it was, but I still experience the bug if I super quickly try to put it down. (as shown in the video below)

Steps to reproduce:
hm I do not have any suggestion on how to fix it or if it is possible so hard for me to say, but please take a look at the video under. 

Miscellaneous information
Here is the video and what happened: (played while listening to you guys on TS and testing the flint and steel out :P)
https://www.youtube.com/watch?v=drsUjUUGo4Y

**Comment by Mr-Bari-99** [comment]
This glitch is still going on for US.

**Comment by forairan** [comment]
We're going to try another experimental fix in the next beta build - however, from what we've tested on the alpha/development servers so far, it _seems_ to work.
