### ISSUE TITLE
Ice Bow (Cosmetic Item)

### ISSUE THREAD

**Issue by FusionDeck** [MCGamerNetwork/Issues#822]
**Environment**

AU, US & EU

**The issue**

Using the Ice Bow from the credit shop crashes all players around it.

**Steps to reproduce**

Select the 'Ice Bow' and shoot it, it will crash players.

**Miscellaneous information**

State Dump ID: #27156 (Generated on the AU Network)

**Comment by DarkNiightz** [comment]
It now only crashes clients that are using 1.8, I tested it in a hub with an alt and when it got kicked I received this message; http://i.imgur.com/DQSJl84.png

**Comment by forairan** [comment]
This again?! :(
It'll be fixed next release. Thanks for the report, though!

**Comment by InstanceOfDev** [comment]
@forairan This is still an issue for 1.7 clients. If you shoot the bow and the player is using 1.7, it will still crash that player.
