### ISSUE TITLE
Games aren't starting

### ISSUE THREAD

**Issue by SinInASuit** [MCGamerNetwork/Issues#824]
1. Environment
Issue is happening on AU SG, 1282

2. The issue
The game isn't starting at all, everyone remains in hub whilst the pregame timer happens. After it ends, everyone is teleported back to the hub, as if the game ended.

3. Steps to reproduce
idk, just go on SG

4. Miscellaneous information

![2015-10-23_17 59 42](https://cloud.githubusercontent.com/assets/15040382/10686482/51e197d8-79b0-11e5-9029-0f668ed06c86.png)

----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 27534).

**Comment by forairan** [comment]
There is an actual code issue behind this; however, in this instance, the issue was only triggered by a specific environment on that specific server, and has been fixed. The code-level issue will be fixed next release.
