### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by soulknight47** [MCGamerNetwork/Issues#825]
https://www.youtube.com/watch?v=V-Rk5C5fsKs&feature=youtu.be fix it

**Comment by InstanceOfDev** [comment]
Completely the wrong way to report a bug. Please actually read the proper way to report bugs here:
https://github.com/MCGamerNetwork/Issues

And don't sound like an ass while you're at it. "Fix it" is not the way to ask.

**Comment by forairan** [comment]
No information provided by user. Probably a duplicate of #826.
