### ISSUE TITLE
PVP in Battlegroundshub

### ISSUE THREAD

**Issue by LilC91** [MCGamerNetwork/Issues#826]
Environment

EU 1702, BattleGrounds, (see picture of exact game), 24. Oct 2015 02:25 PM CEST.

The issue

When playing Battlegrounds, in the lobby of the game with the ---, it is possible to do PvP with hands, kill eachother and get golden apples, and get the kill on the scoreboard, without entering the game at the signs. Only this game it happens, not the other. 

Steps to reproduce

It happens at all servers, it's not the first time i've seen it. 

Miscellaneous information

http://imgur.com/1TLdvN0 (This is the lobby of the game), State Dump ID: #27695

**Comment by arsenalfcgunners** [comment]
This only happens on the ice map.  It seems that spawn is set in the wrong location.  Might be an @AlpakaWhacker issue idk.
