### ISSUE TITLE
Invisible Mobs Survival Bingo

### ISSUE THREAD

**Issue by YourAverageTiger** [MCGamerNetwork/Issues#828]
# Invisible Mobs in Survival Bingo

There have been issues where mobs aren't showing up to players and they appear invisible but their sound still plays.

# Environment

US Survival Bingo, haven't tested on other regions.

# The issue

There are occasions where in a Survival Bingo game the user may hear a mob but they may not see them.

# Steps to reproduce

N/A

# Miscellaneous information

* Video: https://youtu.be/wBbcdPV1oJE

**Comment by arsenalfcgunners** [comment]
This is an issue in UHC Worlds as well.
