### ISSUE TITLE
Skyward Crest DM Bug/Possible Server Bug

### ISSUE THREAD

**Issue by charliewolves** [MCGamerNetwork/Issues#830]
Environment
EU2796

The issue
Lightning Spurs everywhere in DM as soon as the DM begins, and is constant, therefore the user who Chuggs most or has best armour is even more unfairly advantaged. Also there is a Missing Crafting table at spawn I believe

Steps to reproduce
EU2796 and Vote Skyward Crest

Miscellaneous information
None.

**Comment by AlpakaWhacker** [comment]
Issue has been resolved.
