### ISSUE TITLE
/chat ignore [name] can be used to reveal /d's

### ISSUE THREAD

**Issue by S1kBruZZ** [MCGamerNetwork/Issues#832]
Try to separate your issue report into four different sections, if possible:
1. Environment: 
AU Hub (At the current moment, I don't believe the feature in game.)

2. Description:
/chat ignore [name] can be used to reveal /d's
For example
Rustywolf had the name '1kocuiHe'
Using '/chat ignore 1kocuiHe', I was able to find out it was him, as displayed here 
![Screenshot](https://cloud.githubusercontent.com/assets/2324492/10966532/0760b604-8404-11e5-8367-348e08cfa776.png)

3. How to Re-create:
Get someone to /d, or find a /d player, in a hub.
do /chat ignore [their disguise name]
then feel free to do /chat listen [name] to listen to them again, unless of course you don't like them ;)

----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 28937).

**Comment by forairan** [comment]
This should be fixed in the next beta build. Thanks for the report!
