### ISSUE TITLE
Website shows duplicate winners

### ISSUE THREAD

**Issue by nikolafeelzzhd** [MCGamerNetwork/Issues#834]
Today I was playing on the new Halloween map and I was less stacked than the other opponent so I decided to wait out the whole deathmatch. This is what happened:

http://prntscr.com/911m22

I won the game as well! If anyone finds out about this bug it's going to be abused so hard so please fix this. Thank you!

**Comment by SinInASuit** [comment]
I'm pretty sure whoever came first will get the win, and not both of them

**Comment by Gjosiah** [comment]
Interesting, that must be a glitch with the website, as the game can only have one winner. We will look into this soon; thanks for reporting it.

**Comment by nikolafeelzzhd** [comment]
No problem!

**Comment by arsenalfcgunners** [comment]
@Gjosiah happens a lot with UHC Worlds.
