### ISSUE TITLE
MCGamer v2 Bug Report: Minecarts

### ISSUE THREAD

**Issue by Nephilim04** [MCGamerNetwork/Issues#84]
-= Environment =-

On the MCGamer v2 preview network. Specifically in the Arcade hub above the Colorzone mini game portal.

-= The issue =-

After taking the ride in a minecart above the Colorzone portal, the minecarts will fall down into the Arcade hub and stack up. They can be broken be fisting them, but they cannot be obtained and will remain floating on the ground.

-= Steps to reproduce =-

Click the button to receive a minecart and take a ride.

-= Miscellaneous information =-

I recorded a video of the issue: https://www.youtube.com/watch?v=J4xFujQi28o&feature=youtu.be

**Comment by forairan** [comment]
No longer applicable.
