### ISSUE TITLE
SoloSG Typos

### ISSUE THREAD

**Issue by TheJellyfish** [MCGamerNetwork/Issues#842]
http://www.mcgamer.net/games/solosg/view/

Says 24 players will fight but there is only 12

and that should say 11 others not 12 (as then it would a 13 player game)
![screenshot_79](https://cloud.githubusercontent.com/assets/7889946/11324504/9eeb8498-912b-11e5-8dd8-008af56d1324.png)

**Comment by forairan** [comment]
The wording on the website should be fixed now (or within a few hours at most), and the wording in-game will be updated in the next beta build.
Thanks for the report!
