### ISSUE TITLE
/rules needs to be updated

### ISSUE THREAD

**Issue by DarkNiightz** [MCGamerNetwork/Issues#844]
Rules need to be updated

When you do /rules, at the bottom it says "Terms Of Service applies at mcsg.in". The only problem with that is mcsg.in doesn't lead to the mcgamer website anymore.

Example:

Do /rules in game

Environment

On all SG / SoloSG servers.

Steps to reproduce

Go into a server and type /rules

Miscellaneous information

http://i.imgur.com/ewzf9mS.jpg

**Comment by forairan** [comment]
This will be fixed in the next beta build. Thanks for the report!
