### ISSUE TITLE
BUG IN SG SERVERS

### ISSUE THREAD

**Issue by dang39** [MCGamerNetwork/Issues#845]
if you go to server US-445 now there is a wierd bug where the map is like glitched IMPORTANT itll only last a little bit longer

**Comment by forairan** [comment]
This provides no helpful information to us - we're not available to instantly go to a server when someone finds a bug, especially on a holiday.

**Comment by dang39** [comment]
thats okay.i was hoping that saying this could help but im also kinda new
so i had no idea what was right and what was wrong. :) i hope youll
appreciate me trying tho.
