### ISSUE TITLE
People can say "ez" in chat (Glitch)

### ISSUE THREAD

**Issue by Lebron12** [MCGamerNetwork/Issues#849]
Environment:
This bug or error occurred on EU 1474 on Survival Games

The Issue:
A Player (or players) was able to say "ez" in the chat without it being filtered out by the trashtalk filter. I think this is a glitch not a bug.

Steps to reproduce:
To reproduce you *would* type "ez" in chat, but I think since the trashtalk filter didn't filter it out, I think it just isn't enabled on that specific server.

**Comment by arsenalfcgunners** [comment]
If you see it again do /reportbug.  That will create a statedump which probably would provide some useful info in this situation.
