### ISSUE TITLE
SG Pregame Glitch (still in lobby)

### ISSUE THREAD

**Issue by GoontherMC** [MCGamerNetwork/Issues#857]
Environment:
     This glitch occurred on the the US servers survival games, specifically US 244 at 4:07pm (est) on the 17th of December.

Issue: 
     As the timer for the lobby ran out and pregame started, nobody was sent into SG. Instead we were all still at spawn as the timer went down in the chat; when the timer ended the server said "Game has ended!" and all players were transferred to the hub.

Steps to reproduce:
     I'm not sure at all, first time this has happened to me, I think it may be the specific SG server (US 244).

Evidence (information):
http://i.imgur.com/k9seaoq.png

**Comment by GoontherMC** [comment]
I got the glitch again except this time I recorded it.

Environment:
This glitch occured on the US servers survival games, specifically US 2281 at 12:07am (est) on the 18th of December.

(same issue and steps to reproduce as listed in above post)

Evidence (information):
https://www.youtube.com/watch?v=seg7bsPhUtQ&feature=youtu.be

**Comment by GoontherMC** [comment]
The glitch happened again, almost two months after posting this.

Environment: 
This glitched occurred on the US servers survival games, specifically US 790 at 10:23PM (est) on the 15th of February. The game was also MCSG MAKER.

(same issues and steps to reproduce as listed in first post)

Evidence (information:
http://i.imgur.com/lynfQgE.png

**Comment by CAmadeusA** [comment]
"(same issues and steps to reproduce as listed in first post)" && "Steps to reproduce:
I'm not sure at all,"

Please include steps to reproduce so that we can more properly diagnose this issue.

**Comment by GoontherMC** [comment]
The thing is there are no steps to reproduce.

I just joined the game, the timer went down, and we all stayed in the SG lobby.

There's no pattern or specific thing to do to get it to happen again. I'm also not sure if going back to the game would cause the glitch again.
