### ISSUE TITLE
SG2 has all Tier 1's

### ISSUE THREAD

**Issue by WildcatGecko** [MCGamerNetwork/Issues#858]
Environment: All SG servers that run the Survival Games 2 map. It seems to have happened in the latest map update, in which the tiers were said to be updated.

The Issue: The only current tier 2's that I could find out of the dozens of chests I know on the map are the 4 innermost corn chests. All other chests I've checked are tier 1.

Steps to Reproduce: Just find a game on SG2, or do the super secret map stuff.

Misc: N/A

**Comment by CAmadeusA** [comment]
This was resolved several map updates ago. Closed.
