### ISSUE TITLE
us.mcgamer.net SB lobbies not working

### ISSUE THREAD

**Issue by R2D212** [MCGamerNetwork/Issues#859]
Hello My name is R2D2_1 and I am one of your fellow players on the mcgamer server. The reason why I here to discuss an issue is that the Survival Bingo lobbies are not working and without the lobbies   
I will not be able to play and other players will leave the server which will make the rest of us with less people to play with on SB. So please fix the lobbies it would be helpful if you check the server address is us.mcgamer.net and please fix it I want to play. Thank You

**Comment by forairan** [comment]
Should be fixed.
