### ISSUE TITLE
1.8 spectator speed. [Survival Games] [V2] [bug]

### ISSUE THREAD

**Issue by Person903q** [MCGamerNetwork/Issues#86]
Environment: On a 1.8 client that is in spectator mode

The issue: You get tp'd back when your fly speed gets faster

Steps to reproduce: Go into 1.8 on MCSG, go into a live game and try to fly to the point where you speed starts to get faster

Miscellaneous information: Sorry, I dont know how to add tags so I just said what it was in the title. I believe that you get a free platinum rank for reporting bugs? I would like it to go to the account: Mr_kool69
Thats it, thanks!

**Comment by forairan** [comment]
This was fixed with the switch to support only 1.8.
