### ISSUE TITLE
Fire doesn't work consistently

### ISSUE THREAD

**Issue by Mr-Bari-99** [MCGamerNetwork/Issues#860]
1. Environment
This problem is relevant to the areas of US, EU, and AU. It has happened in every server I've joined in the past few months. This pertains to SG. This problem has continued to happen over the past few months.

2. The issue
Fire sets inconsistently. At first I thought it was when you change quickly from the sword to fns and back, but I have noticed that it doesn't work other ways too. Even when I hold out the fns in my hand for a bit before setting the fire, not all the charges will set.

3. Steps to reproduce
1. Switch quickly from sword to fns and back.(Works rarely)
2. Switch quickly from sword to fns.(Works rarely)
3. Holding it in your hand a little bit before setting.(Works more often than first two options but is still not consistent)
Note: I haven't really found much of a pattern for when it works and when it doesn't.

4. Miscellaneous information
Video of me on plain 1.7.10 with no mods installed.
https://www.youtube.com/watch?v=r5OOOD505pg&feature=youtu.be

Please remove the above text before submitting your issue report, but DO NOT REMOVE ANYTHING BELOW THIS LINE! The information below this line will help us find the issue faster.
----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 33788).

**Comment by Envici** [comment]
This was fixed in #891

**Comment by arsenalfcgunners** [comment]
Yes @CAmadeusA want to close this?
