### ISSUE TITLE
Flint and steel won't work

### ISSUE THREAD

**Issue by DeopMC** [MCGamerNetwork/Issues#863]
The issue happened MOST OF THE TIME for me.

Like i if i place my fns down, it dissapears.

**Comment by forairan** [comment]
We need more information to help to diagnose the issue.
What region were you playing on? What time (approximately) did this last happen? If you remember, what server ID were you on when it happened?

**Comment by forairan** [comment]
As no further information has been provided, I'm closing this issue.
If you are still experiencing issues, feel free to open another report.
