### ISSUE TITLE
Lobby starting pregame?

### ISSUE THREAD

**Issue by Sedrazo** [MCGamerNetwork/Issues#865]
Basically, the issue is. I was in a regular game and all of a sudden, the lobby starts to go in pregame. This is what I mean. http://i.imgur.com/LRoyA7u.png

The screenshot provides that this was during the lobby, and it started pregame in the lobby. That's basically the issue.

**Comment by GoontherMC** [comment]
I've made an issue report similar to it: https://github.com/MCGamerNetwork/Issues/issues/857
