### ISSUE TITLE
Hub compass unusable sometimes

### ISSUE THREAD

**Issue by M3rsh** [MCGamerNetwork/Issues#869]
1. Be in a game
2. Be in your first inventory slot
3. /hub
4. Right click compass and nothing happens
5. Go out of first inventory slot and back in, now compass works fine

**Comment by forairan** [comment]
I haven't been able to replicate this. What Minecraft version are you using?
When you join the hub, your active inventory slot is set to the 5th slot (in the middle of your hotbar), which explains why this wouldn't work. If there's a clientside glitch leading to the proper inventory slot not being set when you're put back in the hub, I can see how this would cause confusion.

**Comment by M3rsh** [comment]
That's odd. I've been able to replicate it every time. My active slot never changes. I'm using 1.7.10 with Forge and LiteLoader, though this happens even when using a clean profile with 1.8. Must be client-side, then.
