### ISSUE TITLE
AU 1120 SG Lobby

### ISSUE THREAD

**Issue by TrebleMaker077** [MCGamerNetwork/Issues#871]
http://imgur.com/0Xd30X3

When I did ./join sg it took me to AU 1120 for sg and it was in a Survival world, still in adventure mode as well.

**Comment by TrebleMaker077** [comment]
https://imgur.com/d8UIe61 

another screenshot I got from a community member on EU 1810

**Comment by forairan** [comment]
Should be fixed.
