### ISSUE TITLE
Double health bar/double hearths

### ISSUE THREAD

**Issue by R3chii** [MCGamerNetwork/Issues#873]
Soo before 4 days I was playing on your server EU 1588 29 Dec 2015 13:58 CET and when I killed a full iron guy and Moderator I recived extra health bar..

https://www.youtube.com/watch?v=a0TlrAJnY4g

**Comment by forairan** [comment]
This isn't a bug; you were playing in a MCSG Maker game, which is a custom server/unranked game, and the host had opted to give everyone 20 hearts.
