### ISSUE TITLE
Fence on Holiday Resort 2 Causing Kick for Flying

### ISSUE THREAD

**Issue by TBritts** [MCGamerNetwork/Issues#875]
Hey guys, first report so sorry if I mess this up a little. 

Description
Environment

This was on Holiday Resort 2, in US607, however I have had this happen on multiple other servers to so I don't think it's unique to 607. It's on the Northeast corner of the map, up on the ledge, in the white dome like building. There are three chests on top of the dome, so I climbed the staircase and hopped up onto the fence to get to them, and I got stuck. Anytime I moved I glitched back to the block, and after about the fifth time, it kicked me from the game. I've actually had this happen a few times, each time hoping that I'd get lucky enough to survive, but I've had no luck. 

It's a little frusterating, I have no idea how you'd fix it but I just want you to be aware of the issue.
I typed /reportbug and got the number 35444, not sure if you'd need that for this scenario but I saw somewhere else you might need it. 

To replicate, go on Holiday Resort 2, to the northeast corner of the map. Find the white dome. Go inside, climb halfway up the staircase. Step onto one of the lower fences in order to jump onto the higher ones. Each time I've done this I've been kicked. I've done it with Optifine, without it, and on multiple servers.

Please let me know if I need to correct anything in here.

Thanks.

**Comment by arsenalfcgunners** [comment]
It is a 1.8 fence.

**Comment by CAmadeusA** [comment]
This issue has now been fixed. Thank you for reporting.
