### ISSUE TITLE
BattleGrounds Lag/BattleGrounds Leaderboard

### ISSUE THREAD

**Issue by Porridge123** [MCGamerNetwork/Issues#876]
1. Alot of the time in battlegrouds on AU it will freeze very often for about 2 this is every bg and it needs to be fixed
2. The leaderboard in battlegrounds is too small to display the score of some people if they have a long name.

**Comment by forairan** [comment]
In the future, please separate your issues into one report per issue, as this helps us to keep track of each issue.

1. This is likely either your connection or a routing issue with our Australian provider. Unfortunately, both of these are out of our control.
2. This is a Minecraft limitation that we can't do anything about.
