### ISSUE TITLE
Inverted chest tiers in normal SG.

### ISSUE THREAD

**Issue by DarkNiightz** [MCGamerNetwork/Issues#882]
Inverted chest tiers in normal SG. - 

So I was playing a game it was pretty normal but instead of all the spawn chests being tier 2 they were all tier 1, I thought it was probably like breeze island where its just a map bug but as I ran around the map all of the tier 2's were tier 1 and tier 1's were tier 2.

EU 2795 - Normal SG - 15.01.2016 - 12:28

I don't know what causes it but the only thing that I can think of is that with the new MCSG maker update the inverted chest mutator has transferred with the change of the server so that all the chests in a normal SG game are inverted too.

https://www.youtube.com/watch?v=eoOWx00OZ3o

**Comment by CAmadeusA** [comment]
Is this still an issue?

**Comment by DarkNiightz** [comment]
I don't believe so, I guess you can close this and if I see it again I will create a new bug report and tag this one.

**Comment by Gjosiah** [comment]
This was indeed fixed, I must have forgotten to close the issue earlier.
