### ISSUE TITLE
Mask/Drank Bug in Solo SG

### ISSUE THREAD

**Issue by TrebleMaker077** [MCGamerNetwork/Issues#884]
https://imgur.com/9a0qBLB

So when you ./drank or ./mask as a donor in the lobby of solo sg, when you get warped or tp'd to the game it won't automatically disguise you. It will leave you as your IGN with the mask/drank.

So yeh mask in the lobby, it wont disguise you in the game.

**Comment by CAmadeusA** [comment]
This issue will be resolved in the next update, thank you for reporting! :)
