### ISSUE TITLE
Flint and Steel Glitch

### ISSUE THREAD

**Issue by Ceroria** [MCGamerNetwork/Issues#891]
It has returned ;-;

I personally encountered it on an MCSG Maker match on SG4 on the US Region.

The issue seems to be the same as it was in the past. When placing Flint and Steel, sometimes it will not stay on the ground and can result in some serious gameplay skews. I seem to only have trouble placing it while placing it almost immediately after quickly switching to my FnS. Could the problem lie in the fact that there is a restriction on how fast somebody can place Flint and Steel after switching to it to prevent macroes? If so, that limit may need to be shortened as some people with quick reflexes are still restricted from placing it.

In a Survival Games/MCSG Maker/Solo SG game, try placing to flint and steel quickly then placing it on the ground.

**Comment by CAmadeusA** [comment]
Hey! This issue will be resolved in the next update. Thank you for reporting :)
