### ISSUE TITLE
Dont Have Macros!!!!

### ISSUE THREAD

**Issue by ImSanti** [MCGamerNetwork/Issues#892]
I do not use macros !!! . What is this?
http://i.imgur.com/cVZ4QLR.png?1

At the time of kick this was my ping. Dont Have Macros!!!
http://i.imgur.com/5qE2Xbr.png?1

**Comment by CAmadeusA** [comment]
Hey there! If you'd like to dispute your ban, you can dispute it at http://www.dispute.mcgamer.info. Be sure to follow the template. Thank you!
