### ISSUE TITLE
Flint and Steel Glitch

### ISSUE THREAD

**Issue by iRocki** [MCGamerNetwork/Issues#898]
I know this issue has been brought up multiple times and I know it is used to prevent macro users but whenever I use the flint and steel very fast then it places for one second and disappears.

**Comment by Envici** [comment]
Duplicate of #891 and has already been fixed. As CAm stated, it will be resolved in the next update.

**Comment by arsenalfcgunners** [comment]
Even with the last update the glitch is still occurring.  https://youtu.be/PVoxQr1_pok
