### ISSUE TITLE
Battlegrounds "Gamemaster" Visibility Glitch

### ISSUE THREAD

**Issue by ApexMC** [MCGamerNetwork/Issues#899]
So while in battlegrounds I have noticed that people can easily see my floating head while they are in the game. Here is a clip as an example when I was in battlegrounds spectating a hacker. 

https://www.youtube.com/watch?v=J_OKTE-WhxI&feature=youtu.be

**Comment by arsenalfcgunners** [comment]
Duplicate of #763 :P
