### ISSUE TITLE
AU MCSG - Unable to take items from chests

### ISSUE THREAD

**Issue by HowlingWinds** [MCGamerNetwork/Issues#902]
In the MCSG server, 1258 [as at 2/1/2016 AEST] you are unable to take items from the chest. when you put them into your inventory, it puts it back in chest, so basically its a punching battle. while it is quite fun, it is pretty annoying ;-;

**Comment by CAmadeusA** [comment]
Issue was just corrected and should be fixed asap.

**Comment by Gjosiah** [comment]
Sorry, this appears to have been an issue in the latest beta release, a fix is being pushed and should be live within the hour. Thank you for reporting it.
