### ISSUE TITLE
SG 4 - Bug

### ISSUE THREAD

**Issue by HomeGoods** [MCGamerNetwork/Issues#904]
Tips to remember while submitting an issue (please read this carefully before submitting your issue report):
- Search the issue tracker to ensure that your issue is not a duplicate.
- Be clear and concise in your description.
- Submit one issue per report. Putting multiple issues into one report makes it difficult for us to separate and identify the issues within our code. If you submit multiple issues in one bug report, your report will be closed and you will be asked to separate them.

Try to separate your issue report into four different sections, if possible:
1. Environment
SG 484- SG 4 - US

2. The issue
SG 4 is completely bugged out and broken. (Check Screenshot) 

3. Steps to reproduce
The entire map is just split in half.

4. Miscellaneous information
http://imgur.com/R4hCNLn

Please remove the above text before submitting your issue report, but DO NOT REMOVE ANYTHING BELOW THIS LINE! The information below this line will help us find the issue faster.
----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 39367).

**Comment by CAmadeusA** [comment]
This issue has been resolved. Thank you for reporting, have a great day.
