### ISSUE TITLE
Spectators can trigger trip wires

### ISSUE THREAD

**Issue by DarkNiightz** [MCGamerNetwork/Issues#905]
I was spectating a game and then I kinda rank into a trip wire and the doors beside it opened. This is not a major bug but if there's somebody near a trap and it takes a trip wire to trigger it then people could abuse that. 

Server and Time: - EU 1726 - 05.02 / 11:16Z 2016  (I'm pretty sure it happens on all servers)

https://youtu.be/nOMXsDu4PWs

**Comment by CAmadeusA** [comment]
Thank you for reporting, this will be fixed in the next push. Have a great day!
