### ISSUE TITLE
MCSG Maker - Mods can't tell if knockback is disabled

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#913]
If a player reports a no knockback hacker with a video from a MCSG Maker game mods can't tell if knockback was enabled or not.

**Comment by CAmadeusA** [comment]
Thank you for reporting, this issue will be fixed in both the next update, and as well as when the admins announce that you can read the side bar time stamp. There's an M in it indicating its an MCSGMaker Game. _cough cough_
