### ISSUE TITLE
Deathmatch player invisibility

### ISSUE THREAD

**Issue by VigiloMCGamer** [MCGamerNetwork/Issues#914]
**Environment**

±16:30 GMT 
EU SoloSG 1498
Return to Moonbase 9

**The issue**

The player is not able to see his opponent in the deathmatch:
https://www.youtube.com/watch?v=UizHMEVhmbA&feature=youtu.be

**Steps to reproduce**

It could happen more often, I have only experienced it once.

**Comment by CAmadeusA** [comment]
This _should_ be resolved in the next update. Thank you for reporting.
