### ISSUE TITLE
My Stats Not Going Up (not updating)

### ISSUE THREAD

**Issue by volkainstain** [MCGamerNetwork/Issues#916]
http://www.mcgamer.net/round/solosg/?round=1774329 // I lost the round
http://www.mcgamer.net/round/solosg/?round=1785987 // I won the round

And a lot more won/lost rounds. But my stats not going up (not updating). If you want to see dates, you can see in the above rounds. (sorry for my bad english :c)

http://www.mcgamer.net/player/UnRaisen

Watch this please
[https://www.youtube.com/watch?v=K7XbfU2CIjw](url)

**Comment by forairan** [comment]
Your stats are updating properly internally, but are not displaying correctly on the website at the current moment due to name changes. This issue should resolve itself in about a week when our system updates the list of recent name changes.
