### ISSUE TITLE
Sprint Glitch on Different Clients

### ISSUE THREAD

**Issue by ApexMC** [MCGamerNetwork/Issues#917]
The video displayed below shows AfricanSwallow and I in a game together. The video playing in the top left hand corner of the screen in AfricanSwallow's perspective and the on screen video is my perspective. The glitch is when 2 people are on different clients and 1 player crouches in the lobby before the game starts, then the player that crouched with appear as if he is sprinting while crouching to the other player. 

https://www.youtube.com/watch?v=9AmFjkd_poU&feature=youtu.be

A few people have been punished for this mistake and hopefully this video clears up the issue. Again the video is the top left is AfricanSwallow's view and he cannot see himself crouching. Whereas in my perspective it looks like he is crouching and sprinting at the same time.

**Comment by CAmadeusA** [comment]
Thank you for reporting, this will be fixed in the next push. Have a great day!
