### ISSUE TITLE
Name and Stats bug for "Ruche"

### ISSUE THREAD

**Issue by WilliamFTW** [MCGamerNetwork/Issues#918]
-Environment:
None really, it's the name bug.
-The issue:
The user "Ruche" 's stats aren't counting.
Correct user: http://manage.mcgamer.net/player/uuid/4b8d59a4e3104a7db1738e98dad72e20/
The other user that is causing the issue: http://manage.mcgamer.net/player/uuid/783a447196384135b5deabfef1988e66/
-Steps to reproduce:
I'm not sure what you do, but update the database so the stats are counting for the correct user.
-Miscellaneous information
None.

**Comment by WilliamFTW** [comment]
User is also requesting a reset of stats, I am not sure if that's possible for the situation but yeah. 
Have a nice day! :+1:

**Comment by forairan** [comment]
The stats are indeed counting internally, but just aren't being displayed on the website properly due to name changes. It'll be picked up next time the name change script finishes running - probably in about a week.
