### ISSUE TITLE
Hub GUI not working?

### ISSUE THREAD

**Issue by DarkNiightz** [MCGamerNetwork/Issues#921]
1. Environment
EU HUB / SoloSG - 2789 - 22.02 07:08Z 2016

More reports show that most of the EU hub GUI is broken.

2. The issue

I tried to connect to another HUB server using the GUI and instead of sending me to a hub it sent me to a SoloSG game.

After further investigation, I've tried to join multiple games using the GUI lobby selector and it either took me to a live game or a completely different server (BG). I also tried to connect to a SoloSG lobby and it connected me to a Normal SG live game. You should be able to reproduce to issue by logging onto EU and trying to connect to the servers through the GUI.

3. Steps to reproduce

I don't know if this will still be a problem when you see this but if you go onto the EU network and look for the 2789 enderpearl and click it, it should take you to a SoloSG game.

4. Miscellaneous information

https://youtu.be/OyogAa10VNo
https://youtu.be/sFxYLV1koT0

----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 41281).

**Comment by CAmadeusA** [comment]
Im confident this issue has already been resolved. If it has not, please repost.
