### ISSUE TITLE
1.9 Boats

### ISSUE THREAD

**Issue by DarkNiightz** [MCGamerNetwork/Issues#926]
EU: 2791 - 29.02.2016 / 23:11ZT

When you try and use a boat on 1.9 it kicks you for "Xac: Detected use of Cheat / Macro". I think it might think you're flying or something. You should be able to reproduce this by going into a SG game and using a boat on 1.9.

----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 41739).

**Comment by CAmadeusA** [comment]
Hey, this has been resolved in the latest update. Thanks for reporting.
