### ISSUE TITLE
Don't receive a sword upon spawning in battle grounds

### ISSUE THREAD

**Issue by Vladipiggy** [MCGamerNetwork/Issues#928]
When I spawn in battle grounds I get a compass, iron leggings, iron chestplate, iron helmet, 2 golden apples, some steak, and 64 arrows. Every time i restarted everything, my minecraft my pc even my routher

**Comment by CAmadeusA** [comment]
Hey! This should be fixed in the next update. Thank you for reporting. Have a great day!
