### ISSUE TITLE
Battlegrounds Kit Glitch

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#932]
This glitch doesn't happen with out #931, or at least I have not found a way to trigger it without the compass glitch. But basically this is what happens. If you do the compass glitch, and then use the glitch to spawn again in game you end up with two full kits in your inventory as you have spawned an extra time. Here is where the glitch occurs. 

The server correctly notices that something is wrong, and you get a message in chat saying that it has attempted to fix your kit and you may want to rearrange it or something like that.  However instead of fixing it, all it does is double what you already had. So for example if I had 4 kits from the compass glitch, after the server attempted to fix my inventory I would have 8 kits saved.

Both these glitches are permanently saved in my inventory, and there is no way for me to reset it. So now if I log into a battlegrounds game I will be given 8 kits every time. I am not going to play any BG on my main account until this gets fixed cause I don't want to be abusing a glitch. But anyway this is what I figured out. A lot of people have been abusing this so I hope this helps.

Screenshots (Before the server attempted to fix my kits): http://i.imgur.com/LScEu5t.png As you can see here my custom inventory already has too many kits from the compass glitch.

This is what it looks like after I get the message saying that the server has attempted to fix that issue:
http://imgur.com/a/TWckR

**Comment by arsenalfcgunners** [comment]
If any of the above is confusing and needs clarification let me know. I probably explained that horribly.

**Comment by CAmadeusA** [comment]
This issue has been resolved, thank you for reporting. Have a great day.
