### ISSUE TITLE
Stone sword/Fire

### ISSUE THREAD

**Issue by yannr00s** [MCGamerNetwork/Issues#934]
In US SG 661, if you right click a stone sword it would light the block on fire, acting as if the stone sword is a flint and steel.

**Comment by CAmadeusA** [comment]
Hey, Im unable to reproduce, is there a specific way that this is triggered?

**Comment by Envici** [comment]
Could be an item ghosting situation. I have heard of problems where a player can have nothing in their hand, but be dealing as much damage as a sword.

**Comment by arsenalfcgunners** [comment]
What version of MC are you on @yannr00s?

**Comment by arsenalfcgunners** [comment]
Yeah it could be that Envici. Probably is in fact.

**Comment by yannr00s** [comment]
This was reported to me by DammitDeanne. She was playing on Minecraft 1.8 and I as a spectator on 1.8 saw her holding a stone sword and lighting the blocks on fire.

**Comment by arsenalfcgunners** [comment]
If you both saw it then it is probably not an item ghosting... But idk for sure.

**Comment by yannr00s** [comment]
I am guessing this is related. I got this video from a community member: https://youtu.be/mhMaZ_SNSqQ

**Comment by CAmadeusA** [comment]
This _should_ be resolved in the next update, thank you for reporting and have a great day!
