### ISSUE TITLE
Aesthetics

### ISSUE THREAD

**Issue by TheZombieKat** [MCGamerNetwork/Issues#935]
On the SG map Turbulence, there's a room over by these aircraft hangers. You push a button, and the door opens. For the exiting door, there's a block missing, exposing the redstone. I just thought you guys would want to know. It's not game breaking, or a glitch. I figured you would want to know about it, though.
The cords to where it is are: 
x = 980
z = -30

**Comment by CAmadeusA** [comment]
Hey, this issue has been resolved. Thank you for reporting.
