### ISSUE TITLE
1.9 right clicks not registering properly

### ISSUE THREAD

**Issue by arsenalfcgunners** [MCGamerNetwork/Issues#936]
I have seen other reports of this bug. I got it to occur on US BG 454 in 1.9. I tried to shoot a bow, it pulled back but did not shoot the arrow upon release.  Also, I tried eating food, it did not eat instead it just kept making the chugging sound until I let go of right click.  Same can be said for the rod, it does not cast properly.

All of this only happens on occasion. But it happens quite often.

A state dump was generated and submitted successfully (ID number 41755).

**Comment by forairan** [comment]
This should be fixed in the next release. Thanks for the report!
