### ISSUE TITLE
Battlegrounds - Kit Duplication Glitch

### ISSUE THREAD

**Issue by ApexMC** [MCGamerNetwork/Issues#939]
http://i.imgur.com/RMWHqmB.png

The link above shows an inventory full of kits. This can be achieved by right clicking on a teleport sign with the compass. The kit gui will remain up and if you try and edit your kit while in the game, the next time you die you will have 2 of the same kit. I did this multiple times simply to get as much evidence as possible.

**Comment by CAmadeusA** [comment]
Hey, thanks for reporting, this will be fixed in the next update. Have a great day!
