### ISSUE TITLE
Battlegrounds Glitch!

### ISSUE THREAD

**Issue by RekItPVP** [MCGamerNetwork/Issues#942]
So, When I warp anywhere I don't have a diamond sword, flint and steel or golden apples! The only thing I have is 2 bows, 64 arrows and iron armour. Everybody else has everything and they just kill me!

**Comment by arsenalfcgunners** [comment]
Yeah, I don't get any arrows. I get like 6 swords though, and tons of FNS. Really weird. I wish there was a way to reset your kit.

**Comment by arsenalfcgunners** [comment]
Oh wait you can do /resetkit. Just saw @CAmadeusA post that on another issue.

**Comment by RekItPVP** [comment]
Thanks!
