### ISSUE TITLE
Eating glitch

### ISSUE THREAD

**Issue by VigiloMCGamer** [MCGamerNetwork/Issues#944]
**Environment**

EU, SG, 05:03PM CET

**The issue**

When eating food, it sometimes doesn't add up on your food bar (or disappears quickly after eating). When you open your inventory and click on where the food you ate was, the food spawns back. 

https://www.youtube.com/watch?v=J7SPWcJMQa0&feature=youtu.be

This is especially very annoying when you're trying to gain up health by eating a golden apple. 

**Steps to reproduce**

Play SG and eat. It won't occur every time, but eventually it will happen.

**Comment by CAmadeusA** [comment]
This _should_ be resolved in the latest fix, please re-post if this is still an issue.
