### ISSUE TITLE
Flint And Steel

### ISSUE THREAD

**Issue by Scout325** [MCGamerNetwork/Issues#945]
1. Environment
SG gamemode, occures in every server.

2. The issue
Flint And Steel doesn't work properly and it should be fixed. It sometimes places and sometimes it doesn't. It doesn't place when you want to quick place and fns behind you or you switch to your fns too fast. You can see the fire placing and disappearing right away.

3. Steps to reproduce
Just play a game on survival games and you'll see what I mean, try switching from something to your fns and placing it right away or run and place the fire right when you turn around. It's really random and there are not steps to reproduce as far as I know, it just happens randomly. Sometimes it places, sometimes it doesn't.

4. Miscellaneous information
https://www.youtube.com/watch?v=vzxvWZ65oYE
You can clearly see me placing fns on 0:30 and it disappeares right away.

----------------------------------------------------------------------------------------------------------------------------------------
A state dump was generated and submitted successfully (ID number 42524).

**Comment by arsenalfcgunners** [comment]
Seems to occur almost every time you quickly switch to FNS and try to place. If you switch and then wait a second it doesn't seem to ever glitch.

**Comment by forairan** [comment]
Should be fixed.
