### ISSUE TITLE
Holiday Resort 2 - Pressure Plates

### ISSUE THREAD

**Issue by roygator14** [MCGamerNetwork/Issues#948]
On Holiday Resort 2, running into the pressure plates on fence posts, drops a substantial amount of pressure plates on the ground, and breaks the one currently on the post.

**Comment by NagolGames** [comment]
Hey there, Roy! [ @roygator14 ]

In order to get this issue resolved as quick as possible, could you possible include screenshots + coordinates of where this has happened to you please? 

Thanks!

NagolGames
MCGamer Administrator
