### ISSUE TITLE
SG/MCSG Maker isn't working

### ISSUE THREAD

**Issue by ThaLichBD** [MCGamerNetwork/Issues#950]
When you try to create a SG on MCSG/SG Maker, this it what is says: 
Non-cuted screenshot: http://i.imgur.com/6Lacfc0.jpg
Cuted Screenshot: http://i.imgur.com/CAwuYUB.jpg?1

In less words, when you send a request for creating a game, it will say that the request has been send and some seconds later it will say that an error has occurred and that you won't be able to create that arena.

**Comment by forairan** [comment]
This appears to have been fixed.
