### ISSUE TITLE
Lost my donator

### ISSUE THREAD

**Issue by DoomsKun** [MCGamerNetwork/Issues#955]
Yo, today I joined and I saw that my donator just disappeared (Got a Platinum sponsor lifetime)
IGN: DoomsKun
Proof of my In-Game rank: http://imgur.com/nMEqU98
Proof that I lost my donator: http://imgur.com/a/YKPuN
Proof of lifetime purchase (unfortunately deleted the mail, but as you can see I got stat tokens from the donation): http://imgur.com/epp5VRO
Can someone help me, please?

**Comment by forairan** [comment]
You'll need to contact support@mcgamer.net for help with this.
