### ISSUE TITLE
Multiple Sets in BattleGrounds

### ISSUE THREAD

**Issue by aegislash714** [MCGamerNetwork/Issues#957]
Hi, My ingame IGN is aegislash714 and I am a player on the McGamer Network. I came here to report and Issue in your Game call 'BattleGrounds'

Issue: In BattleGrounds, on my first Day, I had a normal inventory, one set. Now after I don't know what, I gradually got more and more sets until it turned into this: 
![2016-04-17_16 06 05](https://cloud.githubusercontent.com/assets/18512304/14586487/57d482ee-04b7-11e6-9885-cce6a74502bd.png)

Plz Fix, I don't have any space for the golden apples I get for Killing someone.
Thx :)

**Comment by TehJakee** [comment]
Same here

**Comment by TehJakee** [comment]
My ign is jaka_ so if you can please reset my inventory in battlegrounds
