### ISSUE TITLE
Grace period in MCSG Maker didn't work

### ISSUE THREAD

**Issue by Alkan1** [MCGamerNetwork/Issues#960]
I was playing an mcsg maker game with some friends, and these were the mutators that were active: 

![](http://i.imgur.com/eVDECAq.png)

I don't know why, but they killed me while we were in the grace period, I don't know how is that possible, maybe something about no hit delay mutator?

State Dump ID: #44273

**Comment by CAmadeusA** [comment]
This will be resolved in the next update. Thank you for reporting! Have a great day.
