### ISSUE TITLE
Anti-Cheat Glitch

### ISSUE THREAD

**Issue by iRocki** [MCGamerNetwork/Issues#962]
Players who have bad connection to the EU or US servers are getting kicked by the XAC Anti Cheat for no apparent reason. Also the player lives in Norway and was playing on the US server. Se clicked once and got banned by the anti- cheat. After that she was lagging then moved then got banned again.

Thanks

**Comment by CAmadeusA** [comment]
Hey! This has been resolved, thanks for reporting.
