### ISSUE TITLE
Horrible Issues with Survival Games Bingo

### ISSUE THREAD

**Issue by Shugann** [MCGamerNetwork/Issues#964]
**Horrible Issues with Survival Games Bingo** 

    Environment: Survival Games Bingo, USA Server. 
    The Issue:
        - Invisible Mobs
        - No Bingo Slot reward for ...
            1. Wearing Full Leather Armor
            2. Wearing Full Iron Armor
            3. Putting a Pumpkin on Head
            4. Obtaining 6 Types of Slabs
            5. Obtaining Music Discs
            6. Having 6 Different Kinds of Wool
            7. Obtaining a Golden Apple
            8. Having a Stack of 64 Items

**Comment by arsenalfcgunners** [comment]
Knowing how much MCG puts into its less popular gamemodes I would be shocked if this gets fixed. I don't understand why they don't just get rid of these underplayed gamemodes.

**Comment by arsenalfcgunners** [comment]
I heard a rumor that stuff will be happening soon with these underplayed gamemodes. I hope it is true.

**Comment by Shugann** [comment]
Yeah, don't say stuff like that. They don't need to be removed, only fixed.
